/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for Attributes8 type.
 */
public class Attributes8 {
    private String baseTokenAddress;
    private String quoteTokenAddress;
    private List<String> quoteTokenAddresses;
    private Double sentimentVotePositivePercentage;
    private Double sentimentVoteNegativePercentage;
    private Integer communitySusReport;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Attributes8() {
    }

    /**
     * Initialization constructor.
     * @param  baseTokenAddress  String value for baseTokenAddress.
     * @param  quoteTokenAddress  String value for quoteTokenAddress.
     * @param  quoteTokenAddresses  List of String value for quoteTokenAddresses.
     * @param  sentimentVotePositivePercentage  Double value for sentimentVotePositivePercentage.
     * @param  sentimentVoteNegativePercentage  Double value for sentimentVoteNegativePercentage.
     * @param  communitySusReport  Integer value for communitySusReport.
     */
    public Attributes8(
            String baseTokenAddress,
            String quoteTokenAddress,
            List<String> quoteTokenAddresses,
            Double sentimentVotePositivePercentage,
            Double sentimentVoteNegativePercentage,
            Integer communitySusReport) {
        this.baseTokenAddress = baseTokenAddress;
        this.quoteTokenAddress = quoteTokenAddress;
        this.quoteTokenAddresses = quoteTokenAddresses;
        this.sentimentVotePositivePercentage = sentimentVotePositivePercentage;
        this.sentimentVoteNegativePercentage = sentimentVoteNegativePercentage;
        this.communitySusReport = communitySusReport;
    }

    /**
     * Getter for BaseTokenAddress.
     * Base token contract address
     * @return Returns the String
     */
    @JsonGetter("base_token_address")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getBaseTokenAddress() {
        return baseTokenAddress;
    }

    /**
     * Setter for BaseTokenAddress.
     * Base token contract address
     * @param baseTokenAddress Value for String
     */
    @JsonSetter("base_token_address")
    public void setBaseTokenAddress(String baseTokenAddress) {
        this.baseTokenAddress = baseTokenAddress;
    }

    /**
     * Getter for QuoteTokenAddress.
     * Quote token contract address
     * @return Returns the String
     */
    @JsonGetter("quote_token_address")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getQuoteTokenAddress() {
        return quoteTokenAddress;
    }

    /**
     * Setter for QuoteTokenAddress.
     * Quote token contract address
     * @param quoteTokenAddress Value for String
     */
    @JsonSetter("quote_token_address")
    public void setQuoteTokenAddress(String quoteTokenAddress) {
        this.quoteTokenAddress = quoteTokenAddress;
    }

    /**
     * Getter for QuoteTokenAddresses.
     * Quote token contract addresses, present for pools with more than 2 tokens
     * @return Returns the List of String
     */
    @JsonGetter("quote_token_addresses")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getQuoteTokenAddresses() {
        return quoteTokenAddresses;
    }

    /**
     * Setter for QuoteTokenAddresses.
     * Quote token contract addresses, present for pools with more than 2 tokens
     * @param quoteTokenAddresses Value for List of String
     */
    @JsonSetter("quote_token_addresses")
    public void setQuoteTokenAddresses(List<String> quoteTokenAddresses) {
        this.quoteTokenAddresses = quoteTokenAddresses;
    }

    /**
     * Getter for SentimentVotePositivePercentage.
     * GeckoTerminal community positive sentiment vote percentage
     * @return Returns the Double
     */
    @JsonGetter("sentiment_vote_positive_percentage")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getSentimentVotePositivePercentage() {
        return sentimentVotePositivePercentage;
    }

    /**
     * Setter for SentimentVotePositivePercentage.
     * GeckoTerminal community positive sentiment vote percentage
     * @param sentimentVotePositivePercentage Value for Double
     */
    @JsonSetter("sentiment_vote_positive_percentage")
    public void setSentimentVotePositivePercentage(Double sentimentVotePositivePercentage) {
        this.sentimentVotePositivePercentage = sentimentVotePositivePercentage;
    }

    /**
     * Getter for SentimentVoteNegativePercentage.
     * GeckoTerminal community negative sentiment vote percentage
     * @return Returns the Double
     */
    @JsonGetter("sentiment_vote_negative_percentage")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getSentimentVoteNegativePercentage() {
        return sentimentVoteNegativePercentage;
    }

    /**
     * Setter for SentimentVoteNegativePercentage.
     * GeckoTerminal community negative sentiment vote percentage
     * @param sentimentVoteNegativePercentage Value for Double
     */
    @JsonSetter("sentiment_vote_negative_percentage")
    public void setSentimentVoteNegativePercentage(Double sentimentVoteNegativePercentage) {
        this.sentimentVoteNegativePercentage = sentimentVoteNegativePercentage;
    }

    /**
     * Getter for CommunitySusReport.
     * GeckoTerminal community suspicious reports count
     * @return Returns the Integer
     */
    @JsonGetter("community_sus_report")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getCommunitySusReport() {
        return communitySusReport;
    }

    /**
     * Setter for CommunitySusReport.
     * GeckoTerminal community suspicious reports count
     * @param communitySusReport Value for Integer
     */
    @JsonSetter("community_sus_report")
    public void setCommunitySusReport(Integer communitySusReport) {
        this.communitySusReport = communitySusReport;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Attributes8 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Attributes8 [" + "baseTokenAddress=" + baseTokenAddress + ", quoteTokenAddress="
                + quoteTokenAddress + ", quoteTokenAddresses=" + quoteTokenAddresses
                + ", sentimentVotePositivePercentage=" + sentimentVotePositivePercentage
                + ", sentimentVoteNegativePercentage=" + sentimentVoteNegativePercentage
                + ", communitySusReport=" + communitySusReport + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Attributes8.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Attributes8.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .baseTokenAddress(getBaseTokenAddress())
                .quoteTokenAddress(getQuoteTokenAddress())
                .quoteTokenAddresses(getQuoteTokenAddresses())
                .sentimentVotePositivePercentage(getSentimentVotePositivePercentage())
                .sentimentVoteNegativePercentage(getSentimentVoteNegativePercentage())
                .communitySusReport(getCommunitySusReport());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Attributes8}.
     */
    public static class Builder {
        private String baseTokenAddress;
        private String quoteTokenAddress;
        private List<String> quoteTokenAddresses;
        private Double sentimentVotePositivePercentage;
        private Double sentimentVoteNegativePercentage;
        private Integer communitySusReport;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for baseTokenAddress.
         * @param  baseTokenAddress  String value for baseTokenAddress.
         * @return Builder
         */
        public Builder baseTokenAddress(String baseTokenAddress) {
            this.baseTokenAddress = baseTokenAddress;
            return this;
        }

        /**
         * Setter for quoteTokenAddress.
         * @param  quoteTokenAddress  String value for quoteTokenAddress.
         * @return Builder
         */
        public Builder quoteTokenAddress(String quoteTokenAddress) {
            this.quoteTokenAddress = quoteTokenAddress;
            return this;
        }

        /**
         * Setter for quoteTokenAddresses.
         * @param  quoteTokenAddresses  List of String value for quoteTokenAddresses.
         * @return Builder
         */
        public Builder quoteTokenAddresses(List<String> quoteTokenAddresses) {
            this.quoteTokenAddresses = quoteTokenAddresses;
            return this;
        }

        /**
         * Setter for sentimentVotePositivePercentage.
         * @param  sentimentVotePositivePercentage  Double value for
         *         sentimentVotePositivePercentage.
         * @return Builder
         */
        public Builder sentimentVotePositivePercentage(Double sentimentVotePositivePercentage) {
            this.sentimentVotePositivePercentage = sentimentVotePositivePercentage;
            return this;
        }

        /**
         * Setter for sentimentVoteNegativePercentage.
         * @param  sentimentVoteNegativePercentage  Double value for
         *         sentimentVoteNegativePercentage.
         * @return Builder
         */
        public Builder sentimentVoteNegativePercentage(Double sentimentVoteNegativePercentage) {
            this.sentimentVoteNegativePercentage = sentimentVoteNegativePercentage;
            return this;
        }

        /**
         * Setter for communitySusReport.
         * @param  communitySusReport  Integer value for communitySusReport.
         * @return Builder
         */
        public Builder communitySusReport(Integer communitySusReport) {
            this.communitySusReport = communitySusReport;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Attributes8} object using the set fields.
         * @return {@link Attributes8}
         */
        public Attributes8 build() {
            Attributes8 model =
                    new Attributes8(baseTokenAddress, quoteTokenAddress, quoteTokenAddresses,
                            sentimentVotePositivePercentage, sentimentVoteNegativePercentage,
                            communitySusReport);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
