/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Attributes1 type.
 */
public class Attributes1 {
    private String address;
    private String name;
    private String symbol;
    private Integer decimals;
    private String imageUrl;
    private String coingeckoCoinId;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Attributes1() {
    }

    /**
     * Initialization constructor.
     * @param  address  String value for address.
     * @param  name  String value for name.
     * @param  symbol  String value for symbol.
     * @param  decimals  Integer value for decimals.
     * @param  imageUrl  String value for imageUrl.
     * @param  coingeckoCoinId  String value for coingeckoCoinId.
     */
    public Attributes1(
            String address,
            String name,
            String symbol,
            Integer decimals,
            String imageUrl,
            String coingeckoCoinId) {
        this.address = address;
        this.name = name;
        this.symbol = symbol;
        this.decimals = decimals;
        this.imageUrl = imageUrl;
        this.coingeckoCoinId = coingeckoCoinId;
    }

    /**
     * Getter for Address.
     * @return Returns the String
     */
    @JsonGetter("address")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAddress() {
        return address;
    }

    /**
     * Setter for Address.
     * @param address Value for String
     */
    @JsonSetter("address")
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for Symbol.
     * @return Returns the String
     */
    @JsonGetter("symbol")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSymbol() {
        return symbol;
    }

    /**
     * Setter for Symbol.
     * @param symbol Value for String
     */
    @JsonSetter("symbol")
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    /**
     * Getter for Decimals.
     * @return Returns the Integer
     */
    @JsonGetter("decimals")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getDecimals() {
        return decimals;
    }

    /**
     * Setter for Decimals.
     * @param decimals Value for Integer
     */
    @JsonSetter("decimals")
    public void setDecimals(Integer decimals) {
        this.decimals = decimals;
    }

    /**
     * Getter for ImageUrl.
     * @return Returns the String
     */
    @JsonGetter("image_url")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * Setter for ImageUrl.
     * @param imageUrl Value for String
     */
    @JsonSetter("image_url")
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    /**
     * Getter for CoingeckoCoinId.
     * @return Returns the String
     */
    @JsonGetter("coingecko_coin_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCoingeckoCoinId() {
        return coingeckoCoinId;
    }

    /**
     * Setter for CoingeckoCoinId.
     * @param coingeckoCoinId Value for String
     */
    @JsonSetter("coingecko_coin_id")
    public void setCoingeckoCoinId(String coingeckoCoinId) {
        this.coingeckoCoinId = coingeckoCoinId;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Attributes1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Attributes1 [" + "address=" + address + ", name=" + name + ", symbol=" + symbol
                + ", decimals=" + decimals + ", imageUrl=" + imageUrl + ", coingeckoCoinId="
                + coingeckoCoinId + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Attributes1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Attributes1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .address(getAddress())
                .name(getName())
                .symbol(getSymbol())
                .decimals(getDecimals())
                .imageUrl(getImageUrl())
                .coingeckoCoinId(getCoingeckoCoinId());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Attributes1}.
     */
    public static class Builder {
        private String address;
        private String name;
        private String symbol;
        private Integer decimals;
        private String imageUrl;
        private String coingeckoCoinId;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for address.
         * @param  address  String value for address.
         * @return Builder
         */
        public Builder address(String address) {
            this.address = address;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for symbol.
         * @param  symbol  String value for symbol.
         * @return Builder
         */
        public Builder symbol(String symbol) {
            this.symbol = symbol;
            return this;
        }

        /**
         * Setter for decimals.
         * @param  decimals  Integer value for decimals.
         * @return Builder
         */
        public Builder decimals(Integer decimals) {
            this.decimals = decimals;
            return this;
        }

        /**
         * Setter for imageUrl.
         * @param  imageUrl  String value for imageUrl.
         * @return Builder
         */
        public Builder imageUrl(String imageUrl) {
            this.imageUrl = imageUrl;
            return this;
        }

        /**
         * Setter for coingeckoCoinId.
         * @param  coingeckoCoinId  String value for coingeckoCoinId.
         * @return Builder
         */
        public Builder coingeckoCoinId(String coingeckoCoinId) {
            this.coingeckoCoinId = coingeckoCoinId;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Attributes1} object using the set fields.
         * @return {@link Attributes1}
         */
        public Attributes1 build() {
            Attributes1 model =
                    new Attributes1(address, name, symbol, decimals, imageUrl, coingeckoCoinId);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
