/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.types.OptionalNullable;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Base type.
 */
public class Base {
    private String name;
    private String symbol;
    private OptionalNullable<String> coingeckoCoinId;
    private String address;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Base() {
    }

    /**
     * Initialization constructor.
     * @param  name  String value for name.
     * @param  symbol  String value for symbol.
     * @param  coingeckoCoinId  String value for coingeckoCoinId.
     * @param  address  String value for address.
     */
    public Base(
            String name,
            String symbol,
            String coingeckoCoinId,
            String address) {
        this.name = name;
        this.symbol = symbol;
        this.coingeckoCoinId = OptionalNullable.of(coingeckoCoinId);
        this.address = address;
    }

    /**
     * Initialization constructor.
     * @param  name  String value for name.
     * @param  symbol  String value for symbol.
     * @param  coingeckoCoinId  String value for coingeckoCoinId.
     * @param  address  String value for address.
     */

    protected Base(String name, String symbol, OptionalNullable<String> coingeckoCoinId,
            String address) {
        this.name = name;
        this.symbol = symbol;
        this.coingeckoCoinId = coingeckoCoinId;
        this.address = address;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for Symbol.
     * @return Returns the String
     */
    @JsonGetter("symbol")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSymbol() {
        return symbol;
    }

    /**
     * Setter for Symbol.
     * @param symbol Value for String
     */
    @JsonSetter("symbol")
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    /**
     * Internal Getter for CoingeckoCoinId.
     * @return Returns the Internal String
     */
    @JsonGetter("coingecko_coin_id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetCoingeckoCoinId() {
        return this.coingeckoCoinId;
    }

    /**
     * Getter for CoingeckoCoinId.
     * @return Returns the String
     */
    public String getCoingeckoCoinId() {
        return OptionalNullable.getFrom(coingeckoCoinId);
    }

    /**
     * Setter for CoingeckoCoinId.
     * @param coingeckoCoinId Value for String
     */
    @JsonSetter("coingecko_coin_id")
    public void setCoingeckoCoinId(String coingeckoCoinId) {
        this.coingeckoCoinId = OptionalNullable.of(coingeckoCoinId);
    }

    /**
     * UnSetter for CoingeckoCoinId.
     */
    public void unsetCoingeckoCoinId() {
        coingeckoCoinId = null;
    }

    /**
     * Getter for Address.
     * @return Returns the String
     */
    @JsonGetter("address")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAddress() {
        return address;
    }

    /**
     * Setter for Address.
     * @param address Value for String
     */
    @JsonSetter("address")
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Base into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Base [" + "name=" + name + ", symbol=" + symbol + ", coingeckoCoinId="
                + coingeckoCoinId + ", address=" + address + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Base.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Base.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .name(getName())
                .symbol(getSymbol())
                .address(getAddress());
        builder.coingeckoCoinId = internalGetCoingeckoCoinId();
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Base}.
     */
    public static class Builder {
        private String name;
        private String symbol;
        private OptionalNullable<String> coingeckoCoinId;
        private String address;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for symbol.
         * @param  symbol  String value for symbol.
         * @return Builder
         */
        public Builder symbol(String symbol) {
            this.symbol = symbol;
            return this;
        }

        /**
         * Setter for coingeckoCoinId.
         * @param  coingeckoCoinId  String value for coingeckoCoinId.
         * @return Builder
         */
        public Builder coingeckoCoinId(String coingeckoCoinId) {
            this.coingeckoCoinId = OptionalNullable.of(coingeckoCoinId);
            return this;
        }

        /**
         * UnSetter for coingeckoCoinId.
         * @return Builder
         */
        public Builder unsetCoingeckoCoinId() {
            coingeckoCoinId = null;
            return this;
        }

        /**
         * Setter for address.
         * @param  address  String value for address.
         * @return Builder
         */
        public Builder address(String address) {
            this.address = address;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Base} object using the set fields.
         * @return {@link Base}
         */
        public Base build() {
            Base model =
                    new Base(name, symbol, coingeckoCoinId, address);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
