/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for Category2 type.
 */
public class Category2 {
    private int id;
    private String name;
    private List<String> top3CoinsImages;
    private double marketCap1HChange;
    private String slug;
    private String coinsCount;
    private Data4 data;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Category2() {
    }

    /**
     * Initialization constructor.
     * @param  id  int value for id.
     * @param  name  String value for name.
     * @param  top3CoinsImages  List of String value for top3CoinsImages.
     * @param  marketCap1HChange  double value for marketCap1HChange.
     * @param  slug  String value for slug.
     * @param  coinsCount  String value for coinsCount.
     * @param  data  Data4 value for data.
     */
    public Category2(
            int id,
            String name,
            List<String> top3CoinsImages,
            double marketCap1HChange,
            String slug,
            String coinsCount,
            Data4 data) {
        this.id = id;
        this.name = name;
        this.top3CoinsImages = top3CoinsImages;
        this.marketCap1HChange = marketCap1HChange;
        this.slug = slug;
        this.coinsCount = coinsCount;
        this.data = data;
    }

    /**
     * Getter for Id.
     * Category ID
     * @return Returns the int
     */
    @JsonGetter("id")
    public int getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Category ID
     * @param id Value for int
     */
    @JsonSetter("id")
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Getter for Name.
     * Category name
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * Category name
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for Top3CoinsImages.
     * Top 3 coins image URLs in the category
     * @return Returns the List of String
     */
    @JsonGetter("top_3_coins_images")
    public List<String> getTop3CoinsImages() {
        return top3CoinsImages;
    }

    /**
     * Setter for Top3CoinsImages.
     * Top 3 coins image URLs in the category
     * @param top3CoinsImages Value for List of String
     */
    @JsonSetter("top_3_coins_images")
    public void setTop3CoinsImages(List<String> top3CoinsImages) {
        this.top3CoinsImages = top3CoinsImages;
    }

    /**
     * Getter for MarketCap1HChange.
     * Category market cap 1 hour change
     * @return Returns the double
     */
    @JsonGetter("market_cap_1h_change")
    public double getMarketCap1HChange() {
        return marketCap1HChange;
    }

    /**
     * Setter for MarketCap1HChange.
     * Category market cap 1 hour change
     * @param marketCap1HChange Value for double
     */
    @JsonSetter("market_cap_1h_change")
    public void setMarketCap1HChange(double marketCap1HChange) {
        this.marketCap1HChange = marketCap1HChange;
    }

    /**
     * Getter for Slug.
     * Category web slug
     * @return Returns the String
     */
    @JsonGetter("slug")
    public String getSlug() {
        return slug;
    }

    /**
     * Setter for Slug.
     * Category web slug
     * @param slug Value for String
     */
    @JsonSetter("slug")
    public void setSlug(String slug) {
        this.slug = slug;
    }

    /**
     * Getter for CoinsCount.
     * Number of coins in the category
     * @return Returns the String
     */
    @JsonGetter("coins_count")
    public String getCoinsCount() {
        return coinsCount;
    }

    /**
     * Setter for CoinsCount.
     * Number of coins in the category
     * @param coinsCount Value for String
     */
    @JsonSetter("coins_count")
    public void setCoinsCount(String coinsCount) {
        this.coinsCount = coinsCount;
    }

    /**
     * Getter for Data.
     * @return Returns the Data4
     */
    @JsonGetter("data")
    public Data4 getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for Data4
     */
    @JsonSetter("data")
    public void setData(Data4 data) {
        this.data = data;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Category2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Category2 [" + "id=" + id + ", name=" + name + ", top3CoinsImages="
                + top3CoinsImages + ", marketCap1HChange=" + marketCap1HChange + ", slug=" + slug
                + ", coinsCount=" + coinsCount + ", data=" + data + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Category2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Category2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, name, top3CoinsImages, marketCap1HChange, slug,
                coinsCount, data);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Category2}.
     */
    public static class Builder {
        private int id;
        private String name;
        private List<String> top3CoinsImages;
        private double marketCap1HChange;
        private String slug;
        private String coinsCount;
        private Data4 data;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  int value for id.
         * @param  name  String value for name.
         * @param  top3CoinsImages  List of String value for top3CoinsImages.
         * @param  marketCap1HChange  double value for marketCap1HChange.
         * @param  slug  String value for slug.
         * @param  coinsCount  String value for coinsCount.
         * @param  data  Data4 value for data.
         */
        public Builder(int id, String name, List<String> top3CoinsImages, double marketCap1HChange,
                String slug, String coinsCount, Data4 data) {
            this.id = id;
            this.name = name;
            this.top3CoinsImages = top3CoinsImages;
            this.marketCap1HChange = marketCap1HChange;
            this.slug = slug;
            this.coinsCount = coinsCount;
            this.data = data;
        }

        /**
         * Setter for id.
         * @param  id  int value for id.
         * @return Builder
         */
        public Builder id(int id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for top3CoinsImages.
         * @param  top3CoinsImages  List of String value for top3CoinsImages.
         * @return Builder
         */
        public Builder top3CoinsImages(List<String> top3CoinsImages) {
            this.top3CoinsImages = top3CoinsImages;
            return this;
        }

        /**
         * Setter for marketCap1HChange.
         * @param  marketCap1HChange  double value for marketCap1HChange.
         * @return Builder
         */
        public Builder marketCap1HChange(double marketCap1HChange) {
            this.marketCap1HChange = marketCap1HChange;
            return this;
        }

        /**
         * Setter for slug.
         * @param  slug  String value for slug.
         * @return Builder
         */
        public Builder slug(String slug) {
            this.slug = slug;
            return this;
        }

        /**
         * Setter for coinsCount.
         * @param  coinsCount  String value for coinsCount.
         * @return Builder
         */
        public Builder coinsCount(String coinsCount) {
            this.coinsCount = coinsCount;
            return this;
        }

        /**
         * Setter for data.
         * @param  data  Data4 value for data.
         * @return Builder
         */
        public Builder data(Data4 data) {
            this.data = data;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Category2} object using the set fields.
         * @return {@link Category2}
         */
        public Category2 build() {
            Category2 model =
                    new Category2(id, name, top3CoinsImages, marketCap1HChange, slug, coinsCount,
                            data);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
