/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for CategoriesList type.
 */
public class CategoriesList {
    private String categoryId;
    private String name;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public CategoriesList() {
    }

    /**
     * Initialization constructor.
     * @param  categoryId  String value for categoryId.
     * @param  name  String value for name.
     */
    public CategoriesList(
            String categoryId,
            String name) {
        this.categoryId = categoryId;
        this.name = name;
    }

    /**
     * Getter for CategoryId.
     * Category ID
     * @return Returns the String
     */
    @JsonGetter("category_id")
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * Setter for CategoryId.
     * Category ID
     * @param categoryId Value for String
     */
    @JsonSetter("category_id")
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * Getter for Name.
     * Category name
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * Category name
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this CategoriesList into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CategoriesList [" + "categoryId=" + categoryId + ", name=" + name
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link CategoriesList.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CategoriesList.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(categoryId, name);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link CategoriesList}.
     */
    public static class Builder {
        private String categoryId;
        private String name;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  categoryId  String value for categoryId.
         * @param  name  String value for name.
         */
        public Builder(String categoryId, String name) {
            this.categoryId = categoryId;
            this.name = name;
        }

        /**
         * Setter for categoryId.
         * @param  categoryId  String value for categoryId.
         * @return Builder
         */
        public Builder categoryId(String categoryId) {
            this.categoryId = categoryId;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link CategoriesList} object using the set fields.
         * @return {@link CategoriesList}
         */
        public CategoriesList build() {
            CategoriesList model =
                    new CategoriesList(categoryId, name);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
