/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for CoinsIdHistory type.
 */
public class CoinsIdHistory {
    private String id;
    private String symbol;
    private String name;
    private Map<String, String> localization;
    private Image image;
    private MarketData marketData;
    private CommunityData communityData;
    private DeveloperData developerData;
    private PublicInterestStats publicInterestStats;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public CoinsIdHistory() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  symbol  String value for symbol.
     * @param  name  String value for name.
     * @param  image  Image value for image.
     * @param  marketData  MarketData value for marketData.
     * @param  communityData  CommunityData value for communityData.
     * @param  developerData  DeveloperData value for developerData.
     * @param  publicInterestStats  PublicInterestStats value for publicInterestStats.
     * @param  localization  Map of String, value for localization.
     */
    public CoinsIdHistory(
            String id,
            String symbol,
            String name,
            Image image,
            MarketData marketData,
            CommunityData communityData,
            DeveloperData developerData,
            PublicInterestStats publicInterestStats,
            Map<String, String> localization) {
        this.id = id;
        this.symbol = symbol;
        this.name = name;
        this.localization = localization;
        this.image = image;
        this.marketData = marketData;
        this.communityData = communityData;
        this.developerData = developerData;
        this.publicInterestStats = publicInterestStats;
    }

    /**
     * Getter for Id.
     * Coin ID
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Coin ID
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for Symbol.
     * Coin symbol
     * @return Returns the String
     */
    @JsonGetter("symbol")
    public String getSymbol() {
        return symbol;
    }

    /**
     * Setter for Symbol.
     * Coin symbol
     * @param symbol Value for String
     */
    @JsonSetter("symbol")
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    /**
     * Getter for Name.
     * Coin name
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * Coin name
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for Localization.
     * Localized coin names keyed by locale code
     * @return Returns the Map of String, String
     */
    @JsonGetter("localization")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, String> getLocalization() {
        return localization;
    }

    /**
     * Setter for Localization.
     * Localized coin names keyed by locale code
     * @param localization Value for Map of String, String
     */
    @JsonSetter("localization")
    public void setLocalization(Map<String, String> localization) {
        this.localization = localization;
    }

    /**
     * Getter for Image.
     * Coin image URLs
     * @return Returns the Image
     */
    @JsonGetter("image")
    public Image getImage() {
        return image;
    }

    /**
     * Setter for Image.
     * Coin image URLs
     * @param image Value for Image
     */
    @JsonSetter("image")
    public void setImage(Image image) {
        this.image = image;
    }

    /**
     * Getter for MarketData.
     * Market data at the given date
     * @return Returns the MarketData
     */
    @JsonGetter("market_data")
    public MarketData getMarketData() {
        return marketData;
    }

    /**
     * Setter for MarketData.
     * Market data at the given date
     * @param marketData Value for MarketData
     */
    @JsonSetter("market_data")
    public void setMarketData(MarketData marketData) {
        this.marketData = marketData;
    }

    /**
     * Getter for CommunityData.
     * Community engagement data
     * @return Returns the CommunityData
     */
    @JsonGetter("community_data")
    public CommunityData getCommunityData() {
        return communityData;
    }

    /**
     * Setter for CommunityData.
     * Community engagement data
     * @param communityData Value for CommunityData
     */
    @JsonSetter("community_data")
    public void setCommunityData(CommunityData communityData) {
        this.communityData = communityData;
    }

    /**
     * Getter for DeveloperData.
     * Developer activity data
     * @return Returns the DeveloperData
     */
    @JsonGetter("developer_data")
    public DeveloperData getDeveloperData() {
        return developerData;
    }

    /**
     * Setter for DeveloperData.
     * Developer activity data
     * @param developerData Value for DeveloperData
     */
    @JsonSetter("developer_data")
    public void setDeveloperData(DeveloperData developerData) {
        this.developerData = developerData;
    }

    /**
     * Getter for PublicInterestStats.
     * Public interest statistics
     * @return Returns the PublicInterestStats
     */
    @JsonGetter("public_interest_stats")
    public PublicInterestStats getPublicInterestStats() {
        return publicInterestStats;
    }

    /**
     * Setter for PublicInterestStats.
     * Public interest statistics
     * @param publicInterestStats Value for PublicInterestStats
     */
    @JsonSetter("public_interest_stats")
    public void setPublicInterestStats(PublicInterestStats publicInterestStats) {
        this.publicInterestStats = publicInterestStats;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this CoinsIdHistory into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CoinsIdHistory [" + "id=" + id + ", symbol=" + symbol + ", name=" + name
                + ", image=" + image + ", marketData=" + marketData + ", communityData="
                + communityData + ", developerData=" + developerData + ", publicInterestStats="
                + publicInterestStats + ", localization=" + localization + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link CoinsIdHistory.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CoinsIdHistory.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, symbol, name, image, marketData, communityData,
                developerData, publicInterestStats)
                .localization(getLocalization());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link CoinsIdHistory}.
     */
    public static class Builder {
        private String id;
        private String symbol;
        private String name;
        private Image image;
        private MarketData marketData;
        private CommunityData communityData;
        private DeveloperData developerData;
        private PublicInterestStats publicInterestStats;
        private Map<String, String> localization;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  symbol  String value for symbol.
         * @param  name  String value for name.
         * @param  image  Image value for image.
         * @param  marketData  MarketData value for marketData.
         * @param  communityData  CommunityData value for communityData.
         * @param  developerData  DeveloperData value for developerData.
         * @param  publicInterestStats  PublicInterestStats value for publicInterestStats.
         */
        public Builder(String id, String symbol, String name, Image image, MarketData marketData,
                CommunityData communityData, DeveloperData developerData,
                PublicInterestStats publicInterestStats) {
            this.id = id;
            this.symbol = symbol;
            this.name = name;
            this.image = image;
            this.marketData = marketData;
            this.communityData = communityData;
            this.developerData = developerData;
            this.publicInterestStats = publicInterestStats;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for symbol.
         * @param  symbol  String value for symbol.
         * @return Builder
         */
        public Builder symbol(String symbol) {
            this.symbol = symbol;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for image.
         * @param  image  Image value for image.
         * @return Builder
         */
        public Builder image(Image image) {
            this.image = image;
            return this;
        }

        /**
         * Setter for marketData.
         * @param  marketData  MarketData value for marketData.
         * @return Builder
         */
        public Builder marketData(MarketData marketData) {
            this.marketData = marketData;
            return this;
        }

        /**
         * Setter for communityData.
         * @param  communityData  CommunityData value for communityData.
         * @return Builder
         */
        public Builder communityData(CommunityData communityData) {
            this.communityData = communityData;
            return this;
        }

        /**
         * Setter for developerData.
         * @param  developerData  DeveloperData value for developerData.
         * @return Builder
         */
        public Builder developerData(DeveloperData developerData) {
            this.developerData = developerData;
            return this;
        }

        /**
         * Setter for publicInterestStats.
         * @param  publicInterestStats  PublicInterestStats value for publicInterestStats.
         * @return Builder
         */
        public Builder publicInterestStats(PublicInterestStats publicInterestStats) {
            this.publicInterestStats = publicInterestStats;
            return this;
        }

        /**
         * Setter for localization.
         * @param  localization  Map of String, value for localization.
         * @return Builder
         */
        public Builder localization(Map<String, String> localization) {
            this.localization = localization;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link CoinsIdHistory} object using the set fields.
         * @return {@link CoinsIdHistory}
         */
        public CoinsIdHistory build() {
            CoinsIdHistory model =
                    new CoinsIdHistory(id, symbol, name, image, marketData, communityData,
                            developerData, publicInterestStats, localization);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
