/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for CoinsMarketChart type.
 */
public class CoinsMarketChart {
    private List<List<Double>> prices;
    private List<List<Double>> marketCaps;
    private List<List<Double>> totalVolumes;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public CoinsMarketChart() {
    }

    /**
     * Initialization constructor.
     * @param  prices  List of Double value for prices.
     * @param  marketCaps  List of Double value for marketCaps.
     * @param  totalVolumes  List of Double value for totalVolumes.
     */
    public CoinsMarketChart(
            List<List<Double>> prices,
            List<List<Double>> marketCaps,
            List<List<Double>> totalVolumes) {
        this.prices = prices;
        this.marketCaps = marketCaps;
        this.totalVolumes = totalVolumes;
    }

    /**
     * Getter for Prices.
     * Price data points as [timestamp, price] pairs
     * @return Returns the List of Double
     */
    @JsonGetter("prices")
    public List<List<Double>> getPrices() {
        return prices;
    }

    /**
     * Setter for Prices.
     * Price data points as [timestamp, price] pairs
     * @param prices Value for List of Double
     */
    @JsonSetter("prices")
    public void setPrices(List<List<Double>> prices) {
        this.prices = prices;
    }

    /**
     * Getter for MarketCaps.
     * Market cap data points as [timestamp, market_cap] pairs
     * @return Returns the List of Double
     */
    @JsonGetter("market_caps")
    public List<List<Double>> getMarketCaps() {
        return marketCaps;
    }

    /**
     * Setter for MarketCaps.
     * Market cap data points as [timestamp, market_cap] pairs
     * @param marketCaps Value for List of Double
     */
    @JsonSetter("market_caps")
    public void setMarketCaps(List<List<Double>> marketCaps) {
        this.marketCaps = marketCaps;
    }

    /**
     * Getter for TotalVolumes.
     * Total volume data points as [timestamp, volume] pairs
     * @return Returns the List of Double
     */
    @JsonGetter("total_volumes")
    public List<List<Double>> getTotalVolumes() {
        return totalVolumes;
    }

    /**
     * Setter for TotalVolumes.
     * Total volume data points as [timestamp, volume] pairs
     * @param totalVolumes Value for List of Double
     */
    @JsonSetter("total_volumes")
    public void setTotalVolumes(List<List<Double>> totalVolumes) {
        this.totalVolumes = totalVolumes;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this CoinsMarketChart into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CoinsMarketChart [" + "prices=" + prices + ", marketCaps=" + marketCaps
                + ", totalVolumes=" + totalVolumes + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link CoinsMarketChart.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CoinsMarketChart.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(prices, marketCaps, totalVolumes);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link CoinsMarketChart}.
     */
    public static class Builder {
        private List<List<Double>> prices;
        private List<List<Double>> marketCaps;
        private List<List<Double>> totalVolumes;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  prices  List of Double value for prices.
         * @param  marketCaps  List of Double value for marketCaps.
         * @param  totalVolumes  List of Double value for totalVolumes.
         */
        public Builder(List<List<Double>> prices, List<List<Double>> marketCaps,
                List<List<Double>> totalVolumes) {
            this.prices = prices;
            this.marketCaps = marketCaps;
            this.totalVolumes = totalVolumes;
        }

        /**
         * Setter for prices.
         * @param  prices  List of Double value for prices.
         * @return Builder
         */
        public Builder prices(List<List<Double>> prices) {
            this.prices = prices;
            return this;
        }

        /**
         * Setter for marketCaps.
         * @param  marketCaps  List of Double value for marketCaps.
         * @return Builder
         */
        public Builder marketCaps(List<List<Double>> marketCaps) {
            this.marketCaps = marketCaps;
            return this;
        }

        /**
         * Setter for totalVolumes.
         * @param  totalVolumes  List of Double value for totalVolumes.
         * @return Builder
         */
        public Builder totalVolumes(List<List<Double>> totalVolumes) {
            this.totalVolumes = totalVolumes;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link CoinsMarketChart} object using the set fields.
         * @return {@link CoinsMarketChart}
         */
        public CoinsMarketChart build() {
            CoinsMarketChart model =
                    new CoinsMarketChart(prices, marketCaps, totalVolumes);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
