/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for ConvertedLast1 type.
 */
public class ConvertedLast1 {
    private Double btc;
    private Double eth;
    private Double usd;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ConvertedLast1() {
    }

    /**
     * Initialization constructor.
     * @param  btc  Double value for btc.
     * @param  eth  Double value for eth.
     * @param  usd  Double value for usd.
     */
    public ConvertedLast1(
            Double btc,
            Double eth,
            Double usd) {
        this.btc = btc;
        this.eth = eth;
        this.usd = usd;
    }

    /**
     * Getter for Btc.
     * @return Returns the Double
     */
    @JsonGetter("btc")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getBtc() {
        return btc;
    }

    /**
     * Setter for Btc.
     * @param btc Value for Double
     */
    @JsonSetter("btc")
    public void setBtc(Double btc) {
        this.btc = btc;
    }

    /**
     * Getter for Eth.
     * @return Returns the Double
     */
    @JsonGetter("eth")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getEth() {
        return eth;
    }

    /**
     * Setter for Eth.
     * @param eth Value for Double
     */
    @JsonSetter("eth")
    public void setEth(Double eth) {
        this.eth = eth;
    }

    /**
     * Getter for Usd.
     * @return Returns the Double
     */
    @JsonGetter("usd")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getUsd() {
        return usd;
    }

    /**
     * Setter for Usd.
     * @param usd Value for Double
     */
    @JsonSetter("usd")
    public void setUsd(Double usd) {
        this.usd = usd;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ConvertedLast1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ConvertedLast1 [" + "btc=" + btc + ", eth=" + eth + ", usd=" + usd
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ConvertedLast1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ConvertedLast1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .btc(getBtc())
                .eth(getEth())
                .usd(getUsd());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ConvertedLast1}.
     */
    public static class Builder {
        private Double btc;
        private Double eth;
        private Double usd;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for btc.
         * @param  btc  Double value for btc.
         * @return Builder
         */
        public Builder btc(Double btc) {
            this.btc = btc;
            return this;
        }

        /**
         * Setter for eth.
         * @param  eth  Double value for eth.
         * @return Builder
         */
        public Builder eth(Double eth) {
            this.eth = eth;
            return this;
        }

        /**
         * Setter for usd.
         * @param  usd  Double value for usd.
         * @return Builder
         */
        public Builder usd(Double usd) {
            this.usd = usd;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ConvertedLast1} object using the set fields.
         * @return {@link ConvertedLast1}
         */
        public ConvertedLast1 build() {
            ConvertedLast1 model =
                    new ConvertedLast1(btc, eth, usd);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
