/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Data1 type.
 */
public class Data1 {
    private String defiMarketCap;
    private String ethMarketCap;
    private String defiToEthRatio;
    private String tradingVolume24H;
    private String defiDominance;
    private String topCoinName;
    private double topCoinDefiDominance;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Data1() {
    }

    /**
     * Initialization constructor.
     * @param  defiMarketCap  String value for defiMarketCap.
     * @param  ethMarketCap  String value for ethMarketCap.
     * @param  defiToEthRatio  String value for defiToEthRatio.
     * @param  tradingVolume24H  String value for tradingVolume24H.
     * @param  defiDominance  String value for defiDominance.
     * @param  topCoinName  String value for topCoinName.
     * @param  topCoinDefiDominance  double value for topCoinDefiDominance.
     */
    public Data1(
            String defiMarketCap,
            String ethMarketCap,
            String defiToEthRatio,
            String tradingVolume24H,
            String defiDominance,
            String topCoinName,
            double topCoinDefiDominance) {
        this.defiMarketCap = defiMarketCap;
        this.ethMarketCap = ethMarketCap;
        this.defiToEthRatio = defiToEthRatio;
        this.tradingVolume24H = tradingVolume24H;
        this.defiDominance = defiDominance;
        this.topCoinName = topCoinName;
        this.topCoinDefiDominance = topCoinDefiDominance;
    }

    /**
     * Getter for DefiMarketCap.
     * DeFi market cap
     * @return Returns the String
     */
    @JsonGetter("defi_market_cap")
    public String getDefiMarketCap() {
        return defiMarketCap;
    }

    /**
     * Setter for DefiMarketCap.
     * DeFi market cap
     * @param defiMarketCap Value for String
     */
    @JsonSetter("defi_market_cap")
    public void setDefiMarketCap(String defiMarketCap) {
        this.defiMarketCap = defiMarketCap;
    }

    /**
     * Getter for EthMarketCap.
     * ETH market cap
     * @return Returns the String
     */
    @JsonGetter("eth_market_cap")
    public String getEthMarketCap() {
        return ethMarketCap;
    }

    /**
     * Setter for EthMarketCap.
     * ETH market cap
     * @param ethMarketCap Value for String
     */
    @JsonSetter("eth_market_cap")
    public void setEthMarketCap(String ethMarketCap) {
        this.ethMarketCap = ethMarketCap;
    }

    /**
     * Getter for DefiToEthRatio.
     * DeFi to ETH ratio
     * @return Returns the String
     */
    @JsonGetter("defi_to_eth_ratio")
    public String getDefiToEthRatio() {
        return defiToEthRatio;
    }

    /**
     * Setter for DefiToEthRatio.
     * DeFi to ETH ratio
     * @param defiToEthRatio Value for String
     */
    @JsonSetter("defi_to_eth_ratio")
    public void setDefiToEthRatio(String defiToEthRatio) {
        this.defiToEthRatio = defiToEthRatio;
    }

    /**
     * Getter for TradingVolume24H.
     * DeFi trading volume in 24 hours
     * @return Returns the String
     */
    @JsonGetter("trading_volume_24h")
    public String getTradingVolume24H() {
        return tradingVolume24H;
    }

    /**
     * Setter for TradingVolume24H.
     * DeFi trading volume in 24 hours
     * @param tradingVolume24H Value for String
     */
    @JsonSetter("trading_volume_24h")
    public void setTradingVolume24H(String tradingVolume24H) {
        this.tradingVolume24H = tradingVolume24H;
    }

    /**
     * Getter for DefiDominance.
     * DeFi dominance percentage
     * @return Returns the String
     */
    @JsonGetter("defi_dominance")
    public String getDefiDominance() {
        return defiDominance;
    }

    /**
     * Setter for DefiDominance.
     * DeFi dominance percentage
     * @param defiDominance Value for String
     */
    @JsonSetter("defi_dominance")
    public void setDefiDominance(String defiDominance) {
        this.defiDominance = defiDominance;
    }

    /**
     * Getter for TopCoinName.
     * DeFi top coin name
     * @return Returns the String
     */
    @JsonGetter("top_coin_name")
    public String getTopCoinName() {
        return topCoinName;
    }

    /**
     * Setter for TopCoinName.
     * DeFi top coin name
     * @param topCoinName Value for String
     */
    @JsonSetter("top_coin_name")
    public void setTopCoinName(String topCoinName) {
        this.topCoinName = topCoinName;
    }

    /**
     * Getter for TopCoinDefiDominance.
     * DeFi top coin dominance percentage
     * @return Returns the double
     */
    @JsonGetter("top_coin_defi_dominance")
    public double getTopCoinDefiDominance() {
        return topCoinDefiDominance;
    }

    /**
     * Setter for TopCoinDefiDominance.
     * DeFi top coin dominance percentage
     * @param topCoinDefiDominance Value for double
     */
    @JsonSetter("top_coin_defi_dominance")
    public void setTopCoinDefiDominance(double topCoinDefiDominance) {
        this.topCoinDefiDominance = topCoinDefiDominance;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Data1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Data1 [" + "defiMarketCap=" + defiMarketCap + ", ethMarketCap=" + ethMarketCap
                + ", defiToEthRatio=" + defiToEthRatio + ", tradingVolume24H=" + tradingVolume24H
                + ", defiDominance=" + defiDominance + ", topCoinName=" + topCoinName
                + ", topCoinDefiDominance=" + topCoinDefiDominance + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Data1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Data1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(defiMarketCap, ethMarketCap, defiToEthRatio, tradingVolume24H,
                defiDominance, topCoinName, topCoinDefiDominance);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Data1}.
     */
    public static class Builder {
        private String defiMarketCap;
        private String ethMarketCap;
        private String defiToEthRatio;
        private String tradingVolume24H;
        private String defiDominance;
        private String topCoinName;
        private double topCoinDefiDominance;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  defiMarketCap  String value for defiMarketCap.
         * @param  ethMarketCap  String value for ethMarketCap.
         * @param  defiToEthRatio  String value for defiToEthRatio.
         * @param  tradingVolume24H  String value for tradingVolume24H.
         * @param  defiDominance  String value for defiDominance.
         * @param  topCoinName  String value for topCoinName.
         * @param  topCoinDefiDominance  double value for topCoinDefiDominance.
         */
        public Builder(String defiMarketCap, String ethMarketCap, String defiToEthRatio,
                String tradingVolume24H, String defiDominance, String topCoinName,
                double topCoinDefiDominance) {
            this.defiMarketCap = defiMarketCap;
            this.ethMarketCap = ethMarketCap;
            this.defiToEthRatio = defiToEthRatio;
            this.tradingVolume24H = tradingVolume24H;
            this.defiDominance = defiDominance;
            this.topCoinName = topCoinName;
            this.topCoinDefiDominance = topCoinDefiDominance;
        }

        /**
         * Setter for defiMarketCap.
         * @param  defiMarketCap  String value for defiMarketCap.
         * @return Builder
         */
        public Builder defiMarketCap(String defiMarketCap) {
            this.defiMarketCap = defiMarketCap;
            return this;
        }

        /**
         * Setter for ethMarketCap.
         * @param  ethMarketCap  String value for ethMarketCap.
         * @return Builder
         */
        public Builder ethMarketCap(String ethMarketCap) {
            this.ethMarketCap = ethMarketCap;
            return this;
        }

        /**
         * Setter for defiToEthRatio.
         * @param  defiToEthRatio  String value for defiToEthRatio.
         * @return Builder
         */
        public Builder defiToEthRatio(String defiToEthRatio) {
            this.defiToEthRatio = defiToEthRatio;
            return this;
        }

        /**
         * Setter for tradingVolume24H.
         * @param  tradingVolume24H  String value for tradingVolume24H.
         * @return Builder
         */
        public Builder tradingVolume24H(String tradingVolume24H) {
            this.tradingVolume24H = tradingVolume24H;
            return this;
        }

        /**
         * Setter for defiDominance.
         * @param  defiDominance  String value for defiDominance.
         * @return Builder
         */
        public Builder defiDominance(String defiDominance) {
            this.defiDominance = defiDominance;
            return this;
        }

        /**
         * Setter for topCoinName.
         * @param  topCoinName  String value for topCoinName.
         * @return Builder
         */
        public Builder topCoinName(String topCoinName) {
            this.topCoinName = topCoinName;
            return this;
        }

        /**
         * Setter for topCoinDefiDominance.
         * @param  topCoinDefiDominance  double value for topCoinDefiDominance.
         * @return Builder
         */
        public Builder topCoinDefiDominance(double topCoinDefiDominance) {
            this.topCoinDefiDominance = topCoinDefiDominance;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Data1} object using the set fields.
         * @return {@link Data1}
         */
        public Data1 build() {
            Data1 model =
                    new Data1(defiMarketCap, ethMarketCap, defiToEthRatio, tradingVolume24H,
                            defiDominance, topCoinName, topCoinDefiDominance);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
