/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Data31 type.
 */
public class Data31 {
    private String id;
    private String type;
    private Attributes16 attributes;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Data31() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  type  String value for type.
     * @param  attributes  Attributes16 value for attributes.
     */
    public Data31(
            String id,
            String type,
            Attributes16 attributes) {
        this.id = id;
        this.type = type;
        this.attributes = attributes;
    }

    /**
     * Getter for Id.
     * Request ID
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Request ID
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for Type.
     * Response type
     * @return Returns the String
     */
    @JsonGetter("type")
    public String getType() {
        return type;
    }

    /**
     * Setter for Type.
     * Response type
     * @param type Value for String
     */
    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for Attributes.
     * @return Returns the Attributes16
     */
    @JsonGetter("attributes")
    public Attributes16 getAttributes() {
        return attributes;
    }

    /**
     * Setter for Attributes.
     * @param attributes Value for Attributes16
     */
    @JsonSetter("attributes")
    public void setAttributes(Attributes16 attributes) {
        this.attributes = attributes;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Data31 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Data31 [" + "id=" + id + ", type=" + type + ", attributes=" + attributes
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Data31.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Data31.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, type, attributes);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Data31}.
     */
    public static class Builder {
        private String id;
        private String type;
        private Attributes16 attributes;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  type  String value for type.
         * @param  attributes  Attributes16 value for attributes.
         */
        public Builder(String id, String type, Attributes16 attributes) {
            this.id = id;
            this.type = type;
            this.attributes = attributes;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for type.
         * @param  type  String value for type.
         * @return Builder
         */
        public Builder type(String type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for attributes.
         * @param  attributes  Attributes16 value for attributes.
         * @return Builder
         */
        public Builder attributes(Attributes16 attributes) {
            this.attributes = attributes;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Data31} object using the set fields.
         * @return {@link Data31}
         */
        public Data31 build() {
            Data31 model =
                    new Data31(id, type, attributes);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
