/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for DerivativesTicker type.
 */
public class DerivativesTicker {
    private String market;
    private String symbol;
    private String indexId;
    private String price;
    private double pricePercentageChange24H;
    private String contractType;
    private double index;
    private double basis;
    private double spread;
    private double fundingRate;
    private double openInterest;
    private double volume24H;
    private double lastTradedAt;
    private Double expiredAt;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public DerivativesTicker() {
    }

    /**
     * Initialization constructor.
     * @param  market  String value for market.
     * @param  symbol  String value for symbol.
     * @param  indexId  String value for indexId.
     * @param  price  String value for price.
     * @param  pricePercentageChange24H  double value for pricePercentageChange24H.
     * @param  contractType  String value for contractType.
     * @param  index  double value for index.
     * @param  basis  double value for basis.
     * @param  spread  double value for spread.
     * @param  fundingRate  double value for fundingRate.
     * @param  openInterest  double value for openInterest.
     * @param  volume24H  double value for volume24H.
     * @param  lastTradedAt  double value for lastTradedAt.
     * @param  expiredAt  Double value for expiredAt.
     */
    public DerivativesTicker(
            String market,
            String symbol,
            String indexId,
            String price,
            double pricePercentageChange24H,
            String contractType,
            double index,
            double basis,
            double spread,
            double fundingRate,
            double openInterest,
            double volume24H,
            double lastTradedAt,
            Double expiredAt) {
        this.market = market;
        this.symbol = symbol;
        this.indexId = indexId;
        this.price = price;
        this.pricePercentageChange24H = pricePercentageChange24H;
        this.contractType = contractType;
        this.index = index;
        this.basis = basis;
        this.spread = spread;
        this.fundingRate = fundingRate;
        this.openInterest = openInterest;
        this.volume24H = volume24H;
        this.lastTradedAt = lastTradedAt;
        this.expiredAt = expiredAt;
    }

    /**
     * Getter for Market.
     * Derivative market name
     * @return Returns the String
     */
    @JsonGetter("market")
    public String getMarket() {
        return market;
    }

    /**
     * Setter for Market.
     * Derivative market name
     * @param market Value for String
     */
    @JsonSetter("market")
    public void setMarket(String market) {
        this.market = market;
    }

    /**
     * Getter for Symbol.
     * Derivative ticker symbol
     * @return Returns the String
     */
    @JsonGetter("symbol")
    public String getSymbol() {
        return symbol;
    }

    /**
     * Setter for Symbol.
     * Derivative ticker symbol
     * @param symbol Value for String
     */
    @JsonSetter("symbol")
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    /**
     * Getter for IndexId.
     * Derivative underlying asset
     * @return Returns the String
     */
    @JsonGetter("index_id")
    public String getIndexId() {
        return indexId;
    }

    /**
     * Setter for IndexId.
     * Derivative underlying asset
     * @param indexId Value for String
     */
    @JsonSetter("index_id")
    public void setIndexId(String indexId) {
        this.indexId = indexId;
    }

    /**
     * Getter for Price.
     * Derivative ticker price
     * @return Returns the String
     */
    @JsonGetter("price")
    public String getPrice() {
        return price;
    }

    /**
     * Setter for Price.
     * Derivative ticker price
     * @param price Value for String
     */
    @JsonSetter("price")
    public void setPrice(String price) {
        this.price = price;
    }

    /**
     * Getter for PricePercentageChange24H.
     * Derivative ticker price percentage change in 24 hours
     * @return Returns the double
     */
    @JsonGetter("price_percentage_change_24h")
    public double getPricePercentageChange24H() {
        return pricePercentageChange24H;
    }

    /**
     * Setter for PricePercentageChange24H.
     * Derivative ticker price percentage change in 24 hours
     * @param pricePercentageChange24H Value for double
     */
    @JsonSetter("price_percentage_change_24h")
    public void setPricePercentageChange24H(double pricePercentageChange24H) {
        this.pricePercentageChange24H = pricePercentageChange24H;
    }

    /**
     * Getter for ContractType.
     * Derivative contract type
     * @return Returns the String
     */
    @JsonGetter("contract_type")
    public String getContractType() {
        return contractType;
    }

    /**
     * Setter for ContractType.
     * Derivative contract type
     * @param contractType Value for String
     */
    @JsonSetter("contract_type")
    public void setContractType(String contractType) {
        this.contractType = contractType;
    }

    /**
     * Getter for Index.
     * Derivative underlying asset price
     * @return Returns the double
     */
    @JsonGetter("index")
    public double getIndex() {
        return index;
    }

    /**
     * Setter for Index.
     * Derivative underlying asset price
     * @param index Value for double
     */
    @JsonSetter("index")
    public void setIndex(double index) {
        this.index = index;
    }

    /**
     * Getter for Basis.
     * Difference of derivative price and index price
     * @return Returns the double
     */
    @JsonGetter("basis")
    public double getBasis() {
        return basis;
    }

    /**
     * Setter for Basis.
     * Difference of derivative price and index price
     * @param basis Value for double
     */
    @JsonSetter("basis")
    public void setBasis(double basis) {
        this.basis = basis;
    }

    /**
     * Getter for Spread.
     * Derivative bid-ask spread
     * @return Returns the double
     */
    @JsonGetter("spread")
    public double getSpread() {
        return spread;
    }

    /**
     * Setter for Spread.
     * Derivative bid-ask spread
     * @param spread Value for double
     */
    @JsonSetter("spread")
    public void setSpread(double spread) {
        this.spread = spread;
    }

    /**
     * Getter for FundingRate.
     * Derivative funding rate
     * @return Returns the double
     */
    @JsonGetter("funding_rate")
    public double getFundingRate() {
        return fundingRate;
    }

    /**
     * Setter for FundingRate.
     * Derivative funding rate
     * @param fundingRate Value for double
     */
    @JsonSetter("funding_rate")
    public void setFundingRate(double fundingRate) {
        this.fundingRate = fundingRate;
    }

    /**
     * Getter for OpenInterest.
     * Derivative open interest
     * @return Returns the double
     */
    @JsonGetter("open_interest")
    public double getOpenInterest() {
        return openInterest;
    }

    /**
     * Setter for OpenInterest.
     * Derivative open interest
     * @param openInterest Value for double
     */
    @JsonSetter("open_interest")
    public void setOpenInterest(double openInterest) {
        this.openInterest = openInterest;
    }

    /**
     * Getter for Volume24H.
     * Derivative trading volume in 24 hours
     * @return Returns the double
     */
    @JsonGetter("volume_24h")
    public double getVolume24H() {
        return volume24H;
    }

    /**
     * Setter for Volume24H.
     * Derivative trading volume in 24 hours
     * @param volume24H Value for double
     */
    @JsonSetter("volume_24h")
    public void setVolume24H(double volume24H) {
        this.volume24H = volume24H;
    }

    /**
     * Getter for LastTradedAt.
     * Derivative last traded time in UNIX timestamp
     * @return Returns the double
     */
    @JsonGetter("last_traded_at")
    public double getLastTradedAt() {
        return lastTradedAt;
    }

    /**
     * Setter for LastTradedAt.
     * Derivative last traded time in UNIX timestamp
     * @param lastTradedAt Value for double
     */
    @JsonSetter("last_traded_at")
    public void setLastTradedAt(double lastTradedAt) {
        this.lastTradedAt = lastTradedAt;
    }

    /**
     * Getter for ExpiredAt.
     * Derivative expiry time in UNIX timestamp
     * @return Returns the Double
     */
    @JsonGetter("expired_at")
    public Double getExpiredAt() {
        return expiredAt;
    }

    /**
     * Setter for ExpiredAt.
     * Derivative expiry time in UNIX timestamp
     * @param expiredAt Value for Double
     */
    @JsonSetter("expired_at")
    public void setExpiredAt(Double expiredAt) {
        this.expiredAt = expiredAt;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this DerivativesTicker into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DerivativesTicker [" + "market=" + market + ", symbol=" + symbol + ", indexId="
                + indexId + ", price=" + price + ", pricePercentageChange24H="
                + pricePercentageChange24H + ", contractType=" + contractType + ", index=" + index
                + ", basis=" + basis + ", spread=" + spread + ", fundingRate=" + fundingRate
                + ", openInterest=" + openInterest + ", volume24H=" + volume24H + ", lastTradedAt="
                + lastTradedAt + ", expiredAt=" + expiredAt + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link DerivativesTicker.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DerivativesTicker.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(market, symbol, indexId, price, pricePercentageChange24H,
                contractType, index, basis, spread, fundingRate, openInterest, volume24H,
                lastTradedAt, expiredAt);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link DerivativesTicker}.
     */
    public static class Builder {
        private String market;
        private String symbol;
        private String indexId;
        private String price;
        private double pricePercentageChange24H;
        private String contractType;
        private double index;
        private double basis;
        private double spread;
        private double fundingRate;
        private double openInterest;
        private double volume24H;
        private double lastTradedAt;
        private Double expiredAt;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  market  String value for market.
         * @param  symbol  String value for symbol.
         * @param  indexId  String value for indexId.
         * @param  price  String value for price.
         * @param  pricePercentageChange24H  double value for pricePercentageChange24H.
         * @param  contractType  String value for contractType.
         * @param  index  double value for index.
         * @param  basis  double value for basis.
         * @param  spread  double value for spread.
         * @param  fundingRate  double value for fundingRate.
         * @param  openInterest  double value for openInterest.
         * @param  volume24H  double value for volume24H.
         * @param  lastTradedAt  double value for lastTradedAt.
         * @param  expiredAt  Double value for expiredAt.
         */
        public Builder(String market, String symbol, String indexId, String price,
                double pricePercentageChange24H, String contractType, double index, double basis,
                double spread, double fundingRate, double openInterest, double volume24H,
                double lastTradedAt, Double expiredAt) {
            this.market = market;
            this.symbol = symbol;
            this.indexId = indexId;
            this.price = price;
            this.pricePercentageChange24H = pricePercentageChange24H;
            this.contractType = contractType;
            this.index = index;
            this.basis = basis;
            this.spread = spread;
            this.fundingRate = fundingRate;
            this.openInterest = openInterest;
            this.volume24H = volume24H;
            this.lastTradedAt = lastTradedAt;
            this.expiredAt = expiredAt;
        }

        /**
         * Setter for market.
         * @param  market  String value for market.
         * @return Builder
         */
        public Builder market(String market) {
            this.market = market;
            return this;
        }

        /**
         * Setter for symbol.
         * @param  symbol  String value for symbol.
         * @return Builder
         */
        public Builder symbol(String symbol) {
            this.symbol = symbol;
            return this;
        }

        /**
         * Setter for indexId.
         * @param  indexId  String value for indexId.
         * @return Builder
         */
        public Builder indexId(String indexId) {
            this.indexId = indexId;
            return this;
        }

        /**
         * Setter for price.
         * @param  price  String value for price.
         * @return Builder
         */
        public Builder price(String price) {
            this.price = price;
            return this;
        }

        /**
         * Setter for pricePercentageChange24H.
         * @param  pricePercentageChange24H  double value for pricePercentageChange24H.
         * @return Builder
         */
        public Builder pricePercentageChange24H(double pricePercentageChange24H) {
            this.pricePercentageChange24H = pricePercentageChange24H;
            return this;
        }

        /**
         * Setter for contractType.
         * @param  contractType  String value for contractType.
         * @return Builder
         */
        public Builder contractType(String contractType) {
            this.contractType = contractType;
            return this;
        }

        /**
         * Setter for index.
         * @param  index  double value for index.
         * @return Builder
         */
        public Builder index(double index) {
            this.index = index;
            return this;
        }

        /**
         * Setter for basis.
         * @param  basis  double value for basis.
         * @return Builder
         */
        public Builder basis(double basis) {
            this.basis = basis;
            return this;
        }

        /**
         * Setter for spread.
         * @param  spread  double value for spread.
         * @return Builder
         */
        public Builder spread(double spread) {
            this.spread = spread;
            return this;
        }

        /**
         * Setter for fundingRate.
         * @param  fundingRate  double value for fundingRate.
         * @return Builder
         */
        public Builder fundingRate(double fundingRate) {
            this.fundingRate = fundingRate;
            return this;
        }

        /**
         * Setter for openInterest.
         * @param  openInterest  double value for openInterest.
         * @return Builder
         */
        public Builder openInterest(double openInterest) {
            this.openInterest = openInterest;
            return this;
        }

        /**
         * Setter for volume24H.
         * @param  volume24H  double value for volume24H.
         * @return Builder
         */
        public Builder volume24H(double volume24H) {
            this.volume24H = volume24H;
            return this;
        }

        /**
         * Setter for lastTradedAt.
         * @param  lastTradedAt  double value for lastTradedAt.
         * @return Builder
         */
        public Builder lastTradedAt(double lastTradedAt) {
            this.lastTradedAt = lastTradedAt;
            return this;
        }

        /**
         * Setter for expiredAt.
         * @param  expiredAt  Double value for expiredAt.
         * @return Builder
         */
        public Builder expiredAt(Double expiredAt) {
            this.expiredAt = expiredAt;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link DerivativesTicker} object using the set fields.
         * @return {@link DerivativesTicker}
         */
        public DerivativesTicker build() {
            DerivativesTicker model =
                    new DerivativesTicker(market, symbol, indexId, price, pricePercentageChange24H,
                            contractType, index, basis, spread, fundingRate, openInterest,
                            volume24H, lastTradedAt, expiredAt);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
