/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.types.OptionalNullable;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for DetailPlatforms type.
 */
public class DetailPlatforms {
    private OptionalNullable<Integer> decimalPlace;
    private String contractAddress;
    private String geckoterminalUrl;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public DetailPlatforms() {
    }

    /**
     * Initialization constructor.
     * @param  decimalPlace  Integer value for decimalPlace.
     * @param  contractAddress  String value for contractAddress.
     * @param  geckoterminalUrl  String value for geckoterminalUrl.
     */
    public DetailPlatforms(
            Integer decimalPlace,
            String contractAddress,
            String geckoterminalUrl) {
        this.decimalPlace = OptionalNullable.of(decimalPlace);
        this.contractAddress = contractAddress;
        this.geckoterminalUrl = geckoterminalUrl;
    }

    /**
     * Initialization constructor.
     * @param  decimalPlace  Integer value for decimalPlace.
     * @param  contractAddress  String value for contractAddress.
     * @param  geckoterminalUrl  String value for geckoterminalUrl.
     */

    protected DetailPlatforms(OptionalNullable<Integer> decimalPlace, String contractAddress,
            String geckoterminalUrl) {
        this.decimalPlace = decimalPlace;
        this.contractAddress = contractAddress;
        this.geckoterminalUrl = geckoterminalUrl;
    }

    /**
     * Internal Getter for DecimalPlace.
     * Token decimal place
     * @return Returns the Internal Integer
     */
    @JsonGetter("decimal_place")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Integer> internalGetDecimalPlace() {
        return this.decimalPlace;
    }

    /**
     * Getter for DecimalPlace.
     * Token decimal place
     * @return Returns the Integer
     */
    public Integer getDecimalPlace() {
        return OptionalNullable.getFrom(decimalPlace);
    }

    /**
     * Setter for DecimalPlace.
     * Token decimal place
     * @param decimalPlace Value for Integer
     */
    @JsonSetter("decimal_place")
    public void setDecimalPlace(Integer decimalPlace) {
        this.decimalPlace = OptionalNullable.of(decimalPlace);
    }

    /**
     * UnSetter for DecimalPlace.
     * Token decimal place
     */
    public void unsetDecimalPlace() {
        decimalPlace = null;
    }

    /**
     * Getter for ContractAddress.
     * Token contract address
     * @return Returns the String
     */
    @JsonGetter("contract_address")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getContractAddress() {
        return contractAddress;
    }

    /**
     * Setter for ContractAddress.
     * Token contract address
     * @param contractAddress Value for String
     */
    @JsonSetter("contract_address")
    public void setContractAddress(String contractAddress) {
        this.contractAddress = contractAddress;
    }

    /**
     * Getter for GeckoterminalUrl.
     * GeckoTerminal URL
     * @return Returns the String
     */
    @JsonGetter("geckoterminal_url")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getGeckoterminalUrl() {
        return geckoterminalUrl;
    }

    /**
     * Setter for GeckoterminalUrl.
     * GeckoTerminal URL
     * @param geckoterminalUrl Value for String
     */
    @JsonSetter("geckoterminal_url")
    public void setGeckoterminalUrl(String geckoterminalUrl) {
        this.geckoterminalUrl = geckoterminalUrl;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this DetailPlatforms into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DetailPlatforms [" + "decimalPlace=" + decimalPlace + ", contractAddress="
                + contractAddress + ", geckoterminalUrl=" + geckoterminalUrl
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link DetailPlatforms.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DetailPlatforms.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .contractAddress(getContractAddress())
                .geckoterminalUrl(getGeckoterminalUrl());
        builder.decimalPlace = internalGetDecimalPlace();
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link DetailPlatforms}.
     */
    public static class Builder {
        private OptionalNullable<Integer> decimalPlace;
        private String contractAddress;
        private String geckoterminalUrl;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for decimalPlace.
         * @param  decimalPlace  Integer value for decimalPlace.
         * @return Builder
         */
        public Builder decimalPlace(Integer decimalPlace) {
            this.decimalPlace = OptionalNullable.of(decimalPlace);
            return this;
        }

        /**
         * UnSetter for decimalPlace.
         * @return Builder
         */
        public Builder unsetDecimalPlace() {
            decimalPlace = null;
            return this;
        }

        /**
         * Setter for contractAddress.
         * @param  contractAddress  String value for contractAddress.
         * @return Builder
         */
        public Builder contractAddress(String contractAddress) {
            this.contractAddress = contractAddress;
            return this;
        }

        /**
         * Setter for geckoterminalUrl.
         * @param  geckoterminalUrl  String value for geckoterminalUrl.
         * @return Builder
         */
        public Builder geckoterminalUrl(String geckoterminalUrl) {
            this.geckoterminalUrl = geckoterminalUrl;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link DetailPlatforms} object using the set fields.
         * @return {@link DetailPlatforms}
         */
        public DetailPlatforms build() {
            DetailPlatforms model =
                    new DetailPlatforms(decimalPlace, contractAddress, geckoterminalUrl);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
