/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.types.OptionalNullable;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for DeveloperData type.
 */
public class DeveloperData {
    private OptionalNullable<Double> forks;
    private OptionalNullable<Double> stars;
    private OptionalNullable<Double> subscribers;
    private OptionalNullable<Double> totalIssues;
    private OptionalNullable<Double> closedIssues;
    private OptionalNullable<Double> pullRequestsMerged;
    private OptionalNullable<Double> pullRequestContributors;
    private CodeAdditionsDeletions4Weeks codeAdditionsDeletions4Weeks;
    private OptionalNullable<Double> commitCount4Weeks;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public DeveloperData() {
    }

    /**
     * Initialization constructor.
     * @param  forks  Double value for forks.
     * @param  stars  Double value for stars.
     * @param  subscribers  Double value for subscribers.
     * @param  totalIssues  Double value for totalIssues.
     * @param  closedIssues  Double value for closedIssues.
     * @param  pullRequestsMerged  Double value for pullRequestsMerged.
     * @param  pullRequestContributors  Double value for pullRequestContributors.
     * @param  codeAdditionsDeletions4Weeks  CodeAdditionsDeletions4Weeks value for
     *         codeAdditionsDeletions4Weeks.
     * @param  commitCount4Weeks  Double value for commitCount4Weeks.
     */
    public DeveloperData(
            Double forks,
            Double stars,
            Double subscribers,
            Double totalIssues,
            Double closedIssues,
            Double pullRequestsMerged,
            Double pullRequestContributors,
            CodeAdditionsDeletions4Weeks codeAdditionsDeletions4Weeks,
            Double commitCount4Weeks) {
        this.forks = OptionalNullable.of(forks);
        this.stars = OptionalNullable.of(stars);
        this.subscribers = OptionalNullable.of(subscribers);
        this.totalIssues = OptionalNullable.of(totalIssues);
        this.closedIssues = OptionalNullable.of(closedIssues);
        this.pullRequestsMerged = OptionalNullable.of(pullRequestsMerged);
        this.pullRequestContributors = OptionalNullable.of(pullRequestContributors);
        this.codeAdditionsDeletions4Weeks = codeAdditionsDeletions4Weeks;
        this.commitCount4Weeks = OptionalNullable.of(commitCount4Weeks);
    }

    /**
     * Initialization constructor.
     * @param  forks  Double value for forks.
     * @param  stars  Double value for stars.
     * @param  subscribers  Double value for subscribers.
     * @param  totalIssues  Double value for totalIssues.
     * @param  closedIssues  Double value for closedIssues.
     * @param  pullRequestsMerged  Double value for pullRequestsMerged.
     * @param  pullRequestContributors  Double value for pullRequestContributors.
     * @param  codeAdditionsDeletions4Weeks  CodeAdditionsDeletions4Weeks value for
     *         codeAdditionsDeletions4Weeks.
     * @param  commitCount4Weeks  Double value for commitCount4Weeks.
     */

    protected DeveloperData(OptionalNullable<Double> forks, OptionalNullable<Double> stars,
            OptionalNullable<Double> subscribers, OptionalNullable<Double> totalIssues,
            OptionalNullable<Double> closedIssues, OptionalNullable<Double> pullRequestsMerged,
            OptionalNullable<Double> pullRequestContributors,
            CodeAdditionsDeletions4Weeks codeAdditionsDeletions4Weeks,
            OptionalNullable<Double> commitCount4Weeks) {
        this.forks = forks;
        this.stars = stars;
        this.subscribers = subscribers;
        this.totalIssues = totalIssues;
        this.closedIssues = closedIssues;
        this.pullRequestsMerged = pullRequestsMerged;
        this.pullRequestContributors = pullRequestContributors;
        this.codeAdditionsDeletions4Weeks = codeAdditionsDeletions4Weeks;
        this.commitCount4Weeks = commitCount4Weeks;
    }

    /**
     * Internal Getter for Forks.
     * Repository forks
     * @return Returns the Internal Double
     */
    @JsonGetter("forks")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Double> internalGetForks() {
        return this.forks;
    }

    /**
     * Getter for Forks.
     * Repository forks
     * @return Returns the Double
     */
    public Double getForks() {
        return OptionalNullable.getFrom(forks);
    }

    /**
     * Setter for Forks.
     * Repository forks
     * @param forks Value for Double
     */
    @JsonSetter("forks")
    public void setForks(Double forks) {
        this.forks = OptionalNullable.of(forks);
    }

    /**
     * UnSetter for Forks.
     * Repository forks
     */
    public void unsetForks() {
        forks = null;
    }

    /**
     * Internal Getter for Stars.
     * Repository stars
     * @return Returns the Internal Double
     */
    @JsonGetter("stars")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Double> internalGetStars() {
        return this.stars;
    }

    /**
     * Getter for Stars.
     * Repository stars
     * @return Returns the Double
     */
    public Double getStars() {
        return OptionalNullable.getFrom(stars);
    }

    /**
     * Setter for Stars.
     * Repository stars
     * @param stars Value for Double
     */
    @JsonSetter("stars")
    public void setStars(Double stars) {
        this.stars = OptionalNullable.of(stars);
    }

    /**
     * UnSetter for Stars.
     * Repository stars
     */
    public void unsetStars() {
        stars = null;
    }

    /**
     * Internal Getter for Subscribers.
     * Repository subscribers
     * @return Returns the Internal Double
     */
    @JsonGetter("subscribers")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Double> internalGetSubscribers() {
        return this.subscribers;
    }

    /**
     * Getter for Subscribers.
     * Repository subscribers
     * @return Returns the Double
     */
    public Double getSubscribers() {
        return OptionalNullable.getFrom(subscribers);
    }

    /**
     * Setter for Subscribers.
     * Repository subscribers
     * @param subscribers Value for Double
     */
    @JsonSetter("subscribers")
    public void setSubscribers(Double subscribers) {
        this.subscribers = OptionalNullable.of(subscribers);
    }

    /**
     * UnSetter for Subscribers.
     * Repository subscribers
     */
    public void unsetSubscribers() {
        subscribers = null;
    }

    /**
     * Internal Getter for TotalIssues.
     * Total issues
     * @return Returns the Internal Double
     */
    @JsonGetter("total_issues")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Double> internalGetTotalIssues() {
        return this.totalIssues;
    }

    /**
     * Getter for TotalIssues.
     * Total issues
     * @return Returns the Double
     */
    public Double getTotalIssues() {
        return OptionalNullable.getFrom(totalIssues);
    }

    /**
     * Setter for TotalIssues.
     * Total issues
     * @param totalIssues Value for Double
     */
    @JsonSetter("total_issues")
    public void setTotalIssues(Double totalIssues) {
        this.totalIssues = OptionalNullable.of(totalIssues);
    }

    /**
     * UnSetter for TotalIssues.
     * Total issues
     */
    public void unsetTotalIssues() {
        totalIssues = null;
    }

    /**
     * Internal Getter for ClosedIssues.
     * Closed issues
     * @return Returns the Internal Double
     */
    @JsonGetter("closed_issues")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Double> internalGetClosedIssues() {
        return this.closedIssues;
    }

    /**
     * Getter for ClosedIssues.
     * Closed issues
     * @return Returns the Double
     */
    public Double getClosedIssues() {
        return OptionalNullable.getFrom(closedIssues);
    }

    /**
     * Setter for ClosedIssues.
     * Closed issues
     * @param closedIssues Value for Double
     */
    @JsonSetter("closed_issues")
    public void setClosedIssues(Double closedIssues) {
        this.closedIssues = OptionalNullable.of(closedIssues);
    }

    /**
     * UnSetter for ClosedIssues.
     * Closed issues
     */
    public void unsetClosedIssues() {
        closedIssues = null;
    }

    /**
     * Internal Getter for PullRequestsMerged.
     * Pull requests merged
     * @return Returns the Internal Double
     */
    @JsonGetter("pull_requests_merged")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Double> internalGetPullRequestsMerged() {
        return this.pullRequestsMerged;
    }

    /**
     * Getter for PullRequestsMerged.
     * Pull requests merged
     * @return Returns the Double
     */
    public Double getPullRequestsMerged() {
        return OptionalNullable.getFrom(pullRequestsMerged);
    }

    /**
     * Setter for PullRequestsMerged.
     * Pull requests merged
     * @param pullRequestsMerged Value for Double
     */
    @JsonSetter("pull_requests_merged")
    public void setPullRequestsMerged(Double pullRequestsMerged) {
        this.pullRequestsMerged = OptionalNullable.of(pullRequestsMerged);
    }

    /**
     * UnSetter for PullRequestsMerged.
     * Pull requests merged
     */
    public void unsetPullRequestsMerged() {
        pullRequestsMerged = null;
    }

    /**
     * Internal Getter for PullRequestContributors.
     * Pull request contributors
     * @return Returns the Internal Double
     */
    @JsonGetter("pull_request_contributors")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Double> internalGetPullRequestContributors() {
        return this.pullRequestContributors;
    }

    /**
     * Getter for PullRequestContributors.
     * Pull request contributors
     * @return Returns the Double
     */
    public Double getPullRequestContributors() {
        return OptionalNullable.getFrom(pullRequestContributors);
    }

    /**
     * Setter for PullRequestContributors.
     * Pull request contributors
     * @param pullRequestContributors Value for Double
     */
    @JsonSetter("pull_request_contributors")
    public void setPullRequestContributors(Double pullRequestContributors) {
        this.pullRequestContributors = OptionalNullable.of(pullRequestContributors);
    }

    /**
     * UnSetter for PullRequestContributors.
     * Pull request contributors
     */
    public void unsetPullRequestContributors() {
        pullRequestContributors = null;
    }

    /**
     * Getter for CodeAdditionsDeletions4Weeks.
     * Code additions and deletions in the last 4 weeks
     * @return Returns the CodeAdditionsDeletions4Weeks
     */
    @JsonGetter("code_additions_deletions_4_weeks")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CodeAdditionsDeletions4Weeks getCodeAdditionsDeletions4Weeks() {
        return codeAdditionsDeletions4Weeks;
    }

    /**
     * Setter for CodeAdditionsDeletions4Weeks.
     * Code additions and deletions in the last 4 weeks
     * @param codeAdditionsDeletions4Weeks Value for CodeAdditionsDeletions4Weeks
     */
    @JsonSetter("code_additions_deletions_4_weeks")
    public void setCodeAdditionsDeletions4Weeks(CodeAdditionsDeletions4Weeks codeAdditionsDeletions4Weeks) {
        this.codeAdditionsDeletions4Weeks = codeAdditionsDeletions4Weeks;
    }

    /**
     * Internal Getter for CommitCount4Weeks.
     * Commit count in the last 4 weeks
     * @return Returns the Internal Double
     */
    @JsonGetter("commit_count_4_weeks")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Double> internalGetCommitCount4Weeks() {
        return this.commitCount4Weeks;
    }

    /**
     * Getter for CommitCount4Weeks.
     * Commit count in the last 4 weeks
     * @return Returns the Double
     */
    public Double getCommitCount4Weeks() {
        return OptionalNullable.getFrom(commitCount4Weeks);
    }

    /**
     * Setter for CommitCount4Weeks.
     * Commit count in the last 4 weeks
     * @param commitCount4Weeks Value for Double
     */
    @JsonSetter("commit_count_4_weeks")
    public void setCommitCount4Weeks(Double commitCount4Weeks) {
        this.commitCount4Weeks = OptionalNullable.of(commitCount4Weeks);
    }

    /**
     * UnSetter for CommitCount4Weeks.
     * Commit count in the last 4 weeks
     */
    public void unsetCommitCount4Weeks() {
        commitCount4Weeks = null;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this DeveloperData into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DeveloperData [" + "forks=" + forks + ", stars=" + stars + ", subscribers="
                + subscribers + ", totalIssues=" + totalIssues + ", closedIssues=" + closedIssues
                + ", pullRequestsMerged=" + pullRequestsMerged + ", pullRequestContributors="
                + pullRequestContributors + ", codeAdditionsDeletions4Weeks="
                + codeAdditionsDeletions4Weeks + ", commitCount4Weeks=" + commitCount4Weeks
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link DeveloperData.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DeveloperData.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .codeAdditionsDeletions4Weeks(getCodeAdditionsDeletions4Weeks());
        builder.forks = internalGetForks();
        builder.stars = internalGetStars();
        builder.subscribers = internalGetSubscribers();
        builder.totalIssues = internalGetTotalIssues();
        builder.closedIssues = internalGetClosedIssues();
        builder.pullRequestsMerged = internalGetPullRequestsMerged();
        builder.pullRequestContributors = internalGetPullRequestContributors();
        builder.commitCount4Weeks = internalGetCommitCount4Weeks();
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link DeveloperData}.
     */
    public static class Builder {
        private OptionalNullable<Double> forks;
        private OptionalNullable<Double> stars;
        private OptionalNullable<Double> subscribers;
        private OptionalNullable<Double> totalIssues;
        private OptionalNullable<Double> closedIssues;
        private OptionalNullable<Double> pullRequestsMerged;
        private OptionalNullable<Double> pullRequestContributors;
        private CodeAdditionsDeletions4Weeks codeAdditionsDeletions4Weeks;
        private OptionalNullable<Double> commitCount4Weeks;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for forks.
         * @param  forks  Double value for forks.
         * @return Builder
         */
        public Builder forks(Double forks) {
            this.forks = OptionalNullable.of(forks);
            return this;
        }

        /**
         * UnSetter for forks.
         * @return Builder
         */
        public Builder unsetForks() {
            forks = null;
            return this;
        }

        /**
         * Setter for stars.
         * @param  stars  Double value for stars.
         * @return Builder
         */
        public Builder stars(Double stars) {
            this.stars = OptionalNullable.of(stars);
            return this;
        }

        /**
         * UnSetter for stars.
         * @return Builder
         */
        public Builder unsetStars() {
            stars = null;
            return this;
        }

        /**
         * Setter for subscribers.
         * @param  subscribers  Double value for subscribers.
         * @return Builder
         */
        public Builder subscribers(Double subscribers) {
            this.subscribers = OptionalNullable.of(subscribers);
            return this;
        }

        /**
         * UnSetter for subscribers.
         * @return Builder
         */
        public Builder unsetSubscribers() {
            subscribers = null;
            return this;
        }

        /**
         * Setter for totalIssues.
         * @param  totalIssues  Double value for totalIssues.
         * @return Builder
         */
        public Builder totalIssues(Double totalIssues) {
            this.totalIssues = OptionalNullable.of(totalIssues);
            return this;
        }

        /**
         * UnSetter for totalIssues.
         * @return Builder
         */
        public Builder unsetTotalIssues() {
            totalIssues = null;
            return this;
        }

        /**
         * Setter for closedIssues.
         * @param  closedIssues  Double value for closedIssues.
         * @return Builder
         */
        public Builder closedIssues(Double closedIssues) {
            this.closedIssues = OptionalNullable.of(closedIssues);
            return this;
        }

        /**
         * UnSetter for closedIssues.
         * @return Builder
         */
        public Builder unsetClosedIssues() {
            closedIssues = null;
            return this;
        }

        /**
         * Setter for pullRequestsMerged.
         * @param  pullRequestsMerged  Double value for pullRequestsMerged.
         * @return Builder
         */
        public Builder pullRequestsMerged(Double pullRequestsMerged) {
            this.pullRequestsMerged = OptionalNullable.of(pullRequestsMerged);
            return this;
        }

        /**
         * UnSetter for pullRequestsMerged.
         * @return Builder
         */
        public Builder unsetPullRequestsMerged() {
            pullRequestsMerged = null;
            return this;
        }

        /**
         * Setter for pullRequestContributors.
         * @param  pullRequestContributors  Double value for pullRequestContributors.
         * @return Builder
         */
        public Builder pullRequestContributors(Double pullRequestContributors) {
            this.pullRequestContributors = OptionalNullable.of(pullRequestContributors);
            return this;
        }

        /**
         * UnSetter for pullRequestContributors.
         * @return Builder
         */
        public Builder unsetPullRequestContributors() {
            pullRequestContributors = null;
            return this;
        }

        /**
         * Setter for codeAdditionsDeletions4Weeks.
         * @param  codeAdditionsDeletions4Weeks  CodeAdditionsDeletions4Weeks value for
         *         codeAdditionsDeletions4Weeks.
         * @return Builder
         */
        public Builder codeAdditionsDeletions4Weeks(
                CodeAdditionsDeletions4Weeks codeAdditionsDeletions4Weeks) {
            this.codeAdditionsDeletions4Weeks = codeAdditionsDeletions4Weeks;
            return this;
        }

        /**
         * Setter for commitCount4Weeks.
         * @param  commitCount4Weeks  Double value for commitCount4Weeks.
         * @return Builder
         */
        public Builder commitCount4Weeks(Double commitCount4Weeks) {
            this.commitCount4Weeks = OptionalNullable.of(commitCount4Weeks);
            return this;
        }

        /**
         * UnSetter for commitCount4Weeks.
         * @return Builder
         */
        public Builder unsetCommitCount4Weeks() {
            commitCount4Weeks = null;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link DeveloperData} object using the set fields.
         * @return {@link DeveloperData}
         */
        public DeveloperData build() {
            DeveloperData model =
                    new DeveloperData(forks, stars, subscribers, totalIssues, closedIssues,
                            pullRequestsMerged, pullRequestContributors,
                            codeAdditionsDeletions4Weeks, commitCount4Weeks);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
