/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * Duration to be used.
 */
public enum Duration {
    ENUM_5M,

    ENUM_1H,

    ENUM_6H,

    ENUM_24H;

    private static TreeMap<String, Duration> valueMap = new TreeMap<>();
    private String value;

    static {
        ENUM_5M.value = "5m";
        ENUM_1H.value = "1h";
        ENUM_6H.value = "6h";
        ENUM_24H.value = "24h";

        valueMap.put("5m", ENUM_5M);
        valueMap.put("1h", ENUM_1H);
        valueMap.put("6h", ENUM_6H);
        valueMap.put("24h", ENUM_24H);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Duration constructFromString(String toConvert) throws IOException {
        Duration enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Duration fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Duration values to list of string values.
     * @param toConvert The list of Duration values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Duration> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Duration enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 