/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Exchange type.
 */
public class Exchange {
    private String id;
    private String name;
    private String marketType;
    private String thumb;
    private String large;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Exchange() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  name  String value for name.
     * @param  marketType  String value for marketType.
     * @param  thumb  String value for thumb.
     * @param  large  String value for large.
     */
    public Exchange(
            String id,
            String name,
            String marketType,
            String thumb,
            String large) {
        this.id = id;
        this.name = name;
        this.marketType = marketType;
        this.thumb = thumb;
        this.large = large;
    }

    /**
     * Getter for Id.
     * Exchange ID
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Exchange ID
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for Name.
     * Exchange name
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * Exchange name
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for MarketType.
     * Exchange market type
     * @return Returns the String
     */
    @JsonGetter("market_type")
    public String getMarketType() {
        return marketType;
    }

    /**
     * Setter for MarketType.
     * Exchange market type
     * @param marketType Value for String
     */
    @JsonSetter("market_type")
    public void setMarketType(String marketType) {
        this.marketType = marketType;
    }

    /**
     * Getter for Thumb.
     * Exchange thumb image URL
     * @return Returns the String
     */
    @JsonGetter("thumb")
    public String getThumb() {
        return thumb;
    }

    /**
     * Setter for Thumb.
     * Exchange thumb image URL
     * @param thumb Value for String
     */
    @JsonSetter("thumb")
    public void setThumb(String thumb) {
        this.thumb = thumb;
    }

    /**
     * Getter for Large.
     * Exchange large image URL
     * @return Returns the String
     */
    @JsonGetter("large")
    public String getLarge() {
        return large;
    }

    /**
     * Setter for Large.
     * Exchange large image URL
     * @param large Value for String
     */
    @JsonSetter("large")
    public void setLarge(String large) {
        this.large = large;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Exchange into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Exchange [" + "id=" + id + ", name=" + name + ", marketType=" + marketType
                + ", thumb=" + thumb + ", large=" + large + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Exchange.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Exchange.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, name, marketType, thumb, large);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Exchange}.
     */
    public static class Builder {
        private String id;
        private String name;
        private String marketType;
        private String thumb;
        private String large;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  name  String value for name.
         * @param  marketType  String value for marketType.
         * @param  thumb  String value for thumb.
         * @param  large  String value for large.
         */
        public Builder(String id, String name, String marketType, String thumb, String large) {
            this.id = id;
            this.name = name;
            this.marketType = marketType;
            this.thumb = thumb;
            this.large = large;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for marketType.
         * @param  marketType  String value for marketType.
         * @return Builder
         */
        public Builder marketType(String marketType) {
            this.marketType = marketType;
            return this;
        }

        /**
         * Setter for thumb.
         * @param  thumb  String value for thumb.
         * @return Builder
         */
        public Builder thumb(String thumb) {
            this.thumb = thumb;
            return this;
        }

        /**
         * Setter for large.
         * @param  large  String value for large.
         * @return Builder
         */
        public Builder large(String large) {
            this.large = large;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Exchange} object using the set fields.
         * @return {@link Exchange}
         */
        public Exchange build() {
            Exchange model =
                    new Exchange(id, name, marketType, thumb, large);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
