/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Exchange1 type.
 */
public class Exchange1 {
    private String id;
    private String name;
    private Double yearEstablished;
    private String country;
    private String description;
    private String url;
    private String image;
    private boolean hasTradingIncentive;
    private Double trustScore;
    private Double trustScoreRank;
    private double tradeVolume24HBtc;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Exchange1() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  name  String value for name.
     * @param  yearEstablished  Double value for yearEstablished.
     * @param  country  String value for country.
     * @param  description  String value for description.
     * @param  url  String value for url.
     * @param  image  String value for image.
     * @param  hasTradingIncentive  boolean value for hasTradingIncentive.
     * @param  trustScore  Double value for trustScore.
     * @param  trustScoreRank  Double value for trustScoreRank.
     * @param  tradeVolume24HBtc  double value for tradeVolume24HBtc.
     */
    public Exchange1(
            String id,
            String name,
            Double yearEstablished,
            String country,
            String description,
            String url,
            String image,
            boolean hasTradingIncentive,
            Double trustScore,
            Double trustScoreRank,
            double tradeVolume24HBtc) {
        this.id = id;
        this.name = name;
        this.yearEstablished = yearEstablished;
        this.country = country;
        this.description = description;
        this.url = url;
        this.image = image;
        this.hasTradingIncentive = hasTradingIncentive;
        this.trustScore = trustScore;
        this.trustScoreRank = trustScoreRank;
        this.tradeVolume24HBtc = tradeVolume24HBtc;
    }

    /**
     * Getter for Id.
     * Exchange ID
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Exchange ID
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for Name.
     * Exchange name
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * Exchange name
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for YearEstablished.
     * Year the exchange was established
     * @return Returns the Double
     */
    @JsonGetter("year_established")
    public Double getYearEstablished() {
        return yearEstablished;
    }

    /**
     * Setter for YearEstablished.
     * Year the exchange was established
     * @param yearEstablished Value for Double
     */
    @JsonSetter("year_established")
    public void setYearEstablished(Double yearEstablished) {
        this.yearEstablished = yearEstablished;
    }

    /**
     * Getter for Country.
     * Country where the exchange is based
     * @return Returns the String
     */
    @JsonGetter("country")
    public String getCountry() {
        return country;
    }

    /**
     * Setter for Country.
     * Country where the exchange is based
     * @param country Value for String
     */
    @JsonSetter("country")
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * Getter for Description.
     * Exchange description
     * @return Returns the String
     */
    @JsonGetter("description")
    public String getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * Exchange description
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for Url.
     * Exchange website URL
     * @return Returns the String
     */
    @JsonGetter("url")
    public String getUrl() {
        return url;
    }

    /**
     * Setter for Url.
     * Exchange website URL
     * @param url Value for String
     */
    @JsonSetter("url")
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * Getter for Image.
     * Exchange logo URL
     * @return Returns the String
     */
    @JsonGetter("image")
    public String getImage() {
        return image;
    }

    /**
     * Setter for Image.
     * Exchange logo URL
     * @param image Value for String
     */
    @JsonSetter("image")
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * Getter for HasTradingIncentive.
     * Whether the exchange has trading incentive
     * @return Returns the boolean
     */
    @JsonGetter("has_trading_incentive")
    public boolean getHasTradingIncentive() {
        return hasTradingIncentive;
    }

    /**
     * Setter for HasTradingIncentive.
     * Whether the exchange has trading incentive
     * @param hasTradingIncentive Value for boolean
     */
    @JsonSetter("has_trading_incentive")
    public void setHasTradingIncentive(boolean hasTradingIncentive) {
        this.hasTradingIncentive = hasTradingIncentive;
    }

    /**
     * Getter for TrustScore.
     * Exchange trust score
     * @return Returns the Double
     */
    @JsonGetter("trust_score")
    public Double getTrustScore() {
        return trustScore;
    }

    /**
     * Setter for TrustScore.
     * Exchange trust score
     * @param trustScore Value for Double
     */
    @JsonSetter("trust_score")
    public void setTrustScore(Double trustScore) {
        this.trustScore = trustScore;
    }

    /**
     * Getter for TrustScoreRank.
     * Exchange trust score rank
     * @return Returns the Double
     */
    @JsonGetter("trust_score_rank")
    public Double getTrustScoreRank() {
        return trustScoreRank;
    }

    /**
     * Setter for TrustScoreRank.
     * Exchange trust score rank
     * @param trustScoreRank Value for Double
     */
    @JsonSetter("trust_score_rank")
    public void setTrustScoreRank(Double trustScoreRank) {
        this.trustScoreRank = trustScoreRank;
    }

    /**
     * Getter for TradeVolume24HBtc.
     * Exchange 24h trading volume in BTC
     * @return Returns the double
     */
    @JsonGetter("trade_volume_24h_btc")
    public double getTradeVolume24HBtc() {
        return tradeVolume24HBtc;
    }

    /**
     * Setter for TradeVolume24HBtc.
     * Exchange 24h trading volume in BTC
     * @param tradeVolume24HBtc Value for double
     */
    @JsonSetter("trade_volume_24h_btc")
    public void setTradeVolume24HBtc(double tradeVolume24HBtc) {
        this.tradeVolume24HBtc = tradeVolume24HBtc;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Exchange1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Exchange1 [" + "id=" + id + ", name=" + name + ", yearEstablished="
                + yearEstablished + ", country=" + country + ", description=" + description
                + ", url=" + url + ", image=" + image + ", hasTradingIncentive="
                + hasTradingIncentive + ", trustScore=" + trustScore + ", trustScoreRank="
                + trustScoreRank + ", tradeVolume24HBtc=" + tradeVolume24HBtc
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Exchange1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Exchange1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, name, yearEstablished, country, description, url, image,
                hasTradingIncentive, trustScore, trustScoreRank, tradeVolume24HBtc);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Exchange1}.
     */
    public static class Builder {
        private String id;
        private String name;
        private Double yearEstablished;
        private String country;
        private String description;
        private String url;
        private String image;
        private boolean hasTradingIncentive;
        private Double trustScore;
        private Double trustScoreRank;
        private double tradeVolume24HBtc;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  name  String value for name.
         * @param  yearEstablished  Double value for yearEstablished.
         * @param  country  String value for country.
         * @param  description  String value for description.
         * @param  url  String value for url.
         * @param  image  String value for image.
         * @param  hasTradingIncentive  boolean value for hasTradingIncentive.
         * @param  trustScore  Double value for trustScore.
         * @param  trustScoreRank  Double value for trustScoreRank.
         * @param  tradeVolume24HBtc  double value for tradeVolume24HBtc.
         */
        public Builder(String id, String name, Double yearEstablished, String country,
                String description, String url, String image, boolean hasTradingIncentive,
                Double trustScore, Double trustScoreRank, double tradeVolume24HBtc) {
            this.id = id;
            this.name = name;
            this.yearEstablished = yearEstablished;
            this.country = country;
            this.description = description;
            this.url = url;
            this.image = image;
            this.hasTradingIncentive = hasTradingIncentive;
            this.trustScore = trustScore;
            this.trustScoreRank = trustScoreRank;
            this.tradeVolume24HBtc = tradeVolume24HBtc;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for yearEstablished.
         * @param  yearEstablished  Double value for yearEstablished.
         * @return Builder
         */
        public Builder yearEstablished(Double yearEstablished) {
            this.yearEstablished = yearEstablished;
            return this;
        }

        /**
         * Setter for country.
         * @param  country  String value for country.
         * @return Builder
         */
        public Builder country(String country) {
            this.country = country;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Setter for url.
         * @param  url  String value for url.
         * @return Builder
         */
        public Builder url(String url) {
            this.url = url;
            return this;
        }

        /**
         * Setter for image.
         * @param  image  String value for image.
         * @return Builder
         */
        public Builder image(String image) {
            this.image = image;
            return this;
        }

        /**
         * Setter for hasTradingIncentive.
         * @param  hasTradingIncentive  boolean value for hasTradingIncentive.
         * @return Builder
         */
        public Builder hasTradingIncentive(boolean hasTradingIncentive) {
            this.hasTradingIncentive = hasTradingIncentive;
            return this;
        }

        /**
         * Setter for trustScore.
         * @param  trustScore  Double value for trustScore.
         * @return Builder
         */
        public Builder trustScore(Double trustScore) {
            this.trustScore = trustScore;
            return this;
        }

        /**
         * Setter for trustScoreRank.
         * @param  trustScoreRank  Double value for trustScoreRank.
         * @return Builder
         */
        public Builder trustScoreRank(Double trustScoreRank) {
            this.trustScoreRank = trustScoreRank;
            return this;
        }

        /**
         * Setter for tradeVolume24HBtc.
         * @param  tradeVolume24HBtc  double value for tradeVolume24HBtc.
         * @return Builder
         */
        public Builder tradeVolume24HBtc(double tradeVolume24HBtc) {
            this.tradeVolume24HBtc = tradeVolume24HBtc;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Exchange1} object using the set fields.
         * @return {@link Exchange1}
         */
        public Exchange1 build() {
            Exchange1 model =
                    new Exchange1(id, name, yearEstablished, country, description, url, image,
                            hasTradingIncentive, trustScore, trustScoreRank, tradeVolume24HBtc);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
