/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Holders type.
 */
public class Holders {
    private Integer count;
    private Map<String, String> distributionPercentage;
    private String lastUpdated;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Holders() {
    }

    /**
     * Initialization constructor.
     * @param  count  Integer value for count.
     * @param  distributionPercentage  Map of String, value for distributionPercentage.
     * @param  lastUpdated  String value for lastUpdated.
     */
    public Holders(
            Integer count,
            Map<String, String> distributionPercentage,
            String lastUpdated) {
        this.count = count;
        this.distributionPercentage = distributionPercentage;
        this.lastUpdated = lastUpdated;
    }

    /**
     * Getter for Count.
     * Number of holders
     * @return Returns the Integer
     */
    @JsonGetter("count")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getCount() {
        return count;
    }

    /**
     * Setter for Count.
     * Number of holders
     * @param count Value for Integer
     */
    @JsonSetter("count")
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * Getter for DistributionPercentage.
     * Holder distribution percentage (keys vary by chain, e.g. top_10, 11_30, 31_50, rest)
     * @return Returns the Map of String, String
     */
    @JsonGetter("distribution_percentage")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, String> getDistributionPercentage() {
        return distributionPercentage;
    }

    /**
     * Setter for DistributionPercentage.
     * Holder distribution percentage (keys vary by chain, e.g. top_10, 11_30, 31_50, rest)
     * @param distributionPercentage Value for Map of String, String
     */
    @JsonSetter("distribution_percentage")
    public void setDistributionPercentage(Map<String, String> distributionPercentage) {
        this.distributionPercentage = distributionPercentage;
    }

    /**
     * Getter for LastUpdated.
     * Last updated timestamp
     * @return Returns the String
     */
    @JsonGetter("last_updated")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLastUpdated() {
        return lastUpdated;
    }

    /**
     * Setter for LastUpdated.
     * Last updated timestamp
     * @param lastUpdated Value for String
     */
    @JsonSetter("last_updated")
    public void setLastUpdated(String lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Holders into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Holders [" + "count=" + count + ", distributionPercentage=" + distributionPercentage
                + ", lastUpdated=" + lastUpdated + ", additionalProperties=" + additionalProperties
                + "]";
    }

    /**
     * Builds a new {@link Holders.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Holders.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .count(getCount())
                .distributionPercentage(getDistributionPercentage())
                .lastUpdated(getLastUpdated());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Holders}.
     */
    public static class Builder {
        private Integer count;
        private Map<String, String> distributionPercentage;
        private String lastUpdated;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for count.
         * @param  count  Integer value for count.
         * @return Builder
         */
        public Builder count(Integer count) {
            this.count = count;
            return this;
        }

        /**
         * Setter for distributionPercentage.
         * @param  distributionPercentage  Map of String, value for distributionPercentage.
         * @return Builder
         */
        public Builder distributionPercentage(Map<String, String> distributionPercentage) {
            this.distributionPercentage = distributionPercentage;
            return this;
        }

        /**
         * Setter for lastUpdated.
         * @param  lastUpdated  String value for lastUpdated.
         * @return Builder
         */
        public Builder lastUpdated(String lastUpdated) {
            this.lastUpdated = lastUpdated;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Holders} object using the set fields.
         * @return {@link Holders}
         */
        public Holders build() {
            Holders model =
                    new Holders(count, distributionPercentage, lastUpdated);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
