/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Image3 type.
 */
public class Image3 {
    private String thumb;
    private String small;
    private String large;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Image3() {
    }

    /**
     * Initialization constructor.
     * @param  thumb  String value for thumb.
     * @param  small  String value for small.
     * @param  large  String value for large.
     */
    public Image3(
            String thumb,
            String small,
            String large) {
        this.thumb = thumb;
        this.small = small;
        this.large = large;
    }

    /**
     * Getter for Thumb.
     * Thumbnail image URL
     * @return Returns the String
     */
    @JsonGetter("thumb")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getThumb() {
        return thumb;
    }

    /**
     * Setter for Thumb.
     * Thumbnail image URL
     * @param thumb Value for String
     */
    @JsonSetter("thumb")
    public void setThumb(String thumb) {
        this.thumb = thumb;
    }

    /**
     * Getter for Small.
     * Small image URL
     * @return Returns the String
     */
    @JsonGetter("small")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSmall() {
        return small;
    }

    /**
     * Setter for Small.
     * Small image URL
     * @param small Value for String
     */
    @JsonSetter("small")
    public void setSmall(String small) {
        this.small = small;
    }

    /**
     * Getter for Large.
     * Large image URL
     * @return Returns the String
     */
    @JsonGetter("large")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLarge() {
        return large;
    }

    /**
     * Setter for Large.
     * Large image URL
     * @param large Value for String
     */
    @JsonSetter("large")
    public void setLarge(String large) {
        this.large = large;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Image3 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Image3 [" + "thumb=" + thumb + ", small=" + small + ", large=" + large
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Image3.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Image3.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .thumb(getThumb())
                .small(getSmall())
                .large(getLarge());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Image3}.
     */
    public static class Builder {
        private String thumb;
        private String small;
        private String large;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for thumb.
         * @param  thumb  String value for thumb.
         * @return Builder
         */
        public Builder thumb(String thumb) {
            this.thumb = thumb;
            return this;
        }

        /**
         * Setter for small.
         * @param  small  String value for small.
         * @return Builder
         */
        public Builder small(String small) {
            this.small = small;
            return this;
        }

        /**
         * Setter for large.
         * @param  large  String value for large.
         * @return Builder
         */
        public Builder large(String large) {
            this.large = large;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Image3} object using the set fields.
         * @return {@link Image3}
         */
        public Image3 build() {
            Image3 model =
                    new Image3(thumb, small, large);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
