/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Image5 type.
 */
public class Image5 {
    private String small;
    private String small2X;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Image5() {
    }

    /**
     * Initialization constructor.
     * @param  small  String value for small.
     * @param  small2X  String value for small2X.
     */
    public Image5(
            String small,
            String small2X) {
        this.small = small;
        this.small2X = small2X;
    }

    /**
     * Getter for Small.
     * @return Returns the String
     */
    @JsonGetter("small")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSmall() {
        return small;
    }

    /**
     * Setter for Small.
     * @param small Value for String
     */
    @JsonSetter("small")
    public void setSmall(String small) {
        this.small = small;
    }

    /**
     * Getter for Small2X.
     * @return Returns the String
     */
    @JsonGetter("small_2x")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSmall2X() {
        return small2X;
    }

    /**
     * Setter for Small2X.
     * @param small2X Value for String
     */
    @JsonSetter("small_2x")
    public void setSmall2X(String small2X) {
        this.small2X = small2X;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Image5 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Image5 [" + "small=" + small + ", small2X=" + small2X + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Image5.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Image5.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .small(getSmall())
                .small2X(getSmall2X());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Image5}.
     */
    public static class Builder {
        private String small;
        private String small2X;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for small.
         * @param  small  String value for small.
         * @return Builder
         */
        public Builder small(String small) {
            this.small = small;
            return this;
        }

        /**
         * Setter for small2X.
         * @param  small2X  String value for small2X.
         * @return Builder
         */
        public Builder small2X(String small2X) {
            this.small2X = small2X;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Image5} object using the set fields.
         * @return {@link Image5}
         */
        public Image5 build() {
            Image5 model =
                    new Image5(small, small2X);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
