/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.types.OptionalNullable;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for Links type.
 */
public class Links {
    private List<String> homepage;
    private String whitepaper;
    private List<String> blockchainSite;
    private List<String> officialForumUrl;
    private List<String> chatUrl;
    private List<String> announcementUrl;
    private OptionalNullable<String> snapshotUrl;
    private String twitterScreenName;
    private String facebookUsername;
    private OptionalNullable<Integer> bitcointalkThreadIdentifier;
    private String telegramChannelIdentifier;
    private String subredditUrl;
    private ReposUrl reposUrl;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Links() {
    }

    /**
     * Initialization constructor.
     * @param  homepage  List of String value for homepage.
     * @param  whitepaper  String value for whitepaper.
     * @param  blockchainSite  List of String value for blockchainSite.
     * @param  officialForumUrl  List of String value for officialForumUrl.
     * @param  chatUrl  List of String value for chatUrl.
     * @param  announcementUrl  List of String value for announcementUrl.
     * @param  snapshotUrl  String value for snapshotUrl.
     * @param  twitterScreenName  String value for twitterScreenName.
     * @param  facebookUsername  String value for facebookUsername.
     * @param  bitcointalkThreadIdentifier  Integer value for bitcointalkThreadIdentifier.
     * @param  telegramChannelIdentifier  String value for telegramChannelIdentifier.
     * @param  subredditUrl  String value for subredditUrl.
     * @param  reposUrl  ReposUrl value for reposUrl.
     */
    public Links(
            List<String> homepage,
            String whitepaper,
            List<String> blockchainSite,
            List<String> officialForumUrl,
            List<String> chatUrl,
            List<String> announcementUrl,
            String snapshotUrl,
            String twitterScreenName,
            String facebookUsername,
            Integer bitcointalkThreadIdentifier,
            String telegramChannelIdentifier,
            String subredditUrl,
            ReposUrl reposUrl) {
        this.homepage = homepage;
        this.whitepaper = whitepaper;
        this.blockchainSite = blockchainSite;
        this.officialForumUrl = officialForumUrl;
        this.chatUrl = chatUrl;
        this.announcementUrl = announcementUrl;
        this.snapshotUrl = OptionalNullable.of(snapshotUrl);
        this.twitterScreenName = twitterScreenName;
        this.facebookUsername = facebookUsername;
        this.bitcointalkThreadIdentifier = OptionalNullable.of(bitcointalkThreadIdentifier);
        this.telegramChannelIdentifier = telegramChannelIdentifier;
        this.subredditUrl = subredditUrl;
        this.reposUrl = reposUrl;
    }

    /**
     * Initialization constructor.
     * @param  homepage  List of String value for homepage.
     * @param  whitepaper  String value for whitepaper.
     * @param  blockchainSite  List of String value for blockchainSite.
     * @param  officialForumUrl  List of String value for officialForumUrl.
     * @param  chatUrl  List of String value for chatUrl.
     * @param  announcementUrl  List of String value for announcementUrl.
     * @param  snapshotUrl  String value for snapshotUrl.
     * @param  twitterScreenName  String value for twitterScreenName.
     * @param  facebookUsername  String value for facebookUsername.
     * @param  bitcointalkThreadIdentifier  Integer value for bitcointalkThreadIdentifier.
     * @param  telegramChannelIdentifier  String value for telegramChannelIdentifier.
     * @param  subredditUrl  String value for subredditUrl.
     * @param  reposUrl  ReposUrl value for reposUrl.
     */

    protected Links(List<String> homepage, String whitepaper, List<String> blockchainSite,
            List<String> officialForumUrl, List<String> chatUrl, List<String> announcementUrl,
            OptionalNullable<String> snapshotUrl, String twitterScreenName, String facebookUsername,
            OptionalNullable<Integer> bitcointalkThreadIdentifier, String telegramChannelIdentifier,
            String subredditUrl, ReposUrl reposUrl) {
        this.homepage = homepage;
        this.whitepaper = whitepaper;
        this.blockchainSite = blockchainSite;
        this.officialForumUrl = officialForumUrl;
        this.chatUrl = chatUrl;
        this.announcementUrl = announcementUrl;
        this.snapshotUrl = snapshotUrl;
        this.twitterScreenName = twitterScreenName;
        this.facebookUsername = facebookUsername;
        this.bitcointalkThreadIdentifier = bitcointalkThreadIdentifier;
        this.telegramChannelIdentifier = telegramChannelIdentifier;
        this.subredditUrl = subredditUrl;
        this.reposUrl = reposUrl;
    }

    /**
     * Getter for Homepage.
     * Website URL
     * @return Returns the List of String
     */
    @JsonGetter("homepage")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getHomepage() {
        return homepage;
    }

    /**
     * Setter for Homepage.
     * Website URL
     * @param homepage Value for List of String
     */
    @JsonSetter("homepage")
    public void setHomepage(List<String> homepage) {
        this.homepage = homepage;
    }

    /**
     * Getter for Whitepaper.
     * Whitepaper URL
     * @return Returns the String
     */
    @JsonGetter("whitepaper")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getWhitepaper() {
        return whitepaper;
    }

    /**
     * Setter for Whitepaper.
     * Whitepaper URL
     * @param whitepaper Value for String
     */
    @JsonSetter("whitepaper")
    public void setWhitepaper(String whitepaper) {
        this.whitepaper = whitepaper;
    }

    /**
     * Getter for BlockchainSite.
     * Block explorer URL
     * @return Returns the List of String
     */
    @JsonGetter("blockchain_site")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getBlockchainSite() {
        return blockchainSite;
    }

    /**
     * Setter for BlockchainSite.
     * Block explorer URL
     * @param blockchainSite Value for List of String
     */
    @JsonSetter("blockchain_site")
    public void setBlockchainSite(List<String> blockchainSite) {
        this.blockchainSite = blockchainSite;
    }

    /**
     * Getter for OfficialForumUrl.
     * Official forum URL
     * @return Returns the List of String
     */
    @JsonGetter("official_forum_url")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getOfficialForumUrl() {
        return officialForumUrl;
    }

    /**
     * Setter for OfficialForumUrl.
     * Official forum URL
     * @param officialForumUrl Value for List of String
     */
    @JsonSetter("official_forum_url")
    public void setOfficialForumUrl(List<String> officialForumUrl) {
        this.officialForumUrl = officialForumUrl;
    }

    /**
     * Getter for ChatUrl.
     * Chat URL
     * @return Returns the List of String
     */
    @JsonGetter("chat_url")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getChatUrl() {
        return chatUrl;
    }

    /**
     * Setter for ChatUrl.
     * Chat URL
     * @param chatUrl Value for List of String
     */
    @JsonSetter("chat_url")
    public void setChatUrl(List<String> chatUrl) {
        this.chatUrl = chatUrl;
    }

    /**
     * Getter for AnnouncementUrl.
     * Announcement URL
     * @return Returns the List of String
     */
    @JsonGetter("announcement_url")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getAnnouncementUrl() {
        return announcementUrl;
    }

    /**
     * Setter for AnnouncementUrl.
     * Announcement URL
     * @param announcementUrl Value for List of String
     */
    @JsonSetter("announcement_url")
    public void setAnnouncementUrl(List<String> announcementUrl) {
        this.announcementUrl = announcementUrl;
    }

    /**
     * Internal Getter for SnapshotUrl.
     * Snapshot URL
     * @return Returns the Internal String
     */
    @JsonGetter("snapshot_url")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetSnapshotUrl() {
        return this.snapshotUrl;
    }

    /**
     * Getter for SnapshotUrl.
     * Snapshot URL
     * @return Returns the String
     */
    public String getSnapshotUrl() {
        return OptionalNullable.getFrom(snapshotUrl);
    }

    /**
     * Setter for SnapshotUrl.
     * Snapshot URL
     * @param snapshotUrl Value for String
     */
    @JsonSetter("snapshot_url")
    public void setSnapshotUrl(String snapshotUrl) {
        this.snapshotUrl = OptionalNullable.of(snapshotUrl);
    }

    /**
     * UnSetter for SnapshotUrl.
     * Snapshot URL
     */
    public void unsetSnapshotUrl() {
        snapshotUrl = null;
    }

    /**
     * Getter for TwitterScreenName.
     * Twitter handle
     * @return Returns the String
     */
    @JsonGetter("twitter_screen_name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTwitterScreenName() {
        return twitterScreenName;
    }

    /**
     * Setter for TwitterScreenName.
     * Twitter handle
     * @param twitterScreenName Value for String
     */
    @JsonSetter("twitter_screen_name")
    public void setTwitterScreenName(String twitterScreenName) {
        this.twitterScreenName = twitterScreenName;
    }

    /**
     * Getter for FacebookUsername.
     * Facebook username
     * @return Returns the String
     */
    @JsonGetter("facebook_username")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getFacebookUsername() {
        return facebookUsername;
    }

    /**
     * Setter for FacebookUsername.
     * Facebook username
     * @param facebookUsername Value for String
     */
    @JsonSetter("facebook_username")
    public void setFacebookUsername(String facebookUsername) {
        this.facebookUsername = facebookUsername;
    }

    /**
     * Internal Getter for BitcointalkThreadIdentifier.
     * Bitcointalk thread identifier
     * @return Returns the Internal Integer
     */
    @JsonGetter("bitcointalk_thread_identifier")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Integer> internalGetBitcointalkThreadIdentifier() {
        return this.bitcointalkThreadIdentifier;
    }

    /**
     * Getter for BitcointalkThreadIdentifier.
     * Bitcointalk thread identifier
     * @return Returns the Integer
     */
    public Integer getBitcointalkThreadIdentifier() {
        return OptionalNullable.getFrom(bitcointalkThreadIdentifier);
    }

    /**
     * Setter for BitcointalkThreadIdentifier.
     * Bitcointalk thread identifier
     * @param bitcointalkThreadIdentifier Value for Integer
     */
    @JsonSetter("bitcointalk_thread_identifier")
    public void setBitcointalkThreadIdentifier(Integer bitcointalkThreadIdentifier) {
        this.bitcointalkThreadIdentifier = OptionalNullable.of(bitcointalkThreadIdentifier);
    }

    /**
     * UnSetter for BitcointalkThreadIdentifier.
     * Bitcointalk thread identifier
     */
    public void unsetBitcointalkThreadIdentifier() {
        bitcointalkThreadIdentifier = null;
    }

    /**
     * Getter for TelegramChannelIdentifier.
     * Telegram channel identifier
     * @return Returns the String
     */
    @JsonGetter("telegram_channel_identifier")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTelegramChannelIdentifier() {
        return telegramChannelIdentifier;
    }

    /**
     * Setter for TelegramChannelIdentifier.
     * Telegram channel identifier
     * @param telegramChannelIdentifier Value for String
     */
    @JsonSetter("telegram_channel_identifier")
    public void setTelegramChannelIdentifier(String telegramChannelIdentifier) {
        this.telegramChannelIdentifier = telegramChannelIdentifier;
    }

    /**
     * Getter for SubredditUrl.
     * Subreddit URL
     * @return Returns the String
     */
    @JsonGetter("subreddit_url")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSubredditUrl() {
        return subredditUrl;
    }

    /**
     * Setter for SubredditUrl.
     * Subreddit URL
     * @param subredditUrl Value for String
     */
    @JsonSetter("subreddit_url")
    public void setSubredditUrl(String subredditUrl) {
        this.subredditUrl = subredditUrl;
    }

    /**
     * Getter for ReposUrl.
     * Repository URL
     * @return Returns the ReposUrl
     */
    @JsonGetter("repos_url")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ReposUrl getReposUrl() {
        return reposUrl;
    }

    /**
     * Setter for ReposUrl.
     * Repository URL
     * @param reposUrl Value for ReposUrl
     */
    @JsonSetter("repos_url")
    public void setReposUrl(ReposUrl reposUrl) {
        this.reposUrl = reposUrl;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Links into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Links [" + "homepage=" + homepage + ", whitepaper=" + whitepaper
                + ", blockchainSite=" + blockchainSite + ", officialForumUrl=" + officialForumUrl
                + ", chatUrl=" + chatUrl + ", announcementUrl=" + announcementUrl + ", snapshotUrl="
                + snapshotUrl + ", twitterScreenName=" + twitterScreenName + ", facebookUsername="
                + facebookUsername + ", bitcointalkThreadIdentifier=" + bitcointalkThreadIdentifier
                + ", telegramChannelIdentifier=" + telegramChannelIdentifier + ", subredditUrl="
                + subredditUrl + ", reposUrl=" + reposUrl + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Links.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Links.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .homepage(getHomepage())
                .whitepaper(getWhitepaper())
                .blockchainSite(getBlockchainSite())
                .officialForumUrl(getOfficialForumUrl())
                .chatUrl(getChatUrl())
                .announcementUrl(getAnnouncementUrl())
                .twitterScreenName(getTwitterScreenName())
                .facebookUsername(getFacebookUsername())
                .telegramChannelIdentifier(getTelegramChannelIdentifier())
                .subredditUrl(getSubredditUrl())
                .reposUrl(getReposUrl());
        builder.snapshotUrl = internalGetSnapshotUrl();
        builder.bitcointalkThreadIdentifier = internalGetBitcointalkThreadIdentifier();
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Links}.
     */
    public static class Builder {
        private List<String> homepage;
        private String whitepaper;
        private List<String> blockchainSite;
        private List<String> officialForumUrl;
        private List<String> chatUrl;
        private List<String> announcementUrl;
        private OptionalNullable<String> snapshotUrl;
        private String twitterScreenName;
        private String facebookUsername;
        private OptionalNullable<Integer> bitcointalkThreadIdentifier;
        private String telegramChannelIdentifier;
        private String subredditUrl;
        private ReposUrl reposUrl;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for homepage.
         * @param  homepage  List of String value for homepage.
         * @return Builder
         */
        public Builder homepage(List<String> homepage) {
            this.homepage = homepage;
            return this;
        }

        /**
         * Setter for whitepaper.
         * @param  whitepaper  String value for whitepaper.
         * @return Builder
         */
        public Builder whitepaper(String whitepaper) {
            this.whitepaper = whitepaper;
            return this;
        }

        /**
         * Setter for blockchainSite.
         * @param  blockchainSite  List of String value for blockchainSite.
         * @return Builder
         */
        public Builder blockchainSite(List<String> blockchainSite) {
            this.blockchainSite = blockchainSite;
            return this;
        }

        /**
         * Setter for officialForumUrl.
         * @param  officialForumUrl  List of String value for officialForumUrl.
         * @return Builder
         */
        public Builder officialForumUrl(List<String> officialForumUrl) {
            this.officialForumUrl = officialForumUrl;
            return this;
        }

        /**
         * Setter for chatUrl.
         * @param  chatUrl  List of String value for chatUrl.
         * @return Builder
         */
        public Builder chatUrl(List<String> chatUrl) {
            this.chatUrl = chatUrl;
            return this;
        }

        /**
         * Setter for announcementUrl.
         * @param  announcementUrl  List of String value for announcementUrl.
         * @return Builder
         */
        public Builder announcementUrl(List<String> announcementUrl) {
            this.announcementUrl = announcementUrl;
            return this;
        }

        /**
         * Setter for snapshotUrl.
         * @param  snapshotUrl  String value for snapshotUrl.
         * @return Builder
         */
        public Builder snapshotUrl(String snapshotUrl) {
            this.snapshotUrl = OptionalNullable.of(snapshotUrl);
            return this;
        }

        /**
         * UnSetter for snapshotUrl.
         * @return Builder
         */
        public Builder unsetSnapshotUrl() {
            snapshotUrl = null;
            return this;
        }

        /**
         * Setter for twitterScreenName.
         * @param  twitterScreenName  String value for twitterScreenName.
         * @return Builder
         */
        public Builder twitterScreenName(String twitterScreenName) {
            this.twitterScreenName = twitterScreenName;
            return this;
        }

        /**
         * Setter for facebookUsername.
         * @param  facebookUsername  String value for facebookUsername.
         * @return Builder
         */
        public Builder facebookUsername(String facebookUsername) {
            this.facebookUsername = facebookUsername;
            return this;
        }

        /**
         * Setter for bitcointalkThreadIdentifier.
         * @param  bitcointalkThreadIdentifier  Integer value for bitcointalkThreadIdentifier.
         * @return Builder
         */
        public Builder bitcointalkThreadIdentifier(Integer bitcointalkThreadIdentifier) {
            this.bitcointalkThreadIdentifier = OptionalNullable.of(bitcointalkThreadIdentifier);
            return this;
        }

        /**
         * UnSetter for bitcointalkThreadIdentifier.
         * @return Builder
         */
        public Builder unsetBitcointalkThreadIdentifier() {
            bitcointalkThreadIdentifier = null;
            return this;
        }

        /**
         * Setter for telegramChannelIdentifier.
         * @param  telegramChannelIdentifier  String value for telegramChannelIdentifier.
         * @return Builder
         */
        public Builder telegramChannelIdentifier(String telegramChannelIdentifier) {
            this.telegramChannelIdentifier = telegramChannelIdentifier;
            return this;
        }

        /**
         * Setter for subredditUrl.
         * @param  subredditUrl  String value for subredditUrl.
         * @return Builder
         */
        public Builder subredditUrl(String subredditUrl) {
            this.subredditUrl = subredditUrl;
            return this;
        }

        /**
         * Setter for reposUrl.
         * @param  reposUrl  ReposUrl value for reposUrl.
         * @return Builder
         */
        public Builder reposUrl(ReposUrl reposUrl) {
            this.reposUrl = reposUrl;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Links} object using the set fields.
         * @return {@link Links}
         */
        public Links build() {
            Links model =
                    new Links(homepage, whitepaper, blockchainSite, officialForumUrl, chatUrl,
                            announcementUrl, snapshotUrl, twitterScreenName, facebookUsername,
                            bitcointalkThreadIdentifier, telegramChannelIdentifier, subredditUrl,
                            reposUrl);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
