/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.types.OptionalNullable;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for MarketData1 type.
 */
public class MarketData1 {
    private Map<String, Double> currentPrice;
    private OptionalNullable<Double> totalValueLocked;
    private OptionalNullable<Double> mcapToTvlRatio;
    private OptionalNullable<Double> fdvToTvlRatio;
    private OptionalNullable<Roi> roi;
    private Map<String, Double> ath;
    private Map<String, Double> athChangePercentage;
    private Map<String, String> athDate;
    private Map<String, Double> atl;
    private Map<String, Double> atlChangePercentage;
    private Map<String, String> atlDate;
    private Map<String, Double> marketCap;
    private Map<String, Double> fullyDilutedValuation;
    private Double marketCapFdvRatio;
    private OptionalNullable<Integer> marketCapRank;
    private OptionalNullable<Double> outstandingTokenValueUsd;
    private OptionalNullable<Integer> marketCapRankWithRehypothecated;
    private Map<String, Double> totalVolume;
    private Map<String, Double> high24H;
    private Map<String, Double> low24H;
    private Double priceChange24H;
    private Double priceChangePercentage24H;
    private Double priceChangePercentage7D;
    private Double priceChangePercentage14D;
    private Double priceChangePercentage30D;
    private Double priceChangePercentage60D;
    private Double priceChangePercentage200D;
    private Double priceChangePercentage1Y;
    private Double marketCapChange24H;
    private Double marketCapChangePercentage24H;
    private Map<String, Double> priceChange24HInCurrency;
    private Map<String, Double> priceChangePercentage1HInCurrency;
    private Map<String, Double> priceChangePercentage24HInCurrency;
    private Map<String, Double> priceChangePercentage7DInCurrency;
    private Map<String, Double> priceChangePercentage14DInCurrency;
    private Map<String, Double> priceChangePercentage30DInCurrency;
    private Map<String, Double> priceChangePercentage60DInCurrency;
    private Map<String, Double> priceChangePercentage200DInCurrency;
    private Map<String, Double> priceChangePercentage1YInCurrency;
    private Map<String, Double> marketCapChange24HInCurrency;
    private Map<String, Double> marketCapChangePercentage24HInCurrency;
    private Double totalSupply;
    private OptionalNullable<Double> maxSupply;
    private Boolean maxSupplyInfinite;
    private Double circulatingSupply;
    private OptionalNullable<Double> outstandingSupply;
    private String lastUpdated;
    private List<Double> sparkline7D;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public MarketData1() {
    }

    /**
     * Initialization constructor.
     * @param  currentPrice  Map of String, value for currentPrice.
     * @param  totalValueLocked  Double value for totalValueLocked.
     * @param  mcapToTvlRatio  Double value for mcapToTvlRatio.
     * @param  fdvToTvlRatio  Double value for fdvToTvlRatio.
     * @param  roi  Roi value for roi.
     * @param  ath  Map of String, value for ath.
     * @param  athChangePercentage  Map of String, value for athChangePercentage.
     * @param  athDate  Map of String, value for athDate.
     * @param  atl  Map of String, value for atl.
     * @param  atlChangePercentage  Map of String, value for atlChangePercentage.
     * @param  atlDate  Map of String, value for atlDate.
     * @param  marketCap  Map of String, value for marketCap.
     * @param  fullyDilutedValuation  Map of String, value for fullyDilutedValuation.
     * @param  marketCapFdvRatio  Double value for marketCapFdvRatio.
     * @param  marketCapRank  Integer value for marketCapRank.
     * @param  outstandingTokenValueUsd  Double value for outstandingTokenValueUsd.
     * @param  marketCapRankWithRehypothecated  Integer value for marketCapRankWithRehypothecated.
     * @param  totalVolume  Map of String, value for totalVolume.
     * @param  high24H  Map of String, value for high24H.
     * @param  low24H  Map of String, value for low24H.
     * @param  priceChange24H  Double value for priceChange24H.
     * @param  priceChangePercentage24H  Double value for priceChangePercentage24H.
     * @param  priceChangePercentage7D  Double value for priceChangePercentage7D.
     * @param  priceChangePercentage14D  Double value for priceChangePercentage14D.
     * @param  priceChangePercentage30D  Double value for priceChangePercentage30D.
     * @param  priceChangePercentage60D  Double value for priceChangePercentage60D.
     * @param  priceChangePercentage200D  Double value for priceChangePercentage200D.
     * @param  priceChangePercentage1Y  Double value for priceChangePercentage1Y.
     * @param  marketCapChange24H  Double value for marketCapChange24H.
     * @param  marketCapChangePercentage24H  Double value for marketCapChangePercentage24H.
     * @param  priceChange24HInCurrency  Map of String, value for priceChange24HInCurrency.
     * @param  priceChangePercentage1HInCurrency  Map of String, value for
     *         priceChangePercentage1HInCurrency.
     * @param  priceChangePercentage24HInCurrency  Map of String, value for
     *         priceChangePercentage24HInCurrency.
     * @param  priceChangePercentage7DInCurrency  Map of String, value for
     *         priceChangePercentage7DInCurrency.
     * @param  priceChangePercentage14DInCurrency  Map of String, value for
     *         priceChangePercentage14DInCurrency.
     * @param  priceChangePercentage30DInCurrency  Map of String, value for
     *         priceChangePercentage30DInCurrency.
     * @param  priceChangePercentage60DInCurrency  Map of String, value for
     *         priceChangePercentage60DInCurrency.
     * @param  priceChangePercentage200DInCurrency  Map of String, value for
     *         priceChangePercentage200DInCurrency.
     * @param  priceChangePercentage1YInCurrency  Map of String, value for
     *         priceChangePercentage1YInCurrency.
     * @param  marketCapChange24HInCurrency  Map of String, value for marketCapChange24HInCurrency.
     * @param  marketCapChangePercentage24HInCurrency  Map of String, value for
     *         marketCapChangePercentage24HInCurrency.
     * @param  totalSupply  Double value for totalSupply.
     * @param  maxSupply  Double value for maxSupply.
     * @param  maxSupplyInfinite  Boolean value for maxSupplyInfinite.
     * @param  circulatingSupply  Double value for circulatingSupply.
     * @param  outstandingSupply  Double value for outstandingSupply.
     * @param  lastUpdated  String value for lastUpdated.
     * @param  sparkline7D  List of Double value for sparkline7D.
     */
    public MarketData1(
            Map<String, Double> currentPrice,
            Double totalValueLocked,
            Double mcapToTvlRatio,
            Double fdvToTvlRatio,
            Roi roi,
            Map<String, Double> ath,
            Map<String, Double> athChangePercentage,
            Map<String, String> athDate,
            Map<String, Double> atl,
            Map<String, Double> atlChangePercentage,
            Map<String, String> atlDate,
            Map<String, Double> marketCap,
            Map<String, Double> fullyDilutedValuation,
            Double marketCapFdvRatio,
            Integer marketCapRank,
            Double outstandingTokenValueUsd,
            Integer marketCapRankWithRehypothecated,
            Map<String, Double> totalVolume,
            Map<String, Double> high24H,
            Map<String, Double> low24H,
            Double priceChange24H,
            Double priceChangePercentage24H,
            Double priceChangePercentage7D,
            Double priceChangePercentage14D,
            Double priceChangePercentage30D,
            Double priceChangePercentage60D,
            Double priceChangePercentage200D,
            Double priceChangePercentage1Y,
            Double marketCapChange24H,
            Double marketCapChangePercentage24H,
            Map<String, Double> priceChange24HInCurrency,
            Map<String, Double> priceChangePercentage1HInCurrency,
            Map<String, Double> priceChangePercentage24HInCurrency,
            Map<String, Double> priceChangePercentage7DInCurrency,
            Map<String, Double> priceChangePercentage14DInCurrency,
            Map<String, Double> priceChangePercentage30DInCurrency,
            Map<String, Double> priceChangePercentage60DInCurrency,
            Map<String, Double> priceChangePercentage200DInCurrency,
            Map<String, Double> priceChangePercentage1YInCurrency,
            Map<String, Double> marketCapChange24HInCurrency,
            Map<String, Double> marketCapChangePercentage24HInCurrency,
            Double totalSupply,
            Double maxSupply,
            Boolean maxSupplyInfinite,
            Double circulatingSupply,
            Double outstandingSupply,
            String lastUpdated,
            List<Double> sparkline7D) {
        this.currentPrice = currentPrice;
        this.totalValueLocked = OptionalNullable.of(totalValueLocked);
        this.mcapToTvlRatio = OptionalNullable.of(mcapToTvlRatio);
        this.fdvToTvlRatio = OptionalNullable.of(fdvToTvlRatio);
        this.roi = OptionalNullable.of(roi);
        this.ath = ath;
        this.athChangePercentage = athChangePercentage;
        this.athDate = athDate;
        this.atl = atl;
        this.atlChangePercentage = atlChangePercentage;
        this.atlDate = atlDate;
        this.marketCap = marketCap;
        this.fullyDilutedValuation = fullyDilutedValuation;
        this.marketCapFdvRatio = marketCapFdvRatio;
        this.marketCapRank = OptionalNullable.of(marketCapRank);
        this.outstandingTokenValueUsd = OptionalNullable.of(outstandingTokenValueUsd);
        this.marketCapRankWithRehypothecated = OptionalNullable.of(marketCapRankWithRehypothecated);
        this.totalVolume = totalVolume;
        this.high24H = high24H;
        this.low24H = low24H;
        this.priceChange24H = priceChange24H;
        this.priceChangePercentage24H = priceChangePercentage24H;
        this.priceChangePercentage7D = priceChangePercentage7D;
        this.priceChangePercentage14D = priceChangePercentage14D;
        this.priceChangePercentage30D = priceChangePercentage30D;
        this.priceChangePercentage60D = priceChangePercentage60D;
        this.priceChangePercentage200D = priceChangePercentage200D;
        this.priceChangePercentage1Y = priceChangePercentage1Y;
        this.marketCapChange24H = marketCapChange24H;
        this.marketCapChangePercentage24H = marketCapChangePercentage24H;
        this.priceChange24HInCurrency = priceChange24HInCurrency;
        this.priceChangePercentage1HInCurrency = priceChangePercentage1HInCurrency;
        this.priceChangePercentage24HInCurrency = priceChangePercentage24HInCurrency;
        this.priceChangePercentage7DInCurrency = priceChangePercentage7DInCurrency;
        this.priceChangePercentage14DInCurrency = priceChangePercentage14DInCurrency;
        this.priceChangePercentage30DInCurrency = priceChangePercentage30DInCurrency;
        this.priceChangePercentage60DInCurrency = priceChangePercentage60DInCurrency;
        this.priceChangePercentage200DInCurrency = priceChangePercentage200DInCurrency;
        this.priceChangePercentage1YInCurrency = priceChangePercentage1YInCurrency;
        this.marketCapChange24HInCurrency = marketCapChange24HInCurrency;
        this.marketCapChangePercentage24HInCurrency = marketCapChangePercentage24HInCurrency;
        this.totalSupply = totalSupply;
        this.maxSupply = OptionalNullable.of(maxSupply);
        this.maxSupplyInfinite = maxSupplyInfinite;
        this.circulatingSupply = circulatingSupply;
        this.outstandingSupply = OptionalNullable.of(outstandingSupply);
        this.lastUpdated = lastUpdated;
        this.sparkline7D = sparkline7D;
    }

    /**
     * Initialization constructor.
     * @param  currentPrice  Map of String, value for currentPrice.
     * @param  totalValueLocked  Double value for totalValueLocked.
     * @param  mcapToTvlRatio  Double value for mcapToTvlRatio.
     * @param  fdvToTvlRatio  Double value for fdvToTvlRatio.
     * @param  roi  Roi value for roi.
     * @param  ath  Map of String, value for ath.
     * @param  athChangePercentage  Map of String, value for athChangePercentage.
     * @param  athDate  Map of String, value for athDate.
     * @param  atl  Map of String, value for atl.
     * @param  atlChangePercentage  Map of String, value for atlChangePercentage.
     * @param  atlDate  Map of String, value for atlDate.
     * @param  marketCap  Map of String, value for marketCap.
     * @param  fullyDilutedValuation  Map of String, value for fullyDilutedValuation.
     * @param  marketCapFdvRatio  Double value for marketCapFdvRatio.
     * @param  marketCapRank  Integer value for marketCapRank.
     * @param  outstandingTokenValueUsd  Double value for outstandingTokenValueUsd.
     * @param  marketCapRankWithRehypothecated  Integer value for marketCapRankWithRehypothecated.
     * @param  totalVolume  Map of String, value for totalVolume.
     * @param  high24H  Map of String, value for high24H.
     * @param  low24H  Map of String, value for low24H.
     * @param  priceChange24H  Double value for priceChange24H.
     * @param  priceChangePercentage24H  Double value for priceChangePercentage24H.
     * @param  priceChangePercentage7D  Double value for priceChangePercentage7D.
     * @param  priceChangePercentage14D  Double value for priceChangePercentage14D.
     * @param  priceChangePercentage30D  Double value for priceChangePercentage30D.
     * @param  priceChangePercentage60D  Double value for priceChangePercentage60D.
     * @param  priceChangePercentage200D  Double value for priceChangePercentage200D.
     * @param  priceChangePercentage1Y  Double value for priceChangePercentage1Y.
     * @param  marketCapChange24H  Double value for marketCapChange24H.
     * @param  marketCapChangePercentage24H  Double value for marketCapChangePercentage24H.
     * @param  priceChange24HInCurrency  Map of String, value for priceChange24HInCurrency.
     * @param  priceChangePercentage1HInCurrency  Map of String, value for
     *         priceChangePercentage1HInCurrency.
     * @param  priceChangePercentage24HInCurrency  Map of String, value for
     *         priceChangePercentage24HInCurrency.
     * @param  priceChangePercentage7DInCurrency  Map of String, value for
     *         priceChangePercentage7DInCurrency.
     * @param  priceChangePercentage14DInCurrency  Map of String, value for
     *         priceChangePercentage14DInCurrency.
     * @param  priceChangePercentage30DInCurrency  Map of String, value for
     *         priceChangePercentage30DInCurrency.
     * @param  priceChangePercentage60DInCurrency  Map of String, value for
     *         priceChangePercentage60DInCurrency.
     * @param  priceChangePercentage200DInCurrency  Map of String, value for
     *         priceChangePercentage200DInCurrency.
     * @param  priceChangePercentage1YInCurrency  Map of String, value for
     *         priceChangePercentage1YInCurrency.
     * @param  marketCapChange24HInCurrency  Map of String, value for marketCapChange24HInCurrency.
     * @param  marketCapChangePercentage24HInCurrency  Map of String, value for
     *         marketCapChangePercentage24HInCurrency.
     * @param  totalSupply  Double value for totalSupply.
     * @param  maxSupply  Double value for maxSupply.
     * @param  maxSupplyInfinite  Boolean value for maxSupplyInfinite.
     * @param  circulatingSupply  Double value for circulatingSupply.
     * @param  outstandingSupply  Double value for outstandingSupply.
     * @param  lastUpdated  String value for lastUpdated.
     * @param  sparkline7D  List of Double value for sparkline7D.
     */

    protected MarketData1(Map<String, Double> currentPrice,
            OptionalNullable<Double> totalValueLocked, OptionalNullable<Double> mcapToTvlRatio,
            OptionalNullable<Double> fdvToTvlRatio, OptionalNullable<Roi> roi,
            Map<String, Double> ath, Map<String, Double> athChangePercentage,
            Map<String, String> athDate, Map<String, Double> atl,
            Map<String, Double> atlChangePercentage, Map<String, String> atlDate,
            Map<String, Double> marketCap, Map<String, Double> fullyDilutedValuation,
            Double marketCapFdvRatio, OptionalNullable<Integer> marketCapRank,
            OptionalNullable<Double> outstandingTokenValueUsd,
            OptionalNullable<Integer> marketCapRankWithRehypothecated,
            Map<String, Double> totalVolume, Map<String, Double> high24H,
            Map<String, Double> low24H, Double priceChange24H, Double priceChangePercentage24H,
            Double priceChangePercentage7D, Double priceChangePercentage14D,
            Double priceChangePercentage30D, Double priceChangePercentage60D,
            Double priceChangePercentage200D, Double priceChangePercentage1Y,
            Double marketCapChange24H, Double marketCapChangePercentage24H,
            Map<String, Double> priceChange24HInCurrency,
            Map<String, Double> priceChangePercentage1HInCurrency,
            Map<String, Double> priceChangePercentage24HInCurrency,
            Map<String, Double> priceChangePercentage7DInCurrency,
            Map<String, Double> priceChangePercentage14DInCurrency,
            Map<String, Double> priceChangePercentage30DInCurrency,
            Map<String, Double> priceChangePercentage60DInCurrency,
            Map<String, Double> priceChangePercentage200DInCurrency,
            Map<String, Double> priceChangePercentage1YInCurrency,
            Map<String, Double> marketCapChange24HInCurrency,
            Map<String, Double> marketCapChangePercentage24HInCurrency, Double totalSupply,
            OptionalNullable<Double> maxSupply, Boolean maxSupplyInfinite, Double circulatingSupply,
            OptionalNullable<Double> outstandingSupply, String lastUpdated,
            List<Double> sparkline7D) {
        this.currentPrice = currentPrice;
        this.totalValueLocked = totalValueLocked;
        this.mcapToTvlRatio = mcapToTvlRatio;
        this.fdvToTvlRatio = fdvToTvlRatio;
        this.roi = roi;
        this.ath = ath;
        this.athChangePercentage = athChangePercentage;
        this.athDate = athDate;
        this.atl = atl;
        this.atlChangePercentage = atlChangePercentage;
        this.atlDate = atlDate;
        this.marketCap = marketCap;
        this.fullyDilutedValuation = fullyDilutedValuation;
        this.marketCapFdvRatio = marketCapFdvRatio;
        this.marketCapRank = marketCapRank;
        this.outstandingTokenValueUsd = outstandingTokenValueUsd;
        this.marketCapRankWithRehypothecated = marketCapRankWithRehypothecated;
        this.totalVolume = totalVolume;
        this.high24H = high24H;
        this.low24H = low24H;
        this.priceChange24H = priceChange24H;
        this.priceChangePercentage24H = priceChangePercentage24H;
        this.priceChangePercentage7D = priceChangePercentage7D;
        this.priceChangePercentage14D = priceChangePercentage14D;
        this.priceChangePercentage30D = priceChangePercentage30D;
        this.priceChangePercentage60D = priceChangePercentage60D;
        this.priceChangePercentage200D = priceChangePercentage200D;
        this.priceChangePercentage1Y = priceChangePercentage1Y;
        this.marketCapChange24H = marketCapChange24H;
        this.marketCapChangePercentage24H = marketCapChangePercentage24H;
        this.priceChange24HInCurrency = priceChange24HInCurrency;
        this.priceChangePercentage1HInCurrency = priceChangePercentage1HInCurrency;
        this.priceChangePercentage24HInCurrency = priceChangePercentage24HInCurrency;
        this.priceChangePercentage7DInCurrency = priceChangePercentage7DInCurrency;
        this.priceChangePercentage14DInCurrency = priceChangePercentage14DInCurrency;
        this.priceChangePercentage30DInCurrency = priceChangePercentage30DInCurrency;
        this.priceChangePercentage60DInCurrency = priceChangePercentage60DInCurrency;
        this.priceChangePercentage200DInCurrency = priceChangePercentage200DInCurrency;
        this.priceChangePercentage1YInCurrency = priceChangePercentage1YInCurrency;
        this.marketCapChange24HInCurrency = marketCapChange24HInCurrency;
        this.marketCapChangePercentage24HInCurrency = marketCapChangePercentage24HInCurrency;
        this.totalSupply = totalSupply;
        this.maxSupply = maxSupply;
        this.maxSupplyInfinite = maxSupplyInfinite;
        this.circulatingSupply = circulatingSupply;
        this.outstandingSupply = outstandingSupply;
        this.lastUpdated = lastUpdated;
        this.sparkline7D = sparkline7D;
    }

    /**
     * Getter for CurrentPrice.
     * Current price in target currency
     * @return Returns the Map of String, Double
     */
    @JsonGetter("current_price")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, Double> getCurrentPrice() {
        return currentPrice;
    }

    /**
     * Setter for CurrentPrice.
     * Current price in target currency
     * @param currentPrice Value for Map of String, Double
     */
    @JsonSetter("current_price")
    public void setCurrentPrice(Map<String, Double> currentPrice) {
        this.currentPrice = currentPrice;
    }

    /**
     * Internal Getter for TotalValueLocked.
     * Total value locked
     * @return Returns the Internal Double
     */
    @JsonGetter("total_value_locked")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Double> internalGetTotalValueLocked() {
        return this.totalValueLocked;
    }

    /**
     * Getter for TotalValueLocked.
     * Total value locked
     * @return Returns the Double
     */
    public Double getTotalValueLocked() {
        return OptionalNullable.getFrom(totalValueLocked);
    }

    /**
     * Setter for TotalValueLocked.
     * Total value locked
     * @param totalValueLocked Value for Double
     */
    @JsonSetter("total_value_locked")
    public void setTotalValueLocked(Double totalValueLocked) {
        this.totalValueLocked = OptionalNullable.of(totalValueLocked);
    }

    /**
     * UnSetter for TotalValueLocked.
     * Total value locked
     */
    public void unsetTotalValueLocked() {
        totalValueLocked = null;
    }

    /**
     * Internal Getter for McapToTvlRatio.
     * Market cap to TVL ratio
     * @return Returns the Internal Double
     */
    @JsonGetter("mcap_to_tvl_ratio")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Double> internalGetMcapToTvlRatio() {
        return this.mcapToTvlRatio;
    }

    /**
     * Getter for McapToTvlRatio.
     * Market cap to TVL ratio
     * @return Returns the Double
     */
    public Double getMcapToTvlRatio() {
        return OptionalNullable.getFrom(mcapToTvlRatio);
    }

    /**
     * Setter for McapToTvlRatio.
     * Market cap to TVL ratio
     * @param mcapToTvlRatio Value for Double
     */
    @JsonSetter("mcap_to_tvl_ratio")
    public void setMcapToTvlRatio(Double mcapToTvlRatio) {
        this.mcapToTvlRatio = OptionalNullable.of(mcapToTvlRatio);
    }

    /**
     * UnSetter for McapToTvlRatio.
     * Market cap to TVL ratio
     */
    public void unsetMcapToTvlRatio() {
        mcapToTvlRatio = null;
    }

    /**
     * Internal Getter for FdvToTvlRatio.
     * FDV to TVL ratio
     * @return Returns the Internal Double
     */
    @JsonGetter("fdv_to_tvl_ratio")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Double> internalGetFdvToTvlRatio() {
        return this.fdvToTvlRatio;
    }

    /**
     * Getter for FdvToTvlRatio.
     * FDV to TVL ratio
     * @return Returns the Double
     */
    public Double getFdvToTvlRatio() {
        return OptionalNullable.getFrom(fdvToTvlRatio);
    }

    /**
     * Setter for FdvToTvlRatio.
     * FDV to TVL ratio
     * @param fdvToTvlRatio Value for Double
     */
    @JsonSetter("fdv_to_tvl_ratio")
    public void setFdvToTvlRatio(Double fdvToTvlRatio) {
        this.fdvToTvlRatio = OptionalNullable.of(fdvToTvlRatio);
    }

    /**
     * UnSetter for FdvToTvlRatio.
     * FDV to TVL ratio
     */
    public void unsetFdvToTvlRatio() {
        fdvToTvlRatio = null;
    }

    /**
     * Internal Getter for Roi.
     * Return on investment
     * @return Returns the Internal Roi
     */
    @JsonGetter("roi")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Roi> internalGetRoi() {
        return this.roi;
    }

    /**
     * Getter for Roi.
     * Return on investment
     * @return Returns the Roi
     */
    public Roi getRoi() {
        return OptionalNullable.getFrom(roi);
    }

    /**
     * Setter for Roi.
     * Return on investment
     * @param roi Value for Roi
     */
    @JsonSetter("roi")
    public void setRoi(Roi roi) {
        this.roi = OptionalNullable.of(roi);
    }

    /**
     * UnSetter for Roi.
     * Return on investment
     */
    public void unsetRoi() {
        roi = null;
    }

    /**
     * Getter for Ath.
     * All-time high in target currency
     * @return Returns the Map of String, Double
     */
    @JsonGetter("ath")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, Double> getAth() {
        return ath;
    }

    /**
     * Setter for Ath.
     * All-time high in target currency
     * @param ath Value for Map of String, Double
     */
    @JsonSetter("ath")
    public void setAth(Map<String, Double> ath) {
        this.ath = ath;
    }

    /**
     * Getter for AthChangePercentage.
     * All-time high change percentage
     * @return Returns the Map of String, Double
     */
    @JsonGetter("ath_change_percentage")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, Double> getAthChangePercentage() {
        return athChangePercentage;
    }

    /**
     * Setter for AthChangePercentage.
     * All-time high change percentage
     * @param athChangePercentage Value for Map of String, Double
     */
    @JsonSetter("ath_change_percentage")
    public void setAthChangePercentage(Map<String, Double> athChangePercentage) {
        this.athChangePercentage = athChangePercentage;
    }

    /**
     * Getter for AthDate.
     * All-time high date
     * @return Returns the Map of String, String
     */
    @JsonGetter("ath_date")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, String> getAthDate() {
        return athDate;
    }

    /**
     * Setter for AthDate.
     * All-time high date
     * @param athDate Value for Map of String, String
     */
    @JsonSetter("ath_date")
    public void setAthDate(Map<String, String> athDate) {
        this.athDate = athDate;
    }

    /**
     * Getter for Atl.
     * All-time low in target currency
     * @return Returns the Map of String, Double
     */
    @JsonGetter("atl")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, Double> getAtl() {
        return atl;
    }

    /**
     * Setter for Atl.
     * All-time low in target currency
     * @param atl Value for Map of String, Double
     */
    @JsonSetter("atl")
    public void setAtl(Map<String, Double> atl) {
        this.atl = atl;
    }

    /**
     * Getter for AtlChangePercentage.
     * All-time low change percentage
     * @return Returns the Map of String, Double
     */
    @JsonGetter("atl_change_percentage")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, Double> getAtlChangePercentage() {
        return atlChangePercentage;
    }

    /**
     * Setter for AtlChangePercentage.
     * All-time low change percentage
     * @param atlChangePercentage Value for Map of String, Double
     */
    @JsonSetter("atl_change_percentage")
    public void setAtlChangePercentage(Map<String, Double> atlChangePercentage) {
        this.atlChangePercentage = atlChangePercentage;
    }

    /**
     * Getter for AtlDate.
     * All-time low date
     * @return Returns the Map of String, String
     */
    @JsonGetter("atl_date")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, String> getAtlDate() {
        return atlDate;
    }

    /**
     * Setter for AtlDate.
     * All-time low date
     * @param atlDate Value for Map of String, String
     */
    @JsonSetter("atl_date")
    public void setAtlDate(Map<String, String> atlDate) {
        this.atlDate = atlDate;
    }

    /**
     * Getter for MarketCap.
     * Market cap in target currency
     * @return Returns the Map of String, Double
     */
    @JsonGetter("market_cap")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, Double> getMarketCap() {
        return marketCap;
    }

    /**
     * Setter for MarketCap.
     * Market cap in target currency
     * @param marketCap Value for Map of String, Double
     */
    @JsonSetter("market_cap")
    public void setMarketCap(Map<String, Double> marketCap) {
        this.marketCap = marketCap;
    }

    /**
     * Getter for FullyDilutedValuation.
     * Fully diluted valuation in target currency
     * @return Returns the Map of String, Double
     */
    @JsonGetter("fully_diluted_valuation")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, Double> getFullyDilutedValuation() {
        return fullyDilutedValuation;
    }

    /**
     * Setter for FullyDilutedValuation.
     * Fully diluted valuation in target currency
     * @param fullyDilutedValuation Value for Map of String, Double
     */
    @JsonSetter("fully_diluted_valuation")
    public void setFullyDilutedValuation(Map<String, Double> fullyDilutedValuation) {
        this.fullyDilutedValuation = fullyDilutedValuation;
    }

    /**
     * Getter for MarketCapFdvRatio.
     * Market cap to FDV ratio
     * @return Returns the Double
     */
    @JsonGetter("market_cap_fdv_ratio")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getMarketCapFdvRatio() {
        return marketCapFdvRatio;
    }

    /**
     * Setter for MarketCapFdvRatio.
     * Market cap to FDV ratio
     * @param marketCapFdvRatio Value for Double
     */
    @JsonSetter("market_cap_fdv_ratio")
    public void setMarketCapFdvRatio(Double marketCapFdvRatio) {
        this.marketCapFdvRatio = marketCapFdvRatio;
    }

    /**
     * Internal Getter for MarketCapRank.
     * Market cap rank
     * @return Returns the Internal Integer
     */
    @JsonGetter("market_cap_rank")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Integer> internalGetMarketCapRank() {
        return this.marketCapRank;
    }

    /**
     * Getter for MarketCapRank.
     * Market cap rank
     * @return Returns the Integer
     */
    public Integer getMarketCapRank() {
        return OptionalNullable.getFrom(marketCapRank);
    }

    /**
     * Setter for MarketCapRank.
     * Market cap rank
     * @param marketCapRank Value for Integer
     */
    @JsonSetter("market_cap_rank")
    public void setMarketCapRank(Integer marketCapRank) {
        this.marketCapRank = OptionalNullable.of(marketCapRank);
    }

    /**
     * UnSetter for MarketCapRank.
     * Market cap rank
     */
    public void unsetMarketCapRank() {
        marketCapRank = null;
    }

    /**
     * Internal Getter for OutstandingTokenValueUsd.
     * Outstanding token value in USD
     * @return Returns the Internal Double
     */
    @JsonGetter("outstanding_token_value_usd")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Double> internalGetOutstandingTokenValueUsd() {
        return this.outstandingTokenValueUsd;
    }

    /**
     * Getter for OutstandingTokenValueUsd.
     * Outstanding token value in USD
     * @return Returns the Double
     */
    public Double getOutstandingTokenValueUsd() {
        return OptionalNullable.getFrom(outstandingTokenValueUsd);
    }

    /**
     * Setter for OutstandingTokenValueUsd.
     * Outstanding token value in USD
     * @param outstandingTokenValueUsd Value for Double
     */
    @JsonSetter("outstanding_token_value_usd")
    public void setOutstandingTokenValueUsd(Double outstandingTokenValueUsd) {
        this.outstandingTokenValueUsd = OptionalNullable.of(outstandingTokenValueUsd);
    }

    /**
     * UnSetter for OutstandingTokenValueUsd.
     * Outstanding token value in USD
     */
    public void unsetOutstandingTokenValueUsd() {
        outstandingTokenValueUsd = null;
    }

    /**
     * Internal Getter for MarketCapRankWithRehypothecated.
     * Market cap rank including rehypothecated tokens
     * @return Returns the Internal Integer
     */
    @JsonGetter("market_cap_rank_with_rehypothecated")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Integer> internalGetMarketCapRankWithRehypothecated() {
        return this.marketCapRankWithRehypothecated;
    }

    /**
     * Getter for MarketCapRankWithRehypothecated.
     * Market cap rank including rehypothecated tokens
     * @return Returns the Integer
     */
    public Integer getMarketCapRankWithRehypothecated() {
        return OptionalNullable.getFrom(marketCapRankWithRehypothecated);
    }

    /**
     * Setter for MarketCapRankWithRehypothecated.
     * Market cap rank including rehypothecated tokens
     * @param marketCapRankWithRehypothecated Value for Integer
     */
    @JsonSetter("market_cap_rank_with_rehypothecated")
    public void setMarketCapRankWithRehypothecated(Integer marketCapRankWithRehypothecated) {
        this.marketCapRankWithRehypothecated = OptionalNullable.of(marketCapRankWithRehypothecated);
    }

    /**
     * UnSetter for MarketCapRankWithRehypothecated.
     * Market cap rank including rehypothecated tokens
     */
    public void unsetMarketCapRankWithRehypothecated() {
        marketCapRankWithRehypothecated = null;
    }

    /**
     * Getter for TotalVolume.
     * Total trading volume in target currency
     * @return Returns the Map of String, Double
     */
    @JsonGetter("total_volume")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, Double> getTotalVolume() {
        return totalVolume;
    }

    /**
     * Setter for TotalVolume.
     * Total trading volume in target currency
     * @param totalVolume Value for Map of String, Double
     */
    @JsonSetter("total_volume")
    public void setTotalVolume(Map<String, Double> totalVolume) {
        this.totalVolume = totalVolume;
    }

    /**
     * Getter for High24H.
     * 24h price high in target currency
     * @return Returns the Map of String, Double
     */
    @JsonGetter("high_24h")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, Double> getHigh24H() {
        return high24H;
    }

    /**
     * Setter for High24H.
     * 24h price high in target currency
     * @param high24H Value for Map of String, Double
     */
    @JsonSetter("high_24h")
    public void setHigh24H(Map<String, Double> high24H) {
        this.high24H = high24H;
    }

    /**
     * Getter for Low24H.
     * 24h price low in target currency
     * @return Returns the Map of String, Double
     */
    @JsonGetter("low_24h")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, Double> getLow24H() {
        return low24H;
    }

    /**
     * Setter for Low24H.
     * 24h price low in target currency
     * @param low24H Value for Map of String, Double
     */
    @JsonSetter("low_24h")
    public void setLow24H(Map<String, Double> low24H) {
        this.low24H = low24H;
    }

    /**
     * Getter for PriceChange24H.
     * 24h price change in target currency
     * @return Returns the Double
     */
    @JsonGetter("price_change_24h")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getPriceChange24H() {
        return priceChange24H;
    }

    /**
     * Setter for PriceChange24H.
     * 24h price change in target currency
     * @param priceChange24H Value for Double
     */
    @JsonSetter("price_change_24h")
    public void setPriceChange24H(Double priceChange24H) {
        this.priceChange24H = priceChange24H;
    }

    /**
     * Getter for PriceChangePercentage24H.
     * 24h price change percentage
     * @return Returns the Double
     */
    @JsonGetter("price_change_percentage_24h")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getPriceChangePercentage24H() {
        return priceChangePercentage24H;
    }

    /**
     * Setter for PriceChangePercentage24H.
     * 24h price change percentage
     * @param priceChangePercentage24H Value for Double
     */
    @JsonSetter("price_change_percentage_24h")
    public void setPriceChangePercentage24H(Double priceChangePercentage24H) {
        this.priceChangePercentage24H = priceChangePercentage24H;
    }

    /**
     * Getter for PriceChangePercentage7D.
     * 7d price change percentage
     * @return Returns the Double
     */
    @JsonGetter("price_change_percentage_7d")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getPriceChangePercentage7D() {
        return priceChangePercentage7D;
    }

    /**
     * Setter for PriceChangePercentage7D.
     * 7d price change percentage
     * @param priceChangePercentage7D Value for Double
     */
    @JsonSetter("price_change_percentage_7d")
    public void setPriceChangePercentage7D(Double priceChangePercentage7D) {
        this.priceChangePercentage7D = priceChangePercentage7D;
    }

    /**
     * Getter for PriceChangePercentage14D.
     * 14d price change percentage
     * @return Returns the Double
     */
    @JsonGetter("price_change_percentage_14d")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getPriceChangePercentage14D() {
        return priceChangePercentage14D;
    }

    /**
     * Setter for PriceChangePercentage14D.
     * 14d price change percentage
     * @param priceChangePercentage14D Value for Double
     */
    @JsonSetter("price_change_percentage_14d")
    public void setPriceChangePercentage14D(Double priceChangePercentage14D) {
        this.priceChangePercentage14D = priceChangePercentage14D;
    }

    /**
     * Getter for PriceChangePercentage30D.
     * 30d price change percentage
     * @return Returns the Double
     */
    @JsonGetter("price_change_percentage_30d")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getPriceChangePercentage30D() {
        return priceChangePercentage30D;
    }

    /**
     * Setter for PriceChangePercentage30D.
     * 30d price change percentage
     * @param priceChangePercentage30D Value for Double
     */
    @JsonSetter("price_change_percentage_30d")
    public void setPriceChangePercentage30D(Double priceChangePercentage30D) {
        this.priceChangePercentage30D = priceChangePercentage30D;
    }

    /**
     * Getter for PriceChangePercentage60D.
     * 60d price change percentage
     * @return Returns the Double
     */
    @JsonGetter("price_change_percentage_60d")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getPriceChangePercentage60D() {
        return priceChangePercentage60D;
    }

    /**
     * Setter for PriceChangePercentage60D.
     * 60d price change percentage
     * @param priceChangePercentage60D Value for Double
     */
    @JsonSetter("price_change_percentage_60d")
    public void setPriceChangePercentage60D(Double priceChangePercentage60D) {
        this.priceChangePercentage60D = priceChangePercentage60D;
    }

    /**
     * Getter for PriceChangePercentage200D.
     * 200d price change percentage
     * @return Returns the Double
     */
    @JsonGetter("price_change_percentage_200d")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getPriceChangePercentage200D() {
        return priceChangePercentage200D;
    }

    /**
     * Setter for PriceChangePercentage200D.
     * 200d price change percentage
     * @param priceChangePercentage200D Value for Double
     */
    @JsonSetter("price_change_percentage_200d")
    public void setPriceChangePercentage200D(Double priceChangePercentage200D) {
        this.priceChangePercentage200D = priceChangePercentage200D;
    }

    /**
     * Getter for PriceChangePercentage1Y.
     * 1y price change percentage
     * @return Returns the Double
     */
    @JsonGetter("price_change_percentage_1y")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getPriceChangePercentage1Y() {
        return priceChangePercentage1Y;
    }

    /**
     * Setter for PriceChangePercentage1Y.
     * 1y price change percentage
     * @param priceChangePercentage1Y Value for Double
     */
    @JsonSetter("price_change_percentage_1y")
    public void setPriceChangePercentage1Y(Double priceChangePercentage1Y) {
        this.priceChangePercentage1Y = priceChangePercentage1Y;
    }

    /**
     * Getter for MarketCapChange24H.
     * 24h market cap change in target currency
     * @return Returns the Double
     */
    @JsonGetter("market_cap_change_24h")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getMarketCapChange24H() {
        return marketCapChange24H;
    }

    /**
     * Setter for MarketCapChange24H.
     * 24h market cap change in target currency
     * @param marketCapChange24H Value for Double
     */
    @JsonSetter("market_cap_change_24h")
    public void setMarketCapChange24H(Double marketCapChange24H) {
        this.marketCapChange24H = marketCapChange24H;
    }

    /**
     * Getter for MarketCapChangePercentage24H.
     * 24h market cap change percentage
     * @return Returns the Double
     */
    @JsonGetter("market_cap_change_percentage_24h")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getMarketCapChangePercentage24H() {
        return marketCapChangePercentage24H;
    }

    /**
     * Setter for MarketCapChangePercentage24H.
     * 24h market cap change percentage
     * @param marketCapChangePercentage24H Value for Double
     */
    @JsonSetter("market_cap_change_percentage_24h")
    public void setMarketCapChangePercentage24H(Double marketCapChangePercentage24H) {
        this.marketCapChangePercentage24H = marketCapChangePercentage24H;
    }

    /**
     * Getter for PriceChange24HInCurrency.
     * 24h price change in target currency
     * @return Returns the Map of String, Double
     */
    @JsonGetter("price_change_24h_in_currency")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, Double> getPriceChange24HInCurrency() {
        return priceChange24HInCurrency;
    }

    /**
     * Setter for PriceChange24HInCurrency.
     * 24h price change in target currency
     * @param priceChange24HInCurrency Value for Map of String, Double
     */
    @JsonSetter("price_change_24h_in_currency")
    public void setPriceChange24HInCurrency(Map<String, Double> priceChange24HInCurrency) {
        this.priceChange24HInCurrency = priceChange24HInCurrency;
    }

    /**
     * Getter for PriceChangePercentage1HInCurrency.
     * 1h price change percentage per currency
     * @return Returns the Map of String, Double
     */
    @JsonGetter("price_change_percentage_1h_in_currency")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, Double> getPriceChangePercentage1HInCurrency() {
        return priceChangePercentage1HInCurrency;
    }

    /**
     * Setter for PriceChangePercentage1HInCurrency.
     * 1h price change percentage per currency
     * @param priceChangePercentage1HInCurrency Value for Map of String, Double
     */
    @JsonSetter("price_change_percentage_1h_in_currency")
    public void setPriceChangePercentage1HInCurrency(Map<String, Double> priceChangePercentage1HInCurrency) {
        this.priceChangePercentage1HInCurrency = priceChangePercentage1HInCurrency;
    }

    /**
     * Getter for PriceChangePercentage24HInCurrency.
     * 24h price change percentage per currency
     * @return Returns the Map of String, Double
     */
    @JsonGetter("price_change_percentage_24h_in_currency")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, Double> getPriceChangePercentage24HInCurrency() {
        return priceChangePercentage24HInCurrency;
    }

    /**
     * Setter for PriceChangePercentage24HInCurrency.
     * 24h price change percentage per currency
     * @param priceChangePercentage24HInCurrency Value for Map of String, Double
     */
    @JsonSetter("price_change_percentage_24h_in_currency")
    public void setPriceChangePercentage24HInCurrency(Map<String, Double> priceChangePercentage24HInCurrency) {
        this.priceChangePercentage24HInCurrency = priceChangePercentage24HInCurrency;
    }

    /**
     * Getter for PriceChangePercentage7DInCurrency.
     * 7d price change percentage per currency
     * @return Returns the Map of String, Double
     */
    @JsonGetter("price_change_percentage_7d_in_currency")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, Double> getPriceChangePercentage7DInCurrency() {
        return priceChangePercentage7DInCurrency;
    }

    /**
     * Setter for PriceChangePercentage7DInCurrency.
     * 7d price change percentage per currency
     * @param priceChangePercentage7DInCurrency Value for Map of String, Double
     */
    @JsonSetter("price_change_percentage_7d_in_currency")
    public void setPriceChangePercentage7DInCurrency(Map<String, Double> priceChangePercentage7DInCurrency) {
        this.priceChangePercentage7DInCurrency = priceChangePercentage7DInCurrency;
    }

    /**
     * Getter for PriceChangePercentage14DInCurrency.
     * 14d price change percentage per currency
     * @return Returns the Map of String, Double
     */
    @JsonGetter("price_change_percentage_14d_in_currency")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, Double> getPriceChangePercentage14DInCurrency() {
        return priceChangePercentage14DInCurrency;
    }

    /**
     * Setter for PriceChangePercentage14DInCurrency.
     * 14d price change percentage per currency
     * @param priceChangePercentage14DInCurrency Value for Map of String, Double
     */
    @JsonSetter("price_change_percentage_14d_in_currency")
    public void setPriceChangePercentage14DInCurrency(Map<String, Double> priceChangePercentage14DInCurrency) {
        this.priceChangePercentage14DInCurrency = priceChangePercentage14DInCurrency;
    }

    /**
     * Getter for PriceChangePercentage30DInCurrency.
     * 30d price change percentage per currency
     * @return Returns the Map of String, Double
     */
    @JsonGetter("price_change_percentage_30d_in_currency")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, Double> getPriceChangePercentage30DInCurrency() {
        return priceChangePercentage30DInCurrency;
    }

    /**
     * Setter for PriceChangePercentage30DInCurrency.
     * 30d price change percentage per currency
     * @param priceChangePercentage30DInCurrency Value for Map of String, Double
     */
    @JsonSetter("price_change_percentage_30d_in_currency")
    public void setPriceChangePercentage30DInCurrency(Map<String, Double> priceChangePercentage30DInCurrency) {
        this.priceChangePercentage30DInCurrency = priceChangePercentage30DInCurrency;
    }

    /**
     * Getter for PriceChangePercentage60DInCurrency.
     * 60d price change percentage per currency
     * @return Returns the Map of String, Double
     */
    @JsonGetter("price_change_percentage_60d_in_currency")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, Double> getPriceChangePercentage60DInCurrency() {
        return priceChangePercentage60DInCurrency;
    }

    /**
     * Setter for PriceChangePercentage60DInCurrency.
     * 60d price change percentage per currency
     * @param priceChangePercentage60DInCurrency Value for Map of String, Double
     */
    @JsonSetter("price_change_percentage_60d_in_currency")
    public void setPriceChangePercentage60DInCurrency(Map<String, Double> priceChangePercentage60DInCurrency) {
        this.priceChangePercentage60DInCurrency = priceChangePercentage60DInCurrency;
    }

    /**
     * Getter for PriceChangePercentage200DInCurrency.
     * 200d price change percentage per currency
     * @return Returns the Map of String, Double
     */
    @JsonGetter("price_change_percentage_200d_in_currency")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, Double> getPriceChangePercentage200DInCurrency() {
        return priceChangePercentage200DInCurrency;
    }

    /**
     * Setter for PriceChangePercentage200DInCurrency.
     * 200d price change percentage per currency
     * @param priceChangePercentage200DInCurrency Value for Map of String, Double
     */
    @JsonSetter("price_change_percentage_200d_in_currency")
    public void setPriceChangePercentage200DInCurrency(Map<String, Double> priceChangePercentage200DInCurrency) {
        this.priceChangePercentage200DInCurrency = priceChangePercentage200DInCurrency;
    }

    /**
     * Getter for PriceChangePercentage1YInCurrency.
     * 1y price change percentage per currency
     * @return Returns the Map of String, Double
     */
    @JsonGetter("price_change_percentage_1y_in_currency")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, Double> getPriceChangePercentage1YInCurrency() {
        return priceChangePercentage1YInCurrency;
    }

    /**
     * Setter for PriceChangePercentage1YInCurrency.
     * 1y price change percentage per currency
     * @param priceChangePercentage1YInCurrency Value for Map of String, Double
     */
    @JsonSetter("price_change_percentage_1y_in_currency")
    public void setPriceChangePercentage1YInCurrency(Map<String, Double> priceChangePercentage1YInCurrency) {
        this.priceChangePercentage1YInCurrency = priceChangePercentage1YInCurrency;
    }

    /**
     * Getter for MarketCapChange24HInCurrency.
     * 24h market cap change in target currency
     * @return Returns the Map of String, Double
     */
    @JsonGetter("market_cap_change_24h_in_currency")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, Double> getMarketCapChange24HInCurrency() {
        return marketCapChange24HInCurrency;
    }

    /**
     * Setter for MarketCapChange24HInCurrency.
     * 24h market cap change in target currency
     * @param marketCapChange24HInCurrency Value for Map of String, Double
     */
    @JsonSetter("market_cap_change_24h_in_currency")
    public void setMarketCapChange24HInCurrency(Map<String, Double> marketCapChange24HInCurrency) {
        this.marketCapChange24HInCurrency = marketCapChange24HInCurrency;
    }

    /**
     * Getter for MarketCapChangePercentage24HInCurrency.
     * 24h market cap change percentage per currency
     * @return Returns the Map of String, Double
     */
    @JsonGetter("market_cap_change_percentage_24h_in_currency")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, Double> getMarketCapChangePercentage24HInCurrency() {
        return marketCapChangePercentage24HInCurrency;
    }

    /**
     * Setter for MarketCapChangePercentage24HInCurrency.
     * 24h market cap change percentage per currency
     * @param marketCapChangePercentage24HInCurrency Value for Map of String, Double
     */
    @JsonSetter("market_cap_change_percentage_24h_in_currency")
    public void setMarketCapChangePercentage24HInCurrency(Map<String, Double> marketCapChangePercentage24HInCurrency) {
        this.marketCapChangePercentage24HInCurrency = marketCapChangePercentage24HInCurrency;
    }

    /**
     * Getter for TotalSupply.
     * Total supply
     * @return Returns the Double
     */
    @JsonGetter("total_supply")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getTotalSupply() {
        return totalSupply;
    }

    /**
     * Setter for TotalSupply.
     * Total supply
     * @param totalSupply Value for Double
     */
    @JsonSetter("total_supply")
    public void setTotalSupply(Double totalSupply) {
        this.totalSupply = totalSupply;
    }

    /**
     * Internal Getter for MaxSupply.
     * Max supply
     * @return Returns the Internal Double
     */
    @JsonGetter("max_supply")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Double> internalGetMaxSupply() {
        return this.maxSupply;
    }

    /**
     * Getter for MaxSupply.
     * Max supply
     * @return Returns the Double
     */
    public Double getMaxSupply() {
        return OptionalNullable.getFrom(maxSupply);
    }

    /**
     * Setter for MaxSupply.
     * Max supply
     * @param maxSupply Value for Double
     */
    @JsonSetter("max_supply")
    public void setMaxSupply(Double maxSupply) {
        this.maxSupply = OptionalNullable.of(maxSupply);
    }

    /**
     * UnSetter for MaxSupply.
     * Max supply
     */
    public void unsetMaxSupply() {
        maxSupply = null;
    }

    /**
     * Getter for MaxSupplyInfinite.
     * Max supply infinite
     * @return Returns the Boolean
     */
    @JsonGetter("max_supply_infinite")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getMaxSupplyInfinite() {
        return maxSupplyInfinite;
    }

    /**
     * Setter for MaxSupplyInfinite.
     * Max supply infinite
     * @param maxSupplyInfinite Value for Boolean
     */
    @JsonSetter("max_supply_infinite")
    public void setMaxSupplyInfinite(Boolean maxSupplyInfinite) {
        this.maxSupplyInfinite = maxSupplyInfinite;
    }

    /**
     * Getter for CirculatingSupply.
     * Circulating supply
     * @return Returns the Double
     */
    @JsonGetter("circulating_supply")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getCirculatingSupply() {
        return circulatingSupply;
    }

    /**
     * Setter for CirculatingSupply.
     * Circulating supply
     * @param circulatingSupply Value for Double
     */
    @JsonSetter("circulating_supply")
    public void setCirculatingSupply(Double circulatingSupply) {
        this.circulatingSupply = circulatingSupply;
    }

    /**
     * Internal Getter for OutstandingSupply.
     * Tokens outstanding in the market
     * @return Returns the Internal Double
     */
    @JsonGetter("outstanding_supply")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Double> internalGetOutstandingSupply() {
        return this.outstandingSupply;
    }

    /**
     * Getter for OutstandingSupply.
     * Tokens outstanding in the market
     * @return Returns the Double
     */
    public Double getOutstandingSupply() {
        return OptionalNullable.getFrom(outstandingSupply);
    }

    /**
     * Setter for OutstandingSupply.
     * Tokens outstanding in the market
     * @param outstandingSupply Value for Double
     */
    @JsonSetter("outstanding_supply")
    public void setOutstandingSupply(Double outstandingSupply) {
        this.outstandingSupply = OptionalNullable.of(outstandingSupply);
    }

    /**
     * UnSetter for OutstandingSupply.
     * Tokens outstanding in the market
     */
    public void unsetOutstandingSupply() {
        outstandingSupply = null;
    }

    /**
     * Getter for LastUpdated.
     * Market data last updated timestamp
     * @return Returns the String
     */
    @JsonGetter("last_updated")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLastUpdated() {
        return lastUpdated;
    }

    /**
     * Setter for LastUpdated.
     * Market data last updated timestamp
     * @param lastUpdated Value for String
     */
    @JsonSetter("last_updated")
    public void setLastUpdated(String lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * Getter for Sparkline7D.
     * Sparkline 7-day price data
     * @return Returns the List of Double
     */
    @JsonGetter("sparkline_7d")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Double> getSparkline7D() {
        return sparkline7D;
    }

    /**
     * Setter for Sparkline7D.
     * Sparkline 7-day price data
     * @param sparkline7D Value for List of Double
     */
    @JsonSetter("sparkline_7d")
    public void setSparkline7D(List<Double> sparkline7D) {
        this.sparkline7D = sparkline7D;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this MarketData1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MarketData1 [" + "currentPrice=" + currentPrice + ", totalValueLocked="
                + totalValueLocked + ", mcapToTvlRatio=" + mcapToTvlRatio + ", fdvToTvlRatio="
                + fdvToTvlRatio + ", roi=" + roi + ", ath=" + ath + ", athChangePercentage="
                + athChangePercentage + ", athDate=" + athDate + ", atl=" + atl
                + ", atlChangePercentage=" + atlChangePercentage + ", atlDate=" + atlDate
                + ", marketCap=" + marketCap + ", fullyDilutedValuation=" + fullyDilutedValuation
                + ", marketCapFdvRatio=" + marketCapFdvRatio + ", marketCapRank=" + marketCapRank
                + ", outstandingTokenValueUsd=" + outstandingTokenValueUsd
                + ", marketCapRankWithRehypothecated=" + marketCapRankWithRehypothecated
                + ", totalVolume=" + totalVolume + ", high24H=" + high24H + ", low24H=" + low24H
                + ", priceChange24H=" + priceChange24H + ", priceChangePercentage24H="
                + priceChangePercentage24H + ", priceChangePercentage7D=" + priceChangePercentage7D
                + ", priceChangePercentage14D=" + priceChangePercentage14D
                + ", priceChangePercentage30D=" + priceChangePercentage30D
                + ", priceChangePercentage60D=" + priceChangePercentage60D
                + ", priceChangePercentage200D=" + priceChangePercentage200D
                + ", priceChangePercentage1Y=" + priceChangePercentage1Y + ", marketCapChange24H="
                + marketCapChange24H + ", marketCapChangePercentage24H="
                + marketCapChangePercentage24H + ", priceChange24HInCurrency="
                + priceChange24HInCurrency + ", priceChangePercentage1HInCurrency="
                + priceChangePercentage1HInCurrency + ", priceChangePercentage24HInCurrency="
                + priceChangePercentage24HInCurrency + ", priceChangePercentage7DInCurrency="
                + priceChangePercentage7DInCurrency + ", priceChangePercentage14DInCurrency="
                + priceChangePercentage14DInCurrency + ", priceChangePercentage30DInCurrency="
                + priceChangePercentage30DInCurrency + ", priceChangePercentage60DInCurrency="
                + priceChangePercentage60DInCurrency + ", priceChangePercentage200DInCurrency="
                + priceChangePercentage200DInCurrency + ", priceChangePercentage1YInCurrency="
                + priceChangePercentage1YInCurrency + ", marketCapChange24HInCurrency="
                + marketCapChange24HInCurrency + ", marketCapChangePercentage24HInCurrency="
                + marketCapChangePercentage24HInCurrency + ", totalSupply=" + totalSupply
                + ", maxSupply=" + maxSupply + ", maxSupplyInfinite=" + maxSupplyInfinite
                + ", circulatingSupply=" + circulatingSupply + ", outstandingSupply="
                + outstandingSupply + ", lastUpdated=" + lastUpdated + ", sparkline7D="
                + sparkline7D + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link MarketData1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MarketData1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .currentPrice(getCurrentPrice())
                .ath(getAth())
                .athChangePercentage(getAthChangePercentage())
                .athDate(getAthDate())
                .atl(getAtl())
                .atlChangePercentage(getAtlChangePercentage())
                .atlDate(getAtlDate())
                .marketCap(getMarketCap())
                .fullyDilutedValuation(getFullyDilutedValuation())
                .marketCapFdvRatio(getMarketCapFdvRatio())
                .totalVolume(getTotalVolume())
                .high24H(getHigh24H())
                .low24H(getLow24H())
                .priceChange24H(getPriceChange24H())
                .priceChangePercentage24H(getPriceChangePercentage24H())
                .priceChangePercentage7D(getPriceChangePercentage7D())
                .priceChangePercentage14D(getPriceChangePercentage14D())
                .priceChangePercentage30D(getPriceChangePercentage30D())
                .priceChangePercentage60D(getPriceChangePercentage60D())
                .priceChangePercentage200D(getPriceChangePercentage200D())
                .priceChangePercentage1Y(getPriceChangePercentage1Y())
                .marketCapChange24H(getMarketCapChange24H())
                .marketCapChangePercentage24H(getMarketCapChangePercentage24H())
                .priceChange24HInCurrency(getPriceChange24HInCurrency())
                .priceChangePercentage1HInCurrency(getPriceChangePercentage1HInCurrency())
                .priceChangePercentage24HInCurrency(getPriceChangePercentage24HInCurrency())
                .priceChangePercentage7DInCurrency(getPriceChangePercentage7DInCurrency())
                .priceChangePercentage14DInCurrency(getPriceChangePercentage14DInCurrency())
                .priceChangePercentage30DInCurrency(getPriceChangePercentage30DInCurrency())
                .priceChangePercentage60DInCurrency(getPriceChangePercentage60DInCurrency())
                .priceChangePercentage200DInCurrency(getPriceChangePercentage200DInCurrency())
                .priceChangePercentage1YInCurrency(getPriceChangePercentage1YInCurrency())
                .marketCapChange24HInCurrency(getMarketCapChange24HInCurrency())
                .marketCapChangePercentage24HInCurrency(getMarketCapChangePercentage24HInCurrency())
                .totalSupply(getTotalSupply())
                .maxSupplyInfinite(getMaxSupplyInfinite())
                .circulatingSupply(getCirculatingSupply())
                .lastUpdated(getLastUpdated())
                .sparkline7D(getSparkline7D());
        builder.totalValueLocked = internalGetTotalValueLocked();
        builder.mcapToTvlRatio = internalGetMcapToTvlRatio();
        builder.fdvToTvlRatio = internalGetFdvToTvlRatio();
        builder.roi = internalGetRoi();
        builder.marketCapRank = internalGetMarketCapRank();
        builder.outstandingTokenValueUsd = internalGetOutstandingTokenValueUsd();
        builder.marketCapRankWithRehypothecated = internalGetMarketCapRankWithRehypothecated();
        builder.maxSupply = internalGetMaxSupply();
        builder.outstandingSupply = internalGetOutstandingSupply();
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link MarketData1}.
     */
    public static class Builder {
        private Map<String, Double> currentPrice;
        private OptionalNullable<Double> totalValueLocked;
        private OptionalNullable<Double> mcapToTvlRatio;
        private OptionalNullable<Double> fdvToTvlRatio;
        private OptionalNullable<Roi> roi;
        private Map<String, Double> ath;
        private Map<String, Double> athChangePercentage;
        private Map<String, String> athDate;
        private Map<String, Double> atl;
        private Map<String, Double> atlChangePercentage;
        private Map<String, String> atlDate;
        private Map<String, Double> marketCap;
        private Map<String, Double> fullyDilutedValuation;
        private Double marketCapFdvRatio;
        private OptionalNullable<Integer> marketCapRank;
        private OptionalNullable<Double> outstandingTokenValueUsd;
        private OptionalNullable<Integer> marketCapRankWithRehypothecated;
        private Map<String, Double> totalVolume;
        private Map<String, Double> high24H;
        private Map<String, Double> low24H;
        private Double priceChange24H;
        private Double priceChangePercentage24H;
        private Double priceChangePercentage7D;
        private Double priceChangePercentage14D;
        private Double priceChangePercentage30D;
        private Double priceChangePercentage60D;
        private Double priceChangePercentage200D;
        private Double priceChangePercentage1Y;
        private Double marketCapChange24H;
        private Double marketCapChangePercentage24H;
        private Map<String, Double> priceChange24HInCurrency;
        private Map<String, Double> priceChangePercentage1HInCurrency;
        private Map<String, Double> priceChangePercentage24HInCurrency;
        private Map<String, Double> priceChangePercentage7DInCurrency;
        private Map<String, Double> priceChangePercentage14DInCurrency;
        private Map<String, Double> priceChangePercentage30DInCurrency;
        private Map<String, Double> priceChangePercentage60DInCurrency;
        private Map<String, Double> priceChangePercentage200DInCurrency;
        private Map<String, Double> priceChangePercentage1YInCurrency;
        private Map<String, Double> marketCapChange24HInCurrency;
        private Map<String, Double> marketCapChangePercentage24HInCurrency;
        private Double totalSupply;
        private OptionalNullable<Double> maxSupply;
        private Boolean maxSupplyInfinite;
        private Double circulatingSupply;
        private OptionalNullable<Double> outstandingSupply;
        private String lastUpdated;
        private List<Double> sparkline7D;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for currentPrice.
         * @param  currentPrice  Map of String, value for currentPrice.
         * @return Builder
         */
        public Builder currentPrice(Map<String, Double> currentPrice) {
            this.currentPrice = currentPrice;
            return this;
        }

        /**
         * Setter for totalValueLocked.
         * @param  totalValueLocked  Double value for totalValueLocked.
         * @return Builder
         */
        public Builder totalValueLocked(Double totalValueLocked) {
            this.totalValueLocked = OptionalNullable.of(totalValueLocked);
            return this;
        }

        /**
         * UnSetter for totalValueLocked.
         * @return Builder
         */
        public Builder unsetTotalValueLocked() {
            totalValueLocked = null;
            return this;
        }

        /**
         * Setter for mcapToTvlRatio.
         * @param  mcapToTvlRatio  Double value for mcapToTvlRatio.
         * @return Builder
         */
        public Builder mcapToTvlRatio(Double mcapToTvlRatio) {
            this.mcapToTvlRatio = OptionalNullable.of(mcapToTvlRatio);
            return this;
        }

        /**
         * UnSetter for mcapToTvlRatio.
         * @return Builder
         */
        public Builder unsetMcapToTvlRatio() {
            mcapToTvlRatio = null;
            return this;
        }

        /**
         * Setter for fdvToTvlRatio.
         * @param  fdvToTvlRatio  Double value for fdvToTvlRatio.
         * @return Builder
         */
        public Builder fdvToTvlRatio(Double fdvToTvlRatio) {
            this.fdvToTvlRatio = OptionalNullable.of(fdvToTvlRatio);
            return this;
        }

        /**
         * UnSetter for fdvToTvlRatio.
         * @return Builder
         */
        public Builder unsetFdvToTvlRatio() {
            fdvToTvlRatio = null;
            return this;
        }

        /**
         * Setter for roi.
         * @param  roi  Roi value for roi.
         * @return Builder
         */
        public Builder roi(Roi roi) {
            this.roi = OptionalNullable.of(roi);
            return this;
        }

        /**
         * UnSetter for roi.
         * @return Builder
         */
        public Builder unsetRoi() {
            roi = null;
            return this;
        }

        /**
         * Setter for ath.
         * @param  ath  Map of String, value for ath.
         * @return Builder
         */
        public Builder ath(Map<String, Double> ath) {
            this.ath = ath;
            return this;
        }

        /**
         * Setter for athChangePercentage.
         * @param  athChangePercentage  Map of String, value for athChangePercentage.
         * @return Builder
         */
        public Builder athChangePercentage(Map<String, Double> athChangePercentage) {
            this.athChangePercentage = athChangePercentage;
            return this;
        }

        /**
         * Setter for athDate.
         * @param  athDate  Map of String, value for athDate.
         * @return Builder
         */
        public Builder athDate(Map<String, String> athDate) {
            this.athDate = athDate;
            return this;
        }

        /**
         * Setter for atl.
         * @param  atl  Map of String, value for atl.
         * @return Builder
         */
        public Builder atl(Map<String, Double> atl) {
            this.atl = atl;
            return this;
        }

        /**
         * Setter for atlChangePercentage.
         * @param  atlChangePercentage  Map of String, value for atlChangePercentage.
         * @return Builder
         */
        public Builder atlChangePercentage(Map<String, Double> atlChangePercentage) {
            this.atlChangePercentage = atlChangePercentage;
            return this;
        }

        /**
         * Setter for atlDate.
         * @param  atlDate  Map of String, value for atlDate.
         * @return Builder
         */
        public Builder atlDate(Map<String, String> atlDate) {
            this.atlDate = atlDate;
            return this;
        }

        /**
         * Setter for marketCap.
         * @param  marketCap  Map of String, value for marketCap.
         * @return Builder
         */
        public Builder marketCap(Map<String, Double> marketCap) {
            this.marketCap = marketCap;
            return this;
        }

        /**
         * Setter for fullyDilutedValuation.
         * @param  fullyDilutedValuation  Map of String, value for fullyDilutedValuation.
         * @return Builder
         */
        public Builder fullyDilutedValuation(Map<String, Double> fullyDilutedValuation) {
            this.fullyDilutedValuation = fullyDilutedValuation;
            return this;
        }

        /**
         * Setter for marketCapFdvRatio.
         * @param  marketCapFdvRatio  Double value for marketCapFdvRatio.
         * @return Builder
         */
        public Builder marketCapFdvRatio(Double marketCapFdvRatio) {
            this.marketCapFdvRatio = marketCapFdvRatio;
            return this;
        }

        /**
         * Setter for marketCapRank.
         * @param  marketCapRank  Integer value for marketCapRank.
         * @return Builder
         */
        public Builder marketCapRank(Integer marketCapRank) {
            this.marketCapRank = OptionalNullable.of(marketCapRank);
            return this;
        }

        /**
         * UnSetter for marketCapRank.
         * @return Builder
         */
        public Builder unsetMarketCapRank() {
            marketCapRank = null;
            return this;
        }

        /**
         * Setter for outstandingTokenValueUsd.
         * @param  outstandingTokenValueUsd  Double value for outstandingTokenValueUsd.
         * @return Builder
         */
        public Builder outstandingTokenValueUsd(Double outstandingTokenValueUsd) {
            this.outstandingTokenValueUsd = OptionalNullable.of(outstandingTokenValueUsd);
            return this;
        }

        /**
         * UnSetter for outstandingTokenValueUsd.
         * @return Builder
         */
        public Builder unsetOutstandingTokenValueUsd() {
            outstandingTokenValueUsd = null;
            return this;
        }

        /**
         * Setter for marketCapRankWithRehypothecated.
         * @param  marketCapRankWithRehypothecated  Integer value for
         *         marketCapRankWithRehypothecated.
         * @return Builder
         */
        public Builder marketCapRankWithRehypothecated(Integer marketCapRankWithRehypothecated) {
            this.marketCapRankWithRehypothecated =
                    OptionalNullable.of(marketCapRankWithRehypothecated);
            return this;
        }

        /**
         * UnSetter for marketCapRankWithRehypothecated.
         * @return Builder
         */
        public Builder unsetMarketCapRankWithRehypothecated() {
            marketCapRankWithRehypothecated = null;
            return this;
        }

        /**
         * Setter for totalVolume.
         * @param  totalVolume  Map of String, value for totalVolume.
         * @return Builder
         */
        public Builder totalVolume(Map<String, Double> totalVolume) {
            this.totalVolume = totalVolume;
            return this;
        }

        /**
         * Setter for high24H.
         * @param  high24H  Map of String, value for high24H.
         * @return Builder
         */
        public Builder high24H(Map<String, Double> high24H) {
            this.high24H = high24H;
            return this;
        }

        /**
         * Setter for low24H.
         * @param  low24H  Map of String, value for low24H.
         * @return Builder
         */
        public Builder low24H(Map<String, Double> low24H) {
            this.low24H = low24H;
            return this;
        }

        /**
         * Setter for priceChange24H.
         * @param  priceChange24H  Double value for priceChange24H.
         * @return Builder
         */
        public Builder priceChange24H(Double priceChange24H) {
            this.priceChange24H = priceChange24H;
            return this;
        }

        /**
         * Setter for priceChangePercentage24H.
         * @param  priceChangePercentage24H  Double value for priceChangePercentage24H.
         * @return Builder
         */
        public Builder priceChangePercentage24H(Double priceChangePercentage24H) {
            this.priceChangePercentage24H = priceChangePercentage24H;
            return this;
        }

        /**
         * Setter for priceChangePercentage7D.
         * @param  priceChangePercentage7D  Double value for priceChangePercentage7D.
         * @return Builder
         */
        public Builder priceChangePercentage7D(Double priceChangePercentage7D) {
            this.priceChangePercentage7D = priceChangePercentage7D;
            return this;
        }

        /**
         * Setter for priceChangePercentage14D.
         * @param  priceChangePercentage14D  Double value for priceChangePercentage14D.
         * @return Builder
         */
        public Builder priceChangePercentage14D(Double priceChangePercentage14D) {
            this.priceChangePercentage14D = priceChangePercentage14D;
            return this;
        }

        /**
         * Setter for priceChangePercentage30D.
         * @param  priceChangePercentage30D  Double value for priceChangePercentage30D.
         * @return Builder
         */
        public Builder priceChangePercentage30D(Double priceChangePercentage30D) {
            this.priceChangePercentage30D = priceChangePercentage30D;
            return this;
        }

        /**
         * Setter for priceChangePercentage60D.
         * @param  priceChangePercentage60D  Double value for priceChangePercentage60D.
         * @return Builder
         */
        public Builder priceChangePercentage60D(Double priceChangePercentage60D) {
            this.priceChangePercentage60D = priceChangePercentage60D;
            return this;
        }

        /**
         * Setter for priceChangePercentage200D.
         * @param  priceChangePercentage200D  Double value for priceChangePercentage200D.
         * @return Builder
         */
        public Builder priceChangePercentage200D(Double priceChangePercentage200D) {
            this.priceChangePercentage200D = priceChangePercentage200D;
            return this;
        }

        /**
         * Setter for priceChangePercentage1Y.
         * @param  priceChangePercentage1Y  Double value for priceChangePercentage1Y.
         * @return Builder
         */
        public Builder priceChangePercentage1Y(Double priceChangePercentage1Y) {
            this.priceChangePercentage1Y = priceChangePercentage1Y;
            return this;
        }

        /**
         * Setter for marketCapChange24H.
         * @param  marketCapChange24H  Double value for marketCapChange24H.
         * @return Builder
         */
        public Builder marketCapChange24H(Double marketCapChange24H) {
            this.marketCapChange24H = marketCapChange24H;
            return this;
        }

        /**
         * Setter for marketCapChangePercentage24H.
         * @param  marketCapChangePercentage24H  Double value for marketCapChangePercentage24H.
         * @return Builder
         */
        public Builder marketCapChangePercentage24H(Double marketCapChangePercentage24H) {
            this.marketCapChangePercentage24H = marketCapChangePercentage24H;
            return this;
        }

        /**
         * Setter for priceChange24HInCurrency.
         * @param  priceChange24HInCurrency  Map of String, value for priceChange24HInCurrency.
         * @return Builder
         */
        public Builder priceChange24HInCurrency(Map<String, Double> priceChange24HInCurrency) {
            this.priceChange24HInCurrency = priceChange24HInCurrency;
            return this;
        }

        /**
         * Setter for priceChangePercentage1HInCurrency.
         * @param  priceChangePercentage1HInCurrency  Map of String, value for
         *         priceChangePercentage1HInCurrency.
         * @return Builder
         */
        public Builder priceChangePercentage1HInCurrency(
                Map<String, Double> priceChangePercentage1HInCurrency) {
            this.priceChangePercentage1HInCurrency = priceChangePercentage1HInCurrency;
            return this;
        }

        /**
         * Setter for priceChangePercentage24HInCurrency.
         * @param  priceChangePercentage24HInCurrency  Map of String, value for
         *         priceChangePercentage24HInCurrency.
         * @return Builder
         */
        public Builder priceChangePercentage24HInCurrency(
                Map<String, Double> priceChangePercentage24HInCurrency) {
            this.priceChangePercentage24HInCurrency = priceChangePercentage24HInCurrency;
            return this;
        }

        /**
         * Setter for priceChangePercentage7DInCurrency.
         * @param  priceChangePercentage7DInCurrency  Map of String, value for
         *         priceChangePercentage7DInCurrency.
         * @return Builder
         */
        public Builder priceChangePercentage7DInCurrency(
                Map<String, Double> priceChangePercentage7DInCurrency) {
            this.priceChangePercentage7DInCurrency = priceChangePercentage7DInCurrency;
            return this;
        }

        /**
         * Setter for priceChangePercentage14DInCurrency.
         * @param  priceChangePercentage14DInCurrency  Map of String, value for
         *         priceChangePercentage14DInCurrency.
         * @return Builder
         */
        public Builder priceChangePercentage14DInCurrency(
                Map<String, Double> priceChangePercentage14DInCurrency) {
            this.priceChangePercentage14DInCurrency = priceChangePercentage14DInCurrency;
            return this;
        }

        /**
         * Setter for priceChangePercentage30DInCurrency.
         * @param  priceChangePercentage30DInCurrency  Map of String, value for
         *         priceChangePercentage30DInCurrency.
         * @return Builder
         */
        public Builder priceChangePercentage30DInCurrency(
                Map<String, Double> priceChangePercentage30DInCurrency) {
            this.priceChangePercentage30DInCurrency = priceChangePercentage30DInCurrency;
            return this;
        }

        /**
         * Setter for priceChangePercentage60DInCurrency.
         * @param  priceChangePercentage60DInCurrency  Map of String, value for
         *         priceChangePercentage60DInCurrency.
         * @return Builder
         */
        public Builder priceChangePercentage60DInCurrency(
                Map<String, Double> priceChangePercentage60DInCurrency) {
            this.priceChangePercentage60DInCurrency = priceChangePercentage60DInCurrency;
            return this;
        }

        /**
         * Setter for priceChangePercentage200DInCurrency.
         * @param  priceChangePercentage200DInCurrency  Map of String, value for
         *         priceChangePercentage200DInCurrency.
         * @return Builder
         */
        public Builder priceChangePercentage200DInCurrency(
                Map<String, Double> priceChangePercentage200DInCurrency) {
            this.priceChangePercentage200DInCurrency = priceChangePercentage200DInCurrency;
            return this;
        }

        /**
         * Setter for priceChangePercentage1YInCurrency.
         * @param  priceChangePercentage1YInCurrency  Map of String, value for
         *         priceChangePercentage1YInCurrency.
         * @return Builder
         */
        public Builder priceChangePercentage1YInCurrency(
                Map<String, Double> priceChangePercentage1YInCurrency) {
            this.priceChangePercentage1YInCurrency = priceChangePercentage1YInCurrency;
            return this;
        }

        /**
         * Setter for marketCapChange24HInCurrency.
         * @param  marketCapChange24HInCurrency  Map of String, value for
         *         marketCapChange24HInCurrency.
         * @return Builder
         */
        public Builder marketCapChange24HInCurrency(
                Map<String, Double> marketCapChange24HInCurrency) {
            this.marketCapChange24HInCurrency = marketCapChange24HInCurrency;
            return this;
        }

        /**
         * Setter for marketCapChangePercentage24HInCurrency.
         * @param  marketCapChangePercentage24HInCurrency  Map of String, value for
         *         marketCapChangePercentage24HInCurrency.
         * @return Builder
         */
        public Builder marketCapChangePercentage24HInCurrency(
                Map<String, Double> marketCapChangePercentage24HInCurrency) {
            this.marketCapChangePercentage24HInCurrency = marketCapChangePercentage24HInCurrency;
            return this;
        }

        /**
         * Setter for totalSupply.
         * @param  totalSupply  Double value for totalSupply.
         * @return Builder
         */
        public Builder totalSupply(Double totalSupply) {
            this.totalSupply = totalSupply;
            return this;
        }

        /**
         * Setter for maxSupply.
         * @param  maxSupply  Double value for maxSupply.
         * @return Builder
         */
        public Builder maxSupply(Double maxSupply) {
            this.maxSupply = OptionalNullable.of(maxSupply);
            return this;
        }

        /**
         * UnSetter for maxSupply.
         * @return Builder
         */
        public Builder unsetMaxSupply() {
            maxSupply = null;
            return this;
        }

        /**
         * Setter for maxSupplyInfinite.
         * @param  maxSupplyInfinite  Boolean value for maxSupplyInfinite.
         * @return Builder
         */
        public Builder maxSupplyInfinite(Boolean maxSupplyInfinite) {
            this.maxSupplyInfinite = maxSupplyInfinite;
            return this;
        }

        /**
         * Setter for circulatingSupply.
         * @param  circulatingSupply  Double value for circulatingSupply.
         * @return Builder
         */
        public Builder circulatingSupply(Double circulatingSupply) {
            this.circulatingSupply = circulatingSupply;
            return this;
        }

        /**
         * Setter for outstandingSupply.
         * @param  outstandingSupply  Double value for outstandingSupply.
         * @return Builder
         */
        public Builder outstandingSupply(Double outstandingSupply) {
            this.outstandingSupply = OptionalNullable.of(outstandingSupply);
            return this;
        }

        /**
         * UnSetter for outstandingSupply.
         * @return Builder
         */
        public Builder unsetOutstandingSupply() {
            outstandingSupply = null;
            return this;
        }

        /**
         * Setter for lastUpdated.
         * @param  lastUpdated  String value for lastUpdated.
         * @return Builder
         */
        public Builder lastUpdated(String lastUpdated) {
            this.lastUpdated = lastUpdated;
            return this;
        }

        /**
         * Setter for sparkline7D.
         * @param  sparkline7D  List of Double value for sparkline7D.
         * @return Builder
         */
        public Builder sparkline7D(List<Double> sparkline7D) {
            this.sparkline7D = sparkline7D;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link MarketData1} object using the set fields.
         * @return {@link MarketData1}
         */
        public MarketData1 build() {
            MarketData1 model =
                    new MarketData1(currentPrice, totalValueLocked, mcapToTvlRatio, fdvToTvlRatio,
                            roi, ath, athChangePercentage, athDate, atl, atlChangePercentage,
                            atlDate, marketCap, fullyDilutedValuation, marketCapFdvRatio,
                            marketCapRank, outstandingTokenValueUsd,
                            marketCapRankWithRehypothecated, totalVolume, high24H, low24H,
                            priceChange24H, priceChangePercentage24H, priceChangePercentage7D,
                            priceChangePercentage14D, priceChangePercentage30D,
                            priceChangePercentage60D, priceChangePercentage200D,
                            priceChangePercentage1Y, marketCapChange24H,
                            marketCapChangePercentage24H, priceChange24HInCurrency,
                            priceChangePercentage1HInCurrency, priceChangePercentage24HInCurrency,
                            priceChangePercentage7DInCurrency, priceChangePercentage14DInCurrency,
                            priceChangePercentage30DInCurrency, priceChangePercentage60DInCurrency,
                            priceChangePercentage200DInCurrency, priceChangePercentage1YInCurrency,
                            marketCapChange24HInCurrency, marketCapChangePercentage24HInCurrency,
                            totalSupply, maxSupply, maxSupplyInfinite, circulatingSupply,
                            outstandingSupply, lastUpdated, sparkline7D);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
