/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Meta type.
 */
public class Meta {
    private Base base;
    private Quote quote;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Meta() {
    }

    /**
     * Initialization constructor.
     * @param  base  Base value for base.
     * @param  quote  Quote value for quote.
     */
    public Meta(
            Base base,
            Quote quote) {
        this.base = base;
        this.quote = quote;
    }

    /**
     * Getter for Base.
     * Base token metadata
     * @return Returns the Base
     */
    @JsonGetter("base")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Base getBase() {
        return base;
    }

    /**
     * Setter for Base.
     * Base token metadata
     * @param base Value for Base
     */
    @JsonSetter("base")
    public void setBase(Base base) {
        this.base = base;
    }

    /**
     * Getter for Quote.
     * Quote token metadata
     * @return Returns the Quote
     */
    @JsonGetter("quote")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Quote getQuote() {
        return quote;
    }

    /**
     * Setter for Quote.
     * Quote token metadata
     * @param quote Value for Quote
     */
    @JsonSetter("quote")
    public void setQuote(Quote quote) {
        this.quote = quote;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Meta into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Meta [" + "base=" + base + ", quote=" + quote + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Meta.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Meta.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .base(getBase())
                .quote(getQuote());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Meta}.
     */
    public static class Builder {
        private Base base;
        private Quote quote;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for base.
         * @param  base  Base value for base.
         * @return Builder
         */
        public Builder base(Base base) {
            this.base = base;
            return this;
        }

        /**
         * Setter for quote.
         * @param  quote  Quote value for quote.
         * @return Builder
         */
        public Builder quote(Quote quote) {
            this.quote = quote;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Meta} object using the set fields.
         * @return {@link Meta}
         */
        public Meta build() {
            Meta model =
                    new Meta(base, quote);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
