/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for NetBuyVolumeUsd type.
 */
public class NetBuyVolumeUsd {
    private String m5;
    private String m15;
    private String m30;
    private String h1;
    private String h6;
    private String h24;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public NetBuyVolumeUsd() {
    }

    /**
     * Initialization constructor.
     * @param  m5  String value for m5.
     * @param  m15  String value for m15.
     * @param  m30  String value for m30.
     * @param  h1  String value for h1.
     * @param  h6  String value for h6.
     * @param  h24  String value for h24.
     */
    public NetBuyVolumeUsd(
            String m5,
            String m15,
            String m30,
            String h1,
            String h6,
            String h24) {
        this.m5 = m5;
        this.m15 = m15;
        this.m30 = m30;
        this.h1 = h1;
        this.h6 = h6;
        this.h24 = h24;
    }

    /**
     * Getter for M5.
     * @return Returns the String
     */
    @JsonGetter("m5")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getM5() {
        return m5;
    }

    /**
     * Setter for M5.
     * @param m5 Value for String
     */
    @JsonSetter("m5")
    public void setM5(String m5) {
        this.m5 = m5;
    }

    /**
     * Getter for M15.
     * @return Returns the String
     */
    @JsonGetter("m15")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getM15() {
        return m15;
    }

    /**
     * Setter for M15.
     * @param m15 Value for String
     */
    @JsonSetter("m15")
    public void setM15(String m15) {
        this.m15 = m15;
    }

    /**
     * Getter for M30.
     * @return Returns the String
     */
    @JsonGetter("m30")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getM30() {
        return m30;
    }

    /**
     * Setter for M30.
     * @param m30 Value for String
     */
    @JsonSetter("m30")
    public void setM30(String m30) {
        this.m30 = m30;
    }

    /**
     * Getter for H1.
     * @return Returns the String
     */
    @JsonGetter("h1")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getH1() {
        return h1;
    }

    /**
     * Setter for H1.
     * @param h1 Value for String
     */
    @JsonSetter("h1")
    public void setH1(String h1) {
        this.h1 = h1;
    }

    /**
     * Getter for H6.
     * @return Returns the String
     */
    @JsonGetter("h6")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getH6() {
        return h6;
    }

    /**
     * Setter for H6.
     * @param h6 Value for String
     */
    @JsonSetter("h6")
    public void setH6(String h6) {
        this.h6 = h6;
    }

    /**
     * Getter for H24.
     * @return Returns the String
     */
    @JsonGetter("h24")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getH24() {
        return h24;
    }

    /**
     * Setter for H24.
     * @param h24 Value for String
     */
    @JsonSetter("h24")
    public void setH24(String h24) {
        this.h24 = h24;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this NetBuyVolumeUsd into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "NetBuyVolumeUsd [" + "m5=" + m5 + ", m15=" + m15 + ", m30=" + m30 + ", h1=" + h1
                + ", h6=" + h6 + ", h24=" + h24 + ", additionalProperties=" + additionalProperties
                + "]";
    }

    /**
     * Builds a new {@link NetBuyVolumeUsd.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link NetBuyVolumeUsd.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .m5(getM5())
                .m15(getM15())
                .m30(getM30())
                .h1(getH1())
                .h6(getH6())
                .h24(getH24());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link NetBuyVolumeUsd}.
     */
    public static class Builder {
        private String m5;
        private String m15;
        private String m30;
        private String h1;
        private String h6;
        private String h24;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for m5.
         * @param  m5  String value for m5.
         * @return Builder
         */
        public Builder m5(String m5) {
            this.m5 = m5;
            return this;
        }

        /**
         * Setter for m15.
         * @param  m15  String value for m15.
         * @return Builder
         */
        public Builder m15(String m15) {
            this.m15 = m15;
            return this;
        }

        /**
         * Setter for m30.
         * @param  m30  String value for m30.
         * @return Builder
         */
        public Builder m30(String m30) {
            this.m30 = m30;
            return this;
        }

        /**
         * Setter for h1.
         * @param  h1  String value for h1.
         * @return Builder
         */
        public Builder h1(String h1) {
            this.h1 = h1;
            return this;
        }

        /**
         * Setter for h6.
         * @param  h6  String value for h6.
         * @return Builder
         */
        public Builder h6(String h6) {
            this.h6 = h6;
            return this;
        }

        /**
         * Setter for h24.
         * @param  h24  String value for h24.
         * @return Builder
         */
        public Builder h24(String h24) {
            this.h24 = h24;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link NetBuyVolumeUsd} object using the set fields.
         * @return {@link NetBuyVolumeUsd}
         */
        public NetBuyVolumeUsd build() {
            NetBuyVolumeUsd model =
                    new NetBuyVolumeUsd(m5, m15, m30, h1, h6, h24);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
