/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Nft type.
 */
public class Nft {
    private String id;
    private String name;
    private String symbol;
    private String thumb;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Nft() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  name  String value for name.
     * @param  symbol  String value for symbol.
     * @param  thumb  String value for thumb.
     */
    public Nft(
            String id,
            String name,
            String symbol,
            String thumb) {
        this.id = id;
        this.name = name;
        this.symbol = symbol;
        this.thumb = thumb;
    }

    /**
     * Getter for Id.
     * NFT collection ID
     * @return Returns the String
     */
    @JsonGetter("id")
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * NFT collection ID
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for Name.
     * NFT collection name
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * NFT collection name
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for Symbol.
     * NFT collection symbol
     * @return Returns the String
     */
    @JsonGetter("symbol")
    public String getSymbol() {
        return symbol;
    }

    /**
     * Setter for Symbol.
     * NFT collection symbol
     * @param symbol Value for String
     */
    @JsonSetter("symbol")
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    /**
     * Getter for Thumb.
     * NFT collection thumb image URL
     * @return Returns the String
     */
    @JsonGetter("thumb")
    public String getThumb() {
        return thumb;
    }

    /**
     * Setter for Thumb.
     * NFT collection thumb image URL
     * @param thumb Value for String
     */
    @JsonSetter("thumb")
    public void setThumb(String thumb) {
        this.thumb = thumb;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Nft into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Nft [" + "id=" + id + ", name=" + name + ", symbol=" + symbol + ", thumb=" + thumb
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Nft.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Nft.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(id, name, symbol, thumb);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Nft}.
     */
    public static class Builder {
        private String id;
        private String name;
        private String symbol;
        private String thumb;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  id  String value for id.
         * @param  name  String value for name.
         * @param  symbol  String value for symbol.
         * @param  thumb  String value for thumb.
         */
        public Builder(String id, String name, String symbol, String thumb) {
            this.id = id;
            this.name = name;
            this.symbol = symbol;
            this.thumb = thumb;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for symbol.
         * @param  symbol  String value for symbol.
         * @return Builder
         */
        public Builder symbol(String symbol) {
            this.symbol = symbol;
            return this;
        }

        /**
         * Setter for thumb.
         * @param  thumb  String value for thumb.
         * @return Builder
         */
        public Builder thumb(String thumb) {
            this.thumb = thumb;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Nft} object using the set fields.
         * @return {@link Nft}
         */
        public Nft build() {
            Nft model =
                    new Nft(id, name, symbol, thumb);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
