/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * Order to be used.
 */
public enum Order {
    MARKET_CAP_ASC,

    MARKET_CAP_DESC,

    VOLUME_ASC,

    VOLUME_DESC,

    ID_ASC,

    ID_DESC;

    private static TreeMap<String, Order> valueMap = new TreeMap<>();
    private String value;

    static {
        MARKET_CAP_ASC.value = "market_cap_asc";
        MARKET_CAP_DESC.value = "market_cap_desc";
        VOLUME_ASC.value = "volume_asc";
        VOLUME_DESC.value = "volume_desc";
        ID_ASC.value = "id_asc";
        ID_DESC.value = "id_desc";

        valueMap.put("market_cap_asc", MARKET_CAP_ASC);
        valueMap.put("market_cap_desc", MARKET_CAP_DESC);
        valueMap.put("volume_asc", VOLUME_ASC);
        valueMap.put("volume_desc", VOLUME_DESC);
        valueMap.put("id_asc", ID_ASC);
        valueMap.put("id_desc", ID_DESC);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Order constructFromString(String toConvert) throws IOException {
        Order enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Order fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Order values to list of string values.
     * @param toConvert The list of Order values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Order> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Order enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 