/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for PingServer type.
 */
public class PingServer {
    private String geckoSays;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public PingServer() {
    }

    /**
     * Initialization constructor.
     * @param  geckoSays  String value for geckoSays.
     */
    public PingServer(
            String geckoSays) {
        this.geckoSays = geckoSays;
    }

    /**
     * Getter for GeckoSays.
     * API server status message
     * @return Returns the String
     */
    @JsonGetter("gecko_says")
    public String getGeckoSays() {
        return geckoSays;
    }

    /**
     * Setter for GeckoSays.
     * API server status message
     * @param geckoSays Value for String
     */
    @JsonSetter("gecko_says")
    public void setGeckoSays(String geckoSays) {
        this.geckoSays = geckoSays;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this PingServer into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PingServer [" + "geckoSays=" + geckoSays + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link PingServer.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PingServer.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(geckoSays);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link PingServer}.
     */
    public static class Builder {
        private String geckoSays;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  geckoSays  String value for geckoSays.
         */
        public Builder(String geckoSays) {
            this.geckoSays = geckoSays;
        }

        /**
         * Setter for geckoSays.
         * @param  geckoSays  String value for geckoSays.
         * @return Builder
         */
        public Builder geckoSays(String geckoSays) {
            this.geckoSays = geckoSays;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link PingServer} object using the set fields.
         * @return {@link PingServer}
         */
        public PingServer build() {
            PingServer model =
                    new PingServer(geckoSays);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
