/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * Precision to be used.
 */
public enum Precision {
    FULL,

    ENUM_0,

    ENUM_1,

    ENUM_2,

    ENUM_3,

    ENUM_4,

    ENUM_5,

    ENUM_6,

    ENUM_7,

    ENUM_8,

    ENUM_9,

    ENUM_10,

    ENUM_11,

    ENUM_12,

    ENUM_13,

    ENUM_14,

    ENUM_15,

    ENUM_16,

    ENUM_17,

    ENUM_18;

    private static TreeMap<String, Precision> valueMap = new TreeMap<>();
    private String value;

    static {
        FULL.value = "full";
        ENUM_0.value = "0";
        ENUM_1.value = "1";
        ENUM_2.value = "2";
        ENUM_3.value = "3";
        ENUM_4.value = "4";
        ENUM_5.value = "5";
        ENUM_6.value = "6";
        ENUM_7.value = "7";
        ENUM_8.value = "8";
        ENUM_9.value = "9";
        ENUM_10.value = "10";
        ENUM_11.value = "11";
        ENUM_12.value = "12";
        ENUM_13.value = "13";
        ENUM_14.value = "14";
        ENUM_15.value = "15";
        ENUM_16.value = "16";
        ENUM_17.value = "17";
        ENUM_18.value = "18";

        valueMap.put("full", FULL);
        valueMap.put("0", ENUM_0);
        valueMap.put("1", ENUM_1);
        valueMap.put("2", ENUM_2);
        valueMap.put("3", ENUM_3);
        valueMap.put("4", ENUM_4);
        valueMap.put("5", ENUM_5);
        valueMap.put("6", ENUM_6);
        valueMap.put("7", ENUM_7);
        valueMap.put("8", ENUM_8);
        valueMap.put("9", ENUM_9);
        valueMap.put("10", ENUM_10);
        valueMap.put("11", ENUM_11);
        valueMap.put("12", ENUM_12);
        valueMap.put("13", ENUM_13);
        valueMap.put("14", ENUM_14);
        valueMap.put("15", ENUM_15);
        valueMap.put("16", ENUM_16);
        valueMap.put("17", ENUM_17);
        valueMap.put("18", ENUM_18);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Precision constructFromString(String toConvert) throws IOException {
        Precision enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Precision fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Precision values to list of string values.
     * @param toConvert The list of Precision values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Precision> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Precision enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 