/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for PublicTreasuryTransactionHistory type.
 */
public class PublicTreasuryTransactionHistory {
    private List<Transaction> transactions;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public PublicTreasuryTransactionHistory() {
    }

    /**
     * Initialization constructor.
     * @param  transactions  List of Transaction value for transactions.
     */
    public PublicTreasuryTransactionHistory(
            List<Transaction> transactions) {
        this.transactions = transactions;
    }

    /**
     * Getter for Transactions.
     * @return Returns the List of Transaction
     */
    @JsonGetter("transactions")
    public List<Transaction> getTransactions() {
        return transactions;
    }

    /**
     * Setter for Transactions.
     * @param transactions Value for List of Transaction
     */
    @JsonSetter("transactions")
    public void setTransactions(List<Transaction> transactions) {
        this.transactions = transactions;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this PublicTreasuryTransactionHistory into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PublicTreasuryTransactionHistory [" + "transactions=" + transactions
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link PublicTreasuryTransactionHistory.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PublicTreasuryTransactionHistory.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(transactions);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link PublicTreasuryTransactionHistory}.
     */
    public static class Builder {
        private List<Transaction> transactions;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  transactions  List of Transaction value for transactions.
         */
        public Builder(List<Transaction> transactions) {
            this.transactions = transactions;
        }

        /**
         * Setter for transactions.
         * @param  transactions  List of Transaction value for transactions.
         * @return Builder
         */
        public Builder transactions(List<Transaction> transactions) {
            this.transactions = transactions;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link PublicTreasuryTransactionHistory} object using the set fields.
         * @return {@link PublicTreasuryTransactionHistory}
         */
        public PublicTreasuryTransactionHistory build() {
            PublicTreasuryTransactionHistory model =
                    new PublicTreasuryTransactionHistory(transactions);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
