/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for PublicTreasuryEntityChart type.
 */
public class PublicTreasuryEntityChart {
    private List<List<Double>> holdings;
    private List<List<Double>> holdingValueInUsd;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public PublicTreasuryEntityChart() {
    }

    /**
     * Initialization constructor.
     * @param  holdings  List of Double value for holdings.
     * @param  holdingValueInUsd  List of Double value for holdingValueInUsd.
     */
    public PublicTreasuryEntityChart(
            List<List<Double>> holdings,
            List<List<Double>> holdingValueInUsd) {
        this.holdings = holdings;
        this.holdingValueInUsd = holdingValueInUsd;
    }

    /**
     * Getter for Holdings.
     * Historical holdings data as [timestamp, amount] pairs
     * @return Returns the List of Double
     */
    @JsonGetter("holdings")
    public List<List<Double>> getHoldings() {
        return holdings;
    }

    /**
     * Setter for Holdings.
     * Historical holdings data as [timestamp, amount] pairs
     * @param holdings Value for List of Double
     */
    @JsonSetter("holdings")
    public void setHoldings(List<List<Double>> holdings) {
        this.holdings = holdings;
    }

    /**
     * Getter for HoldingValueInUsd.
     * Historical holdings value in USD as [timestamp, value_usd] pairs
     * @return Returns the List of Double
     */
    @JsonGetter("holding_value_in_usd")
    public List<List<Double>> getHoldingValueInUsd() {
        return holdingValueInUsd;
    }

    /**
     * Setter for HoldingValueInUsd.
     * Historical holdings value in USD as [timestamp, value_usd] pairs
     * @param holdingValueInUsd Value for List of Double
     */
    @JsonSetter("holding_value_in_usd")
    public void setHoldingValueInUsd(List<List<Double>> holdingValueInUsd) {
        this.holdingValueInUsd = holdingValueInUsd;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this PublicTreasuryEntityChart into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PublicTreasuryEntityChart [" + "holdings=" + holdings + ", holdingValueInUsd="
                + holdingValueInUsd + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link PublicTreasuryEntityChart.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PublicTreasuryEntityChart.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(holdings, holdingValueInUsd);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link PublicTreasuryEntityChart}.
     */
    public static class Builder {
        private List<List<Double>> holdings;
        private List<List<Double>> holdingValueInUsd;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  holdings  List of Double value for holdings.
         * @param  holdingValueInUsd  List of Double value for holdingValueInUsd.
         */
        public Builder(List<List<Double>> holdings, List<List<Double>> holdingValueInUsd) {
            this.holdings = holdings;
            this.holdingValueInUsd = holdingValueInUsd;
        }

        /**
         * Setter for holdings.
         * @param  holdings  List of Double value for holdings.
         * @return Builder
         */
        public Builder holdings(List<List<Double>> holdings) {
            this.holdings = holdings;
            return this;
        }

        /**
         * Setter for holdingValueInUsd.
         * @param  holdingValueInUsd  List of Double value for holdingValueInUsd.
         * @return Builder
         */
        public Builder holdingValueInUsd(List<List<Double>> holdingValueInUsd) {
            this.holdingValueInUsd = holdingValueInUsd;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link PublicTreasuryEntityChart} object using the set fields.
         * @return {@link PublicTreasuryEntityChart}
         */
        public PublicTreasuryEntityChart build() {
            PublicTreasuryEntityChart model =
                    new PublicTreasuryEntityChart(holdings, holdingValueInUsd);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
