/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Rates type.
 */
public class Rates {
    private String name;
    private String unit;
    private double value;
    private String type;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Rates() {
    }

    /**
     * Initialization constructor.
     * @param  name  String value for name.
     * @param  unit  String value for unit.
     * @param  value  double value for value.
     * @param  type  String value for type.
     */
    public Rates(
            String name,
            String unit,
            double value,
            String type) {
        this.name = name;
        this.unit = unit;
        this.value = value;
        this.type = type;
    }

    /**
     * Getter for Name.
     * Currency name
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * Currency name
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for Unit.
     * Currency unit symbol
     * @return Returns the String
     */
    @JsonGetter("unit")
    public String getUnit() {
        return unit;
    }

    /**
     * Setter for Unit.
     * Currency unit symbol
     * @param unit Value for String
     */
    @JsonSetter("unit")
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * Getter for Value.
     * Exchange rate value relative to BTC
     * @return Returns the double
     */
    @JsonGetter("value")
    public double getValue() {
        return value;
    }

    /**
     * Setter for Value.
     * Exchange rate value relative to BTC
     * @param value Value for double
     */
    @JsonSetter("value")
    public void setValue(double value) {
        this.value = value;
    }

    /**
     * Getter for Type.
     * Currency type: crypto, fiat, or commodity
     * @return Returns the String
     */
    @JsonGetter("type")
    public String getType() {
        return type;
    }

    /**
     * Setter for Type.
     * Currency type: crypto, fiat, or commodity
     * @param type Value for String
     */
    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Rates into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Rates [" + "name=" + name + ", unit=" + unit + ", value=" + value + ", type=" + type
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Rates.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Rates.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(name, unit, value, type);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Rates}.
     */
    public static class Builder {
        private String name;
        private String unit;
        private double value;
        private String type;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  name  String value for name.
         * @param  unit  String value for unit.
         * @param  value  double value for value.
         * @param  type  String value for type.
         */
        public Builder(String name, String unit, double value, String type) {
            this.name = name;
            this.unit = unit;
            this.value = value;
            this.type = type;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for unit.
         * @param  unit  String value for unit.
         * @return Builder
         */
        public Builder unit(String unit) {
            this.unit = unit;
            return this;
        }

        /**
         * Setter for value.
         * @param  value  double value for value.
         * @return Builder
         */
        public Builder value(double value) {
            this.value = value;
            return this;
        }

        /**
         * Setter for type.
         * @param  type  String value for type.
         * @return Builder
         */
        public Builder type(String type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Rates} object using the set fields.
         * @return {@link Rates}
         */
        public Rates build() {
            Rates model =
                    new Rates(name, unit, value, type);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
