/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Relationships type.
 */
public class Relationships {
    private BaseToken baseToken;
    private QuoteToken quoteToken;
    private Dex dex;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Relationships() {
    }

    /**
     * Initialization constructor.
     * @param  baseToken  BaseToken value for baseToken.
     * @param  quoteToken  QuoteToken value for quoteToken.
     * @param  dex  Dex value for dex.
     */
    public Relationships(
            BaseToken baseToken,
            QuoteToken quoteToken,
            Dex dex) {
        this.baseToken = baseToken;
        this.quoteToken = quoteToken;
        this.dex = dex;
    }

    /**
     * Getter for BaseToken.
     * @return Returns the BaseToken
     */
    @JsonGetter("base_token")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public BaseToken getBaseToken() {
        return baseToken;
    }

    /**
     * Setter for BaseToken.
     * @param baseToken Value for BaseToken
     */
    @JsonSetter("base_token")
    public void setBaseToken(BaseToken baseToken) {
        this.baseToken = baseToken;
    }

    /**
     * Getter for QuoteToken.
     * @return Returns the QuoteToken
     */
    @JsonGetter("quote_token")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public QuoteToken getQuoteToken() {
        return quoteToken;
    }

    /**
     * Setter for QuoteToken.
     * @param quoteToken Value for QuoteToken
     */
    @JsonSetter("quote_token")
    public void setQuoteToken(QuoteToken quoteToken) {
        this.quoteToken = quoteToken;
    }

    /**
     * Getter for Dex.
     * @return Returns the Dex
     */
    @JsonGetter("dex")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Dex getDex() {
        return dex;
    }

    /**
     * Setter for Dex.
     * @param dex Value for Dex
     */
    @JsonSetter("dex")
    public void setDex(Dex dex) {
        this.dex = dex;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Relationships into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Relationships [" + "baseToken=" + baseToken + ", quoteToken=" + quoteToken
                + ", dex=" + dex + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Relationships.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Relationships.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .baseToken(getBaseToken())
                .quoteToken(getQuoteToken())
                .dex(getDex());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Relationships}.
     */
    public static class Builder {
        private BaseToken baseToken;
        private QuoteToken quoteToken;
        private Dex dex;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for baseToken.
         * @param  baseToken  BaseToken value for baseToken.
         * @return Builder
         */
        public Builder baseToken(BaseToken baseToken) {
            this.baseToken = baseToken;
            return this;
        }

        /**
         * Setter for quoteToken.
         * @param  quoteToken  QuoteToken value for quoteToken.
         * @return Builder
         */
        public Builder quoteToken(QuoteToken quoteToken) {
            this.quoteToken = quoteToken;
            return this;
        }

        /**
         * Setter for dex.
         * @param  dex  Dex value for dex.
         * @return Builder
         */
        public Builder dex(Dex dex) {
            this.dex = dex;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Relationships} object using the set fields.
         * @return {@link Relationships}
         */
        public Relationships build() {
            Relationships model =
                    new Relationships(baseToken, quoteToken, dex);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
