/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Roi2 type.
 */
public class Roi2 {
    private Double times;
    private String currency;
    private Double percentage;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Roi2() {
    }

    /**
     * Initialization constructor.
     * @param  times  Double value for times.
     * @param  currency  String value for currency.
     * @param  percentage  Double value for percentage.
     */
    public Roi2(
            Double times,
            String currency,
            Double percentage) {
        this.times = times;
        this.currency = currency;
        this.percentage = percentage;
    }

    /**
     * Getter for Times.
     * ROI multiplier
     * @return Returns the Double
     */
    @JsonGetter("times")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getTimes() {
        return times;
    }

    /**
     * Setter for Times.
     * ROI multiplier
     * @param times Value for Double
     */
    @JsonSetter("times")
    public void setTimes(Double times) {
        this.times = times;
    }

    /**
     * Getter for Currency.
     * ROI currency
     * @return Returns the String
     */
    @JsonGetter("currency")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCurrency() {
        return currency;
    }

    /**
     * Setter for Currency.
     * ROI currency
     * @param currency Value for String
     */
    @JsonSetter("currency")
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * Getter for Percentage.
     * ROI percentage
     * @return Returns the Double
     */
    @JsonGetter("percentage")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getPercentage() {
        return percentage;
    }

    /**
     * Setter for Percentage.
     * ROI percentage
     * @param percentage Value for Double
     */
    @JsonSetter("percentage")
    public void setPercentage(Double percentage) {
        this.percentage = percentage;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Roi2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Roi2 [" + "times=" + times + ", currency=" + currency + ", percentage=" + percentage
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Roi2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Roi2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .times(getTimes())
                .currency(getCurrency())
                .percentage(getPercentage());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Roi2}.
     */
    public static class Builder {
        private Double times;
        private String currency;
        private Double percentage;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for times.
         * @param  times  Double value for times.
         * @return Builder
         */
        public Builder times(Double times) {
            this.times = times;
            return this;
        }

        /**
         * Setter for currency.
         * @param  currency  String value for currency.
         * @return Builder
         */
        public Builder currency(String currency) {
            this.currency = currency;
            return this;
        }

        /**
         * Setter for percentage.
         * @param  percentage  Double value for percentage.
         * @return Builder
         */
        public Builder percentage(Double percentage) {
            this.percentage = percentage;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Roi2} object using the set fields.
         * @return {@link Roi2}
         */
        public Roi2 build() {
            Roi2 model =
                    new Roi2(times, currency, percentage);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
