/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for SimplePrice type.
 */
public class SimplePrice {
    private Double usd;
    private Double usdMarketCap;
    private Double usd24HVol;
    private Double usd24HChange;
    private Double lastUpdatedAt;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public SimplePrice() {
    }

    /**
     * Initialization constructor.
     * @param  usd  Double value for usd.
     * @param  usdMarketCap  Double value for usdMarketCap.
     * @param  usd24HVol  Double value for usd24HVol.
     * @param  usd24HChange  Double value for usd24HChange.
     * @param  lastUpdatedAt  Double value for lastUpdatedAt.
     */
    public SimplePrice(
            Double usd,
            Double usdMarketCap,
            Double usd24HVol,
            Double usd24HChange,
            Double lastUpdatedAt) {
        this.usd = usd;
        this.usdMarketCap = usdMarketCap;
        this.usd24HVol = usd24HVol;
        this.usd24HChange = usd24HChange;
        this.lastUpdatedAt = lastUpdatedAt;
    }

    /**
     * Getter for Usd.
     * Price in the target currency
     * @return Returns the Double
     */
    @JsonGetter("usd")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getUsd() {
        return usd;
    }

    /**
     * Setter for Usd.
     * Price in the target currency
     * @param usd Value for Double
     */
    @JsonSetter("usd")
    public void setUsd(Double usd) {
        this.usd = usd;
    }

    /**
     * Getter for UsdMarketCap.
     * Market capitalization in the target currency
     * @return Returns the Double
     */
    @JsonGetter("usd_market_cap")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getUsdMarketCap() {
        return usdMarketCap;
    }

    /**
     * Setter for UsdMarketCap.
     * Market capitalization in the target currency
     * @param usdMarketCap Value for Double
     */
    @JsonSetter("usd_market_cap")
    public void setUsdMarketCap(Double usdMarketCap) {
        this.usdMarketCap = usdMarketCap;
    }

    /**
     * Getter for Usd24HVol.
     * 24-hour trading volume in the target currency
     * @return Returns the Double
     */
    @JsonGetter("usd_24h_vol")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getUsd24HVol() {
        return usd24HVol;
    }

    /**
     * Setter for Usd24HVol.
     * 24-hour trading volume in the target currency
     * @param usd24HVol Value for Double
     */
    @JsonSetter("usd_24h_vol")
    public void setUsd24HVol(Double usd24HVol) {
        this.usd24HVol = usd24HVol;
    }

    /**
     * Getter for Usd24HChange.
     * 24-hour price change percentage in the target currency
     * @return Returns the Double
     */
    @JsonGetter("usd_24h_change")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getUsd24HChange() {
        return usd24HChange;
    }

    /**
     * Setter for Usd24HChange.
     * 24-hour price change percentage in the target currency
     * @param usd24HChange Value for Double
     */
    @JsonSetter("usd_24h_change")
    public void setUsd24HChange(Double usd24HChange) {
        this.usd24HChange = usd24HChange;
    }

    /**
     * Getter for LastUpdatedAt.
     * Last updated timestamp in UNIX seconds
     * @return Returns the Double
     */
    @JsonGetter("last_updated_at")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getLastUpdatedAt() {
        return lastUpdatedAt;
    }

    /**
     * Setter for LastUpdatedAt.
     * Last updated timestamp in UNIX seconds
     * @param lastUpdatedAt Value for Double
     */
    @JsonSetter("last_updated_at")
    public void setLastUpdatedAt(Double lastUpdatedAt) {
        this.lastUpdatedAt = lastUpdatedAt;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this SimplePrice into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SimplePrice [" + "usd=" + usd + ", usdMarketCap=" + usdMarketCap + ", usd24HVol="
                + usd24HVol + ", usd24HChange=" + usd24HChange + ", lastUpdatedAt=" + lastUpdatedAt
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link SimplePrice.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SimplePrice.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .usd(getUsd())
                .usdMarketCap(getUsdMarketCap())
                .usd24HVol(getUsd24HVol())
                .usd24HChange(getUsd24HChange())
                .lastUpdatedAt(getLastUpdatedAt());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link SimplePrice}.
     */
    public static class Builder {
        private Double usd;
        private Double usdMarketCap;
        private Double usd24HVol;
        private Double usd24HChange;
        private Double lastUpdatedAt;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for usd.
         * @param  usd  Double value for usd.
         * @return Builder
         */
        public Builder usd(Double usd) {
            this.usd = usd;
            return this;
        }

        /**
         * Setter for usdMarketCap.
         * @param  usdMarketCap  Double value for usdMarketCap.
         * @return Builder
         */
        public Builder usdMarketCap(Double usdMarketCap) {
            this.usdMarketCap = usdMarketCap;
            return this;
        }

        /**
         * Setter for usd24HVol.
         * @param  usd24HVol  Double value for usd24HVol.
         * @return Builder
         */
        public Builder usd24HVol(Double usd24HVol) {
            this.usd24HVol = usd24HVol;
            return this;
        }

        /**
         * Setter for usd24HChange.
         * @param  usd24HChange  Double value for usd24HChange.
         * @return Builder
         */
        public Builder usd24HChange(Double usd24HChange) {
            this.usd24HChange = usd24HChange;
            return this;
        }

        /**
         * Setter for lastUpdatedAt.
         * @param  lastUpdatedAt  Double value for lastUpdatedAt.
         * @return Builder
         */
        public Builder lastUpdatedAt(Double lastUpdatedAt) {
            this.lastUpdatedAt = lastUpdatedAt;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link SimplePrice} object using the set fields.
         * @return {@link SimplePrice}
         */
        public SimplePrice build() {
            SimplePrice model =
                    new SimplePrice(usd, usdMarketCap, usd24HVol, usd24HChange, lastUpdatedAt);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
