/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * Sort2 to be used.
 */
public enum Sort2 {
    H24_VOLUME_USD_LIQUIDITY_DESC,

    H24_TX_COUNT_DESC,

    H24_VOLUME_USD_DESC;

    private static TreeMap<String, Sort2> valueMap = new TreeMap<>();
    private String value;

    static {
        H24_VOLUME_USD_LIQUIDITY_DESC.value = "h24_volume_usd_liquidity_desc";
        H24_TX_COUNT_DESC.value = "h24_tx_count_desc";
        H24_VOLUME_USD_DESC.value = "h24_volume_usd_desc";

        valueMap.put("h24_volume_usd_liquidity_desc", H24_VOLUME_USD_LIQUIDITY_DESC);
        valueMap.put("h24_tx_count_desc", H24_TX_COUNT_DESC);
        valueMap.put("h24_volume_usd_desc", H24_VOLUME_USD_DESC);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Sort2 constructFromString(String toConvert) throws IOException {
        Sort2 enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Sort2 fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Sort2 values to list of string values.
     * @param toConvert The list of Sort2 values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Sort2> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Sort2 enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 