/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for StatusUpdate2 type.
 */
public class StatusUpdate2 {
    private String description;
    private String category;
    private String createdAt;
    private String user;
    private String userTitle;
    private Boolean pin;
    private Project project;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public StatusUpdate2() {
    }

    /**
     * Initialization constructor.
     * @param  description  String value for description.
     * @param  category  String value for category.
     * @param  createdAt  String value for createdAt.
     * @param  user  String value for user.
     * @param  userTitle  String value for userTitle.
     * @param  pin  Boolean value for pin.
     * @param  project  Project value for project.
     */
    public StatusUpdate2(
            String description,
            String category,
            String createdAt,
            String user,
            String userTitle,
            Boolean pin,
            Project project) {
        this.description = description;
        this.category = category;
        this.createdAt = createdAt;
        this.user = user;
        this.userTitle = userTitle;
        this.pin = pin;
        this.project = project;
    }

    /**
     * Getter for Description.
     * Status update description
     * @return Returns the String
     */
    @JsonGetter("description")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDescription() {
        return description;
    }

    /**
     * Setter for Description.
     * Status update description
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for Category.
     * Status update category
     * @return Returns the String
     */
    @JsonGetter("category")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCategory() {
        return category;
    }

    /**
     * Setter for Category.
     * Status update category
     * @param category Value for String
     */
    @JsonSetter("category")
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * Getter for CreatedAt.
     * Status update creation time
     * @return Returns the String
     */
    @JsonGetter("created_at")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCreatedAt() {
        return createdAt;
    }

    /**
     * Setter for CreatedAt.
     * Status update creation time
     * @param createdAt Value for String
     */
    @JsonSetter("created_at")
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for User.
     * Status update user
     * @return Returns the String
     */
    @JsonGetter("user")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getUser() {
        return user;
    }

    /**
     * Setter for User.
     * Status update user
     * @param user Value for String
     */
    @JsonSetter("user")
    public void setUser(String user) {
        this.user = user;
    }

    /**
     * Getter for UserTitle.
     * Status update user title
     * @return Returns the String
     */
    @JsonGetter("user_title")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getUserTitle() {
        return userTitle;
    }

    /**
     * Setter for UserTitle.
     * Status update user title
     * @param userTitle Value for String
     */
    @JsonSetter("user_title")
    public void setUserTitle(String userTitle) {
        this.userTitle = userTitle;
    }

    /**
     * Getter for Pin.
     * Whether status update is pinned
     * @return Returns the Boolean
     */
    @JsonGetter("pin")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getPin() {
        return pin;
    }

    /**
     * Setter for Pin.
     * Whether status update is pinned
     * @param pin Value for Boolean
     */
    @JsonSetter("pin")
    public void setPin(Boolean pin) {
        this.pin = pin;
    }

    /**
     * Getter for Project.
     * Project information
     * @return Returns the Project
     */
    @JsonGetter("project")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Project getProject() {
        return project;
    }

    /**
     * Setter for Project.
     * Project information
     * @param project Value for Project
     */
    @JsonSetter("project")
    public void setProject(Project project) {
        this.project = project;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this StatusUpdate2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "StatusUpdate2 [" + "description=" + description + ", category=" + category
                + ", createdAt=" + createdAt + ", user=" + user + ", userTitle=" + userTitle
                + ", pin=" + pin + ", project=" + project + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link StatusUpdate2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link StatusUpdate2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .description(getDescription())
                .category(getCategory())
                .createdAt(getCreatedAt())
                .user(getUser())
                .userTitle(getUserTitle())
                .pin(getPin())
                .project(getProject());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link StatusUpdate2}.
     */
    public static class Builder {
        private String description;
        private String category;
        private String createdAt;
        private String user;
        private String userTitle;
        private Boolean pin;
        private Project project;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = description;
            return this;
        }

        /**
         * Setter for category.
         * @param  category  String value for category.
         * @return Builder
         */
        public Builder category(String category) {
            this.category = category;
            return this;
        }

        /**
         * Setter for createdAt.
         * @param  createdAt  String value for createdAt.
         * @return Builder
         */
        public Builder createdAt(String createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * Setter for user.
         * @param  user  String value for user.
         * @return Builder
         */
        public Builder user(String user) {
            this.user = user;
            return this;
        }

        /**
         * Setter for userTitle.
         * @param  userTitle  String value for userTitle.
         * @return Builder
         */
        public Builder userTitle(String userTitle) {
            this.userTitle = userTitle;
            return this;
        }

        /**
         * Setter for pin.
         * @param  pin  Boolean value for pin.
         * @return Builder
         */
        public Builder pin(Boolean pin) {
            this.pin = pin;
            return this;
        }

        /**
         * Setter for project.
         * @param  project  Project value for project.
         * @return Builder
         */
        public Builder project(Project project) {
            this.project = project;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link StatusUpdate2} object using the set fields.
         * @return {@link StatusUpdate2}
         */
        public StatusUpdate2 build() {
            StatusUpdate2 model =
                    new StatusUpdate2(description, category, createdAt, user, userTitle, pin,
                            project);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
