/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for Token type.
 */
public class Token {
    private double chainId;
    private String address;
    private String name;
    private String symbol;
    private double decimals;
    private String logoUri;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public Token() {
    }

    /**
     * Initialization constructor.
     * @param  chainId  double value for chainId.
     * @param  address  String value for address.
     * @param  name  String value for name.
     * @param  symbol  String value for symbol.
     * @param  decimals  double value for decimals.
     * @param  logoUri  String value for logoUri.
     */
    public Token(
            double chainId,
            String address,
            String name,
            String symbol,
            double decimals,
            String logoUri) {
        this.chainId = chainId;
        this.address = address;
        this.name = name;
        this.symbol = symbol;
        this.decimals = decimals;
        this.logoUri = logoUri;
    }

    /**
     * Getter for ChainId.
     * Chainlist's chain ID
     * @return Returns the double
     */
    @JsonGetter("chainId")
    public double getChainId() {
        return chainId;
    }

    /**
     * Setter for ChainId.
     * Chainlist's chain ID
     * @param chainId Value for double
     */
    @JsonSetter("chainId")
    public void setChainId(double chainId) {
        this.chainId = chainId;
    }

    /**
     * Getter for Address.
     * Token contract address
     * @return Returns the String
     */
    @JsonGetter("address")
    public String getAddress() {
        return address;
    }

    /**
     * Setter for Address.
     * Token contract address
     * @param address Value for String
     */
    @JsonSetter("address")
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * Getter for Name.
     * Token name
     * @return Returns the String
     */
    @JsonGetter("name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * Token name
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for Symbol.
     * Token symbol
     * @return Returns the String
     */
    @JsonGetter("symbol")
    public String getSymbol() {
        return symbol;
    }

    /**
     * Setter for Symbol.
     * Token symbol
     * @param symbol Value for String
     */
    @JsonSetter("symbol")
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    /**
     * Getter for Decimals.
     * Token decimals
     * @return Returns the double
     */
    @JsonGetter("decimals")
    public double getDecimals() {
        return decimals;
    }

    /**
     * Setter for Decimals.
     * Token decimals
     * @param decimals Value for double
     */
    @JsonSetter("decimals")
    public void setDecimals(double decimals) {
        this.decimals = decimals;
    }

    /**
     * Getter for LogoUri.
     * Token image URL
     * @return Returns the String
     */
    @JsonGetter("logoURI")
    public String getLogoUri() {
        return logoUri;
    }

    /**
     * Setter for LogoUri.
     * Token image URL
     * @param logoUri Value for String
     */
    @JsonSetter("logoURI")
    public void setLogoUri(String logoUri) {
        this.logoUri = logoUri;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this Token into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Token [" + "chainId=" + chainId + ", address=" + address + ", name=" + name
                + ", symbol=" + symbol + ", decimals=" + decimals + ", logoUri=" + logoUri
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link Token.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Token.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(chainId, address, name, symbol, decimals, logoUri);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link Token}.
     */
    public static class Builder {
        private double chainId;
        private String address;
        private String name;
        private String symbol;
        private double decimals;
        private String logoUri;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  chainId  double value for chainId.
         * @param  address  String value for address.
         * @param  name  String value for name.
         * @param  symbol  String value for symbol.
         * @param  decimals  double value for decimals.
         * @param  logoUri  String value for logoUri.
         */
        public Builder(double chainId, String address, String name, String symbol, double decimals,
                String logoUri) {
            this.chainId = chainId;
            this.address = address;
            this.name = name;
            this.symbol = symbol;
            this.decimals = decimals;
            this.logoUri = logoUri;
        }

        /**
         * Setter for chainId.
         * @param  chainId  double value for chainId.
         * @return Builder
         */
        public Builder chainId(double chainId) {
            this.chainId = chainId;
            return this;
        }

        /**
         * Setter for address.
         * @param  address  String value for address.
         * @return Builder
         */
        public Builder address(String address) {
            this.address = address;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for symbol.
         * @param  symbol  String value for symbol.
         * @return Builder
         */
        public Builder symbol(String symbol) {
            this.symbol = symbol;
            return this;
        }

        /**
         * Setter for decimals.
         * @param  decimals  double value for decimals.
         * @return Builder
         */
        public Builder decimals(double decimals) {
            this.decimals = decimals;
            return this;
        }

        /**
         * Setter for logoUri.
         * @param  logoUri  String value for logoUri.
         * @return Builder
         */
        public Builder logoUri(String logoUri) {
            this.logoUri = logoUri;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link Token} object using the set fields.
         * @return {@link Token}
         */
        public Token build() {
            Token model =
                    new Token(chainId, address, name, symbol, decimals, logoUri);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
