/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for VolumeUsd1 type.
 */
public class VolumeUsd1 {
    private String h24;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public VolumeUsd1() {
    }

    /**
     * Initialization constructor.
     * @param  h24  String value for h24.
     */
    public VolumeUsd1(
            String h24) {
        this.h24 = h24;
    }

    /**
     * Getter for H24.
     * @return Returns the String
     */
    @JsonGetter("h24")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getH24() {
        return h24;
    }

    /**
     * Setter for H24.
     * @param h24 Value for String
     */
    @JsonSetter("h24")
    public void setH24(String h24) {
        this.h24 = h24;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this VolumeUsd1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "VolumeUsd1 [" + "h24=" + h24 + ", additionalProperties=" + additionalProperties
                + "]";
    }

    /**
     * Builds a new {@link VolumeUsd1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link VolumeUsd1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .h24(getH24());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link VolumeUsd1}.
     */
    public static class Builder {
        private String h24;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for h24.
         * @param  h24  String value for h24.
         * @return Builder
         */
        public Builder h24(String h24) {
            this.h24 = h24;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link VolumeUsd1} object using the set fields.
         * @return {@link VolumeUsd1}
         */
        public VolumeUsd1 build() {
            VolumeUsd1 model =
                    new VolumeUsd1(h24);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
