/*
 * CoinGeckoDemoApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.coingecko.api.authentication;

import io.apimatic.core.authentication.HeaderAuth;
import java.util.HashMap;

public class HeaderAuthManager extends HeaderAuth implements HeaderAuthCredentials {

    /**
     * Private instance of the auth model containing the auth credentials.
     */
    private HeaderAuthModel authModel;

    /**
     * Constructor that sets custom header parameters.
     */
    public HeaderAuthManager(HeaderAuthModel authModel) {

        super(new HashMap<String,String>() {
            private static final long serialVersionUID = 1L;
            {
                put("x-cg-demo-api-key", authModel.getXCgDemoApiKey());
            }
        });

        this.authModel = authModel;
    }

    /**
     * String value for xCgDemoApiKey.
     * @return xCgDemoApiKey
     */
    public String getXCgDemoApiKey() {
        return authModel.getXCgDemoApiKey();
    }

    /**
     * Checks if provided credentials matched with existing ones.
     * @param xCgDemoApiKey String value for credentials.
     * @return true if credentials matched.
     */
    public boolean equals(String xCgDemoApiKey) {
        return xCgDemoApiKey.equals(getXCgDemoApiKey());
    }

    /**
     * Converts this HeaderAuthManager into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "HeaderAuthManager [" + "xCgDemoApiKey=" + getXCgDemoApiKey() + "]";
    }
    /**
    * Returns the error message if the auth credentials are not valid.
    * @return the auth specific error message.
    */
    @Override
    public String getErrorMessage() {
        String errorMessage = super.getErrorMessage();
        if (errorMessage == null) {
            return null;
        }

        return "HeaderAuth - " + errorMessage;
    }

}
